var PP7_PART_6 = [
  '                { id:\'P2-SAMPLE-002\', firstName:\'พิมพ์ใจ\', lastName:\'รักดี\', position:\'ที่ปรึกษางานขาย\', department:\'ขาย\', branch:\'ชลบุรี\', status:\'test_done\', phone:\'0810000002\', email:\'pimjai@test.com\', education:\'ปริญญาตรี\', major:\'บริหารธุรกิจ\', skills:\'การสื่อสาร, การเจรจา, CRM, Microsoft Office\', experience:\'2\', aiScore:90, appliedAt:\'2026-07-19T09:00:00Z\', testScores:{attitude:95,skill:88,cc:92,e3p:90,overall:91}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-19T09:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-20T11:00:00Z\',note:\'คะแนนรวม: 91\'}] },',
  '                { id:\'P2-SAMPLE-003\', firstName:\'ณัฐพล\', lastName:\'เก่งกาจ\', position:\'ช่างเทคนิคคอมพิวเตอร์\', department:\'IT\', branch:\'ชลบุรี\', status:\'screened\', phone:\'0810000003\', email:\'nuttapon@test.com\', education:\'ปวส.\', major:\'คอมพิวเตอร์\', skills:\'ซ่อมคอมพิวเตอร์, Network, ติดตั้งระบบ, Linux\', experience:\'1\', aiScore:75, appliedAt:\'2026-07-18T07:00:00Z\', testScores:{attitude:78,skill:82,cc:78,e3p:74,overall:78}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-18T07:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-19T09:00:00Z\',note:\'คะแนนรวม: 78\'},{action:\'คัดกรอง\',timestamp:\'2026-07-20T14:00:00Z\',note:\'HR คัดกรองผ่าน\'}] },',
  '                { id:\'P2-SAMPLE-004\', firstName:\'กัลยา\', lastName:\'ชาญชัย\', position:\'feel well\', department:\'บริการ\', branch:\'ชลบุรี\', status:\'test_done\', phone:\'0810000004\', email:\'kanlaya@test.com\', education:\'มัธยมศึกษา\', major:\'ไม่จำกัด\', skills:\'การสื่อสาร, การบริการ, ความเป็นมิตร, First Aid\', experience:\'4\', aiScore:86, appliedAt:\'2026-07-17T10:00:00Z\', testScores:{attitude:92,skill:80,cc:88,e3p:85,overall:86}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-17T10:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-18T13:00:00Z\',note:\'คะแนนรวม: 86\'}] },',
  '                { id:\'P2-SAMPLE-005\', firstName:\'วริศ\', lastName:\'มั่นคง\', position:\'ช่างยนต์\', department:\'บริการ\', branch:\'ชลบุรี\', status:\'screened\', phone:\'0810000005\', email:\'warit@test.com\', education:\'ปวส.\', major:\'ช่างยนต์\', skills:\'ซ่อมเครื่องยนต์, ระบบไฟฟ้า, ไฮบริด, EV, การวินิจฉัยปัญหา\', experience:\'5\', aiScore:94, appliedAt:\'2026-07-16T08:00:00Z\', testScores:{attitude:96,skill:95,cc:95,e3p:93,overall:95}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-16T08:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-17T10:00:00Z\',note:\'คะแนนรวม: 95\'},{action:\'คัดกรอง\',timestamp:\'2026-07-18T15:00:00Z\',note:\'HR คัดกรองผ่าน\'}] }',
  '            ];',
  '            // Add only if not already present',
  '            samples.forEach(s => {',
  '                if (!initial.find(a => a.id === s.id)) initial.push(s);',
  '            });',
  '            localStorage.setItem(\'pkg_initial_applicants\', JSON.stringify(initial));',
  '        }',
  '',
  '        function getP2Candidates() {',
  '            const all = getAllApplicants();',
  '            return all.filter(a => a.status === \'test_done\' || a.status === \'screened\');',
  '        }',
  '',
  '        function renderP2() {',
  '            initP2SampleData();',
  '            const candidates = getP2Candidates();',
  '            const container = document.getElementById(\'p2-content\');',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                    <div class="flex items-center justify-between mb-4">',
  '                        <h2 class="text-xl font-bold text-gray-800"><i class="fas fa-users text-purple-600 mr-2"></i>ผู้สมัครรอประเมิน CC (${candidates.length} คน)</h2>',
  '                        <span class="text-sm text-gray-500">สถานะ: test_done / screened</span>',
  '                    </div>',
  '                    ${candidates.length === 0 ? \'<p class="text-gray-500 text-center py-8">ไม่มีผู้สมัครรอประเมิน</p>\' : `',
  '                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">',
  '                        ${candidates.map(app => `',
  '                            <div class="border-2 border-gray-200 rounded-xl p-4 card-hover cursor-pointer hover:border-purple-500" onclick="startP2Assess(\'${app.id}\')">',
  '                                <div class="flex items-center gap-3 mb-3">',
  '                                    <div class="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center text-xl font-bold text-purple-600">${app.firstName.charAt(0)}</div>',
  '                                    <div>',
  '                                        <h3 class="font-bold text-gray-800">${app.firstName} ${app.lastName}</h3>',
  '                                        <p class="text-xs text-gray-500">${app.position}</p>',
  '                                    </div>',
  '                                </div>',
  '                                <div class="flex justify-between text-xs text-gray-600 mb-2">',
  '                                    <span>🎓 ${app.education || \'-\'}</span>',
  '                                    <span>💼 ${app.experience || 0} ปี</span>',
  '                                </div>',
  '                                <div class="flex justify-between items-center">',
  '                                    <span class="px-2 py-1 ${getStatusBadgeClass(app.status)} rounded-full text-xs font-semibold">${getStatusText(app.status)}</span>',
  '                                    ${app.aiScore ? `<span class="text-sm font-bold text-purple-600">AI: ${app.aiScore}</span>` : \'\'}',
  '                                </div>',
  '                                ${app.ccScores ? `<div class="mt-2 text-xs text-green-600 font-semibold">✅ ประเมินแล้ว (Score: ${calcCCOverall(app.ccScores)})</div>` : \'<div class="mt-2 text-xs text-amber-600 font-semibold">⏳ ยังไม่ประเมิน</div>\'}',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>`}',
  '                </div>',
  '                <div class="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-xl p-6 border border-purple-200">',
  '                    <h3 class="font-bold text-gray-800 mb-3">🧭 CC 7 ด้าน — Core Competency</h3>',
  '                    <div class="grid grid-cols-2 md:grid-cols-4 gap-3">',
  '                        ${CC_DIMENSIONS.map(cc => `',
  '                            <div class="bg-white p-3 rounded-lg text-center shadow-sm">',
  '                                <div class="text-2xl mb-1">${cc.icon}</div>',
  '                                <div class="text-xs font-bold" style="color:${cc.color}">${cc.key}</div>',
  '                                <div class="text-xs text-gray-600">${cc.name}</div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function startP2Assess(appId) {',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (!app) return;',
  '            p2CurrentApplicant = app;',
  '            p2CurrentCC = 0;',
  '            p2CurrentQuestion = 0;',
  '            p2Answers = {};',
  '            // If already assessed, load existing answers',
  '            if (app.ccScores) {',
  '                p2Answers = JSON.parse(JSON.stringify(app.ccScores));',
  '            }',
  '            renderP2Question();',
  '        }',
  '',
  '        function renderP2Question() {',
  '            const container = document.getElementById(\'p2-content\');',
  '            const cc = CC_DIMENSIONS[p2CurrentCC];',
  '            const q = cc.questions[p2CurrentQuestion];',
  '            const totalQ = CC_DIMENSIONS.reduce((s,c) => s + c.questions.length, 0);',
  '            const answered = Object.keys(p2Answers).length;',
  '            const progress = (answered / totalQ) * 100;',
  '            const currentKey = cc.key + \'_q\' + p2CurrentQuestion;',
  '            const currentVal = p2Answers[currentKey] || 0;',
  '',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <div class="flex items-center justify-between mb-4">',
  '                        <button onclick="renderP2()" class="text-purple-600 hover:text-purple-800 text-sm"><i class="fas fa-arrow-left mr-1"></i>กลับรายการ</button>',
  '                        <div class="text-sm text-gray-500">${p2CurrentApplicant.firstName} ${p2CurrentApplicant.lastName} — ${p2CurrentApplicant.position}</div>',
  '                    </div>',
  '                    <div class="flex justify-between items-center mb-2">',
  '                        <h3 class="text-lg font-bold" style="color:${cc.color}">${cc.icon} ${cc.key}: ${cc.name}</h3>',
  '                        <span class="text-sm text-gray-500">ข้อ ${p2CurrentQuestion+1}/${cc.questions.length}</span>',
  '                    </div>',
  '                    <div class="w-full bg-gray-200 rounded-full h-2 mb-6"><div class="h-2 rounded-full" style="width:${progress}%;background:${cc.color}"></div></div>',
  '',
  '                    <!-- CC Navigation Tabs -->',
  '                    <div class="flex flex-wrap gap-1 mb-6">',
  '                        ${CC_DIMENSIONS.map((c,i) => {',
  '                            const cAnswered = c.questions.filter((_,qi) => p2Answers[c.key+\'_q\'+qi]).length;',
  '                            const isComplete = cAnswered === c.questions.length;',
  '                            return `<button onclick="p2CurrentCC=${i};p2CurrentQuestion=0;renderP2Question()" class="px-2 py-1 rounded text-xs font-semibold ${i===p2CurrentCC?\'text-white\':\'bg-gray-100 text-gray-600 hover:bg-gray-200\'} ${isComplete && i!==p2CurrentCC?\'ring-2 ring-green-400\':\'\'}" style="${i===p2CurrentCC?\'background:\'+c.color:\'\'}">${c.key} ${isComplete?\'✓\':\'\'}</button>`;',
  '                        }).join(\'\')}',
  '                    </div>',
  '',
  '                    <div class="bg-gray-50 border-l-4 p-4 rounded-lg mb-6" style="border-color:${cc.color}">',
  '                        <p class="text-gray-800 font-medium">${q}</p>',
  '                    </div>',
  '                    <div class="space-y-3 mb-6">',
  '                        ${[1,2,3,4,5].map(score => `',
  '                            <div class="option-card border-2 rounded-lg p-4 ${currentVal===score?\'selected\':\'\'}" onclick="p2Answers[\'${currentKey}\']=${score};renderP2Question()" style="${currentVal===score?\'border-color:\'+cc.color+\';background:\'+cc.color+\';color:white\':\'\'}">',
  '                                <div class="flex items-center">',
  '                                    <div class="w-10 h-10 rounded-full border-2 flex items-center justify-center font-bold mr-4 ${currentVal===score?\'bg-white text-gray-800\':\'border-gray-300 text-gray-600\'}">${score}</div>',
  '                                    <span>${[\'\',\'น้อยมาก\',\'น้อย\',\'ปานกลาง\',\'ดี\',\'ดีมาก\'][score]}</span>',
  '                                </div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                    <div class="flex justify-between">',
  '                        <button onclick="p2Prev()" class="bg-gray-300 text-gray-700 px-6 py-3 rounded-lg hover:bg-gray-400 disabled:opacity-50" ${p2CurrentCC===0&&p2CurrentQuestion===0?\'disabled\':\'\'}><i class="fas fa-arrow-left mr-2"></i>ก่อนหน้า</button>',
  '                        ${p2CurrentCC===CC_DIMENSIONS.length-1&&p2CurrentQuestion===cc.questions.length-1',
  '                            ? `<button onclick="submitP2Assessment()" class="bg-green-600 text-white px-8 py-3 rounded-lg hover:bg-green-700 font-semibold"><i class="fas fa-check-circle mr-2"></i>ส่งผลการประเมิน</button>`',
  '                            : `<button onclick="p2Next()" class="text-white px-6 py-3 rounded-lg hover:opacity-90" style="background:${cc.color}">ถัดไป<i class="fas fa-arrow-right ml-2"></i></button>`}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function p2Next() {',
  '            const cc = CC_DIMENSIONS[p2CurrentCC];',
  '            if (p2CurrentQuestion < cc.questions.length - 1) { p2CurrentQuestion++; }',
  '            else if (p2CurrentCC < CC_DIMENSIONS.length - 1) { p2CurrentCC++; p2CurrentQuestion = 0; }',
  '            renderP2Question();',
  '        }',
  '        function p2Prev() {',
  '            if (p2CurrentQuestion > 0) { p2CurrentQuestion--; }',
  '            else if (p2CurrentCC > 0) { p2CurrentCC--; p2CurrentQuestion = CC_DIMENSIONS[p2CurrentCC].questions.length - 1; }',
  '            renderP2Question();',
  '        }',
  '',
  '        function submitP2Assessment() {',
  '            const totalQ = CC_DIMENSIONS.reduce((s,c) => s + c.questions.length, 0);',
  '            const answered = Object.keys(p2Answers).length;',
  '            if (answered < totalQ) {',
  '                if (!confirm(`ยังไม่ได้ตอบ ${totalQ - answered} ข้อ ต้องการส่งหรือไม่?`)) return;',
  '            } else {',
  '                if (!confirm(\'ต้องการส่งผลการประเมิน CC หรือไม่?\')) return;',
  '            }',
  '            // Calculate CC scores',
  '            const ccScores = {};',
  '            CC_DIMENSIONS.forEach(cc => {',
  '                let total = 0, count = 0;',
  '                cc.questions.forEach((_, qi) => {',
  '                    const val = p2Answers[cc.key + \'_q\' + qi];',
  '                    if (val) { total += val; count++; }',
  '                });',
  '                ccScores[cc.key] = count > 0 ? Math.round((total / (count * 5)) * 100) : 0;',
  '            });',
  '            // Save to applicant',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === p2CurrentApplicant.id);',
  '            if (app) {',
  '                app.ccScores = ccScores;',
  '                app.status = \'assessed\';',
  '                if (!app.history) app.history = [];',
  '                app.history.push({ action:\'ประเมิน CC\', timestamp: new Date().toISOString(), note: `CC Score: ${calcCCOverall(ccScores)}` });',
  '                saveApplicantData(app);',
  '            }',
  '            // Show result with radar chart',
  '            renderP2Result(ccScores);',
  '        }',
  '',
  '        function calcCCOverall(ccScores) {',
  '            const vals = Object.values(ccScores);',
  '            return vals.length ? Math.round(vals.reduce((a,b)=>a+b,0)/vals.length) : 0;',
  '        }',
  '',
  '        function renderP2Result(ccScores) {',
  '            const container = document.getElementById(\'p2-content\');',
  '            const overall = calcCCOverall(ccScores);',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <div class="text-center mb-6">',
  '                        <div class="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4"><i class="fas fa-check-circle text-green-600 text-4xl"></i></div>',
  '                        <h2 class="text-2xl font-bold text-gray-800 mb-2">ประเมิน CC เสร็จสิ้น!</h2>',
  '                        <p class="text-gray-600">${p2CurrentApplicant.firstName} ${p2CurrentApplicant.lastName}</p>',
  '                    </div>',
  '                    <div class="bg-gradient-to-r from-purple-600 to-indigo-600 text-white p-6 rounded-xl text-center mb-6">',
  '                        <p class="text-sm opacity-90 mb-1">คะแนน CC รวม</p>',
  '                        <p class="text-5xl font-bold">${overall}</p>',
  '                        <p class="text-sm opacity-75 mt-1">จาก 100 คะแนน</p>',
  '                    </div>',
  '                    <div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">',
  '                        ${CC_DIMENSIONS.map(cc => `',
  '                            <div class="p-3 rounded-lg text-center" style="background:${cc.color}15">',
  '                                <div class="text-xl mb-1">${cc.icon}</div>',
  '                                <div class="text-xs font-bold" style="color:${cc.color}">${cc.key}</div>',
  '                                <div class="text-xs text-gray-600 mb-1">${cc.name}</div>',
  '                                <div class="text-xl font-bold" style="color:${cc.color}">${ccScores[cc.key]}</div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                    <div class="flex justify-center mb-6" style="max-width:400px;margin:0 auto">',
  '                        <canvas id="p2RadarChart" width="400" height="400"></canvas>',
  '                    </div>',
  '                    <div class="flex gap-4">',
  '                        <button onclick="renderP2()" class="flex-1 bg-gray-300 text-gray-700 py-3 rounded-lg hover:bg-gray-400"><i class="fas fa-arrow-left mr-2"></i>กลับรายการ</button>',
  '                        <button onclick="sendToP3(\'${p2CurrentApplicant.id}\')" class="flex-1 bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 font-semibold"><i class="fas fa-arrow-right mr-2"></i>ส่งไป P3 จับคู่</button>',
  '                    </div>',
  '                </div>',
  '            `;',
  '            // Draw radar chart',
  '            setTimeout(() => drawP2Radar(ccScores), 100);',
  '        }',
  '',
  '        function drawP2Radar(ccScores) {',
  '            const ctx = document.getElementById(\'p2RadarChart\');',
  '            if (!ctx) return;',
  '            if (p2RadarChart) { p2RadarChart.destroy(); p2RadarChart = null; }',
  '            p2RadarChart = new Chart(ctx, {',
  '                type: \'radar\',',
  '                data: {',
  '                    labels: CC_DIMENSIONS.map(c => c.key + \' \' + c.name),',
  '                    datasets: [{',
  '                        label: \'CC Score\',',
  '                        data: CC_DIMENSIONS.map(c => ccScores[c.key]),',
  '                        backgroundColor: \'rgba(139, 92, 246, 0.2)\',',
  '                        borderColor: \'rgba(139, 92, 246, 1)\',',
  '                        borderWidth: 2,',
  '                        pointBackgroundColor: CC_DIMENSIONS.map(c => c.color),',
  '                        pointRadius: 5',
  '                    }]',
  '                },',
  '                options: {',
  '                    responsive: true,',
  '                    scales: {',
  '                        r: {',
  '                            beginAtZero: true,',
  '                            max: 100,',
  '                            ticks: { stepSize: 20, font: { size: 10 } },',
  '                            pointLabels: { font: { size: 11, family: \'Prompt\' } }',
  '                        }',
  '                    },',
  '                    plugins: { legend: { display: false } }',
  '                }',
  '            });',
  '        }',
  '',
  '        function sendToP3(appId) {',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (app) {',
  '                app.status = \'assessed\';',
  '                if (!app.history) app.history = [];',
  '                app.history.push({ action:\'ส่งไป P3\', timestamp: new Date().toISOString(), note:\'พร้อมจับคู่ตำแหน่งงาน\' });',
  '                saveApplicantData(app);',
  '            }',
  '            showTab(\'match\');',
  '            renderP3();',
  '        }',
  '',
  '        // ============================================================',
  '        // ===== P3: ระบบจับคู่คนกับงาน (Job Matching) =====',
  '        // ============================================================',
  '',
  '        const P3_JOB_POSITIONS = [',
  '            { id:\'JOB-001\', title:\'ช่างยนต์\', department:\'บริการ\', level:\'Junior\', salary:\'15,000-25,000\', requiredCC:{CC1:50,CC2:60,CC3:60,CC4:60,CC5:80,CC6:70,CC7:40}, requiredSkills:[\'ซ่อมเครื่องยนต์\',\'ระบบไฟฟ้า\',\'การวินิจฉัยปัญหา\'], education:\'ปวส.\' },',
  '            { id:\'JOB-002\', title:\'ที่ปรึกษางานขาย\', department:\'ขาย\', level:\'Entry\', salary:\'12,000-18,000+Comm\', requiredCC:{CC1:60,CC2:70,CC3:80,CC4:70,CC5:60,CC6:50,CC7:80}, requiredSkills:[\'การสื่อสาร\',\'การเจรจา\',\'Microsoft Office\'], education:\'มัธยมศึกษา\' },',
  '            { id:\'JOB-003\', title:\'ช่างเทคนิคคอมพิวเตอร์\', department:\'IT\', level:\'Junior\', salary:\'18,000-28,000\', requiredCC:{CC1:50,CC2:70,CC3:60,CC4:60,CC5:70,CC6:90,CC7:40}, requiredSkills:[\'ซ่อมคอมพิวเตอร์\',\'Network\',\'ติดตั้งระบบ\'], education:\'ปวส.\' },',
  '            { id:\'JOB-004\', title:\'feel well\', department:\'บริการ\', level:\'Entry\', salary:\'13,000-20,000\', requiredCC:{CC1:50,CC2:50,CC3:70,CC4:80,CC5:60,CC6:40,CC7:90}, requiredSkills:[\'การสื่อสาร\',\'การบริการ\',\'ความเป็นมิตร\'], education:\'มัธยมศึกษา\' },',
  '            { id:\'JOB-005\', title:\'หัวหน้าช่าง\', department:\'บริการ\', level:\'Senior\', salary:\'25,000-35,000\', requiredCC:{CC1:90,CC2:70,CC3:70,CC4:80,CC5:80,CC6:80,CC7:60}, requiredSkills:[\'ซ่อมเครื่องยนต์\',\'ระบบไฟฟ้า\',\'ผู้นำทีม\'], education:\'ปวส.\' },',
  '            { id:\'JOB-006\', title:\'ผู้จัดการสาขา\', department:\'บริหาร\', level:\'Manager\', salary:\'35,000-50,000\', requiredCC:{CC1:90,CC2:80,CC3:90,CC4:90,CC5:80,CC6:70,CC7:80}, requiredSkills:[\'การบริหาร\',\'การสื่อสาร\',\'การเจรจา\'], education:\'ปริญญาตรี\' }',
  '        ];',
  '',
  '        function getP3Candidates() {',
  '            const all = getAllApplicants();',
  '            return all.filter(a => a.status === \'assessed\');',
  '        }',
  '',
  '        function calcMatchScore(applicant, job) {',
  '            if (!applicant.ccScores) return 0;',
  '            // CC Match (60%)',
  '            let ccMatch = 0;',
  '            CC_DIMENSIONS.forEach(cc => {',
  '                const appScore = applicant.ccScores[cc.key] || 0;',
  '                const reqScore = job.requiredCC[cc.key] || 50;',
  '                const diff = appScore - reqScore;',
  '                if (diff >= 0) ccMatch += 100;',
  '                else ccMatch += Math.max(0, 100 + diff * 2);',
  '            });',
  '            ccMatch = ccMatch / 7;',
  '            // Skill Match (25%)',
  '            const appSkills = (applicant.skills || \'\').toLowerCase().split(\',\').map(s=>s.trim());',
  '            const reqSkills = job.requiredSkills.map(s=>s.toLowerCase());',
  '            const skillMatched = reqSkills.filter(rs => appSkills.some(as => as.includes(rs) || rs.includes(as)));',
  '            const skillScore = reqSkills.length > 0 ? (skillMatched.length / reqSkills.length) * 100 : 50;',
  '            // Experience Match (15%)',
  '            const exp = parseInt(applicant.experience || 0);',
  '            const expScore = job.level === \'Entry\' ? (exp >= 0 ? 100 : 50) :',
  '                             job.level === \'Junior\' ? Math.min(100, 50 + exp * 15) :',
  '                             job.level === \'Senior\' ? Math.min(100, 40 + exp * 12) :',
  '                             Math.min(100, 30 + exp * 10);',
  '            return Math.round(ccMatch * 0.6 + skillScore * 0.25 + expScore * 0.15);',
  '        }',
  '',
  '        function getTopMatches(applicant) {',
  '            return P3_JOB_POSITIONS.map(job => ({',
  '                ...job,',
  '                matchScore: calcMatchScore(applicant, job)',
  '            })).sort((a,b) => b.matchScore - a.matchScore).slice(0, 3);',
  '        }',
  '',
  '        function renderP3() {',
  '            initP2SampleData();',
  '            const candidates = getP3Candidates();',
  '            const container = document.getElementById(\'p3-content\');',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                    <div class="flex items-center justify-between mb-4">',
  '                        <h2 class="text-xl font-bold text-gray-800"><i class="fas fa-users text-emerald-600 mr-2"></i>ผู้สมัครรอจับคู่ (${candidates.length} คน)</h2>',
  '                        <span class="text-sm text-gray-500">สถานะ: assessed (ผ่าน P2 แล้ว)</span>',
  '                    </div>',
  '                    ${candidates.length === 0 ? \'<p class="text-gray-500 text-center py-8">ไม่มีผู้สมัครรอจับคู่ — กรุณาประเมิน CC ใน P2 ก่อน</p>\' : `',
  '                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">',
  '                        ${candidates.map(app => `',
  '                            <div class="border-2 border-gray-200 rounded-xl p-4 card-hover cursor-pointer hover:border-emerald-500" onclick="startP3Match(\'${app.id}\')">',
  '                                <div class="flex items-center gap-3 mb-3">',
  '                                    <div class="w-12 h-12 bg-emerald-100 rounded-full flex items-center justify-center text-xl font-bold text-emerald-600">${app.firstName.charAt(0)}</div>',
  '                                    <div>',
  '                                        <h3 class="font-bold text-gray-800">${app.firstName} ${app.lastName}</h3>',
  '                                        <p class="text-xs text-gray-500">${app.position || \'ไม่ระบุ\'}</p>',
  '                                    </div>',
  '                                </div>',
  '                                ${app.ccScores ? `',
  '                                    <div class="mb-2">',
  '                                        <div class="text-xs text-gray-600 mb-1">CC Score: <strong class="text-purple-600">${calcCCOverall(app.ccScores)}</strong></div>',
  '                                        <div class="w-full bg-gray-200 rounded-full h-2"><div class="bg-purple-600 h-2 rounded-full" style="width:${calcCCOverall(app.ccScores)}%"></div></div>',
  '                                    </div>',
  '                                    <div class="flex flex-wrap gap-1">',
  '                                        ${CC_DIMENSIONS.map(cc => `<span class="text-xs px-1.5 py-0.5 rounded" style="background:${cc.color}20;color:${cc.color}">${cc.key}:${app.ccScores[cc.key]}</span>`).join(\'\')}',
  '                                    </div>',
  '                                ` : \'\'}',
  '                                <div class="mt-3 text-xs text-emerald-600 font-semibold">🎯 คลิกเพื่อจับคู่ตำแหน่ง</div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>`}',
  '                </div>',
  '                <div class="bg-gradient-to-r from-emerald-50 to-teal-50 rounded-xl p-6 border border-emerald-200">',
  '                    <h3 class="font-bold text-gray-800 mb-3">📋 ตำแหน่งงานที่เปิดรับ (${P3_JOB_POSITIONS.length} ตำแหน่ง)</h3>',
  '                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">',
  '                        ${P3_JOB_POSITIONS.map(job => `',
  '                            <div class="bg-white p-3 rounded-lg shadow-sm">',
  '                                <div class="font-bold text-gray-800 text-sm">${job.title}</div>',
  '                                <div class="text-xs text-gray-500">${job.department} | ${job.level} | ${job.salary} ฿</div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function startP3Match(appId) {',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (!app || !app.ccScores) return;',
  '            const topMatches = getTopMatches(app);',
  '            const container = document.getElementById(\'p3-content\');',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <button onclick="renderP3()" class="mb-4 text-emerald-600 hover:text-emerald-800 text-sm"><i class="fas fa-arrow-left mr-1"></i>กลับรายการ</button>',
  '                    <div class="flex items-center gap-4 mb-6">',
  '                        <div class="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center text-2xl font-bold text-emerald-600">${app.firstName.charAt(0)}</div>',
  '                        <div>',
  '                            <h2 class="text-2xl font-bold text-gray-800">${app.firstName} ${app.lastName}</h2>',
  '                            <p class="text-gray-600">CC Score: <strong class="text-purple-600">${calcCCOverall(app.ccScores)}</strong> | ประสบการณ์: ${app.experience || 0} ปี</p>',
  '                        </div>',
  '                    </div>',
  '',
  '                    <!-- CC Radar -->',
  '                    <div class="flex justify-center mb-6" style="max-width:350px;margin:0 auto">',
  '                        <canvas id="p3RadarChart" width="350" height="350"></canvas>',
  '                    </div>',
  '',
  '                    <h3 class="text-xl font-bold text-gray-800 mb-4"><i class="fas fa-trophy text-amber-500 mr-2"></i>Top 3 ตำแหน่งที่เหมาะสม</h3>',
  '                    <div class="space-y-4 mb-6">',
  '                        ${topMatches.map((job, idx) => {',
  '                            const medals = [\'🥇\',\'🥈\',\'🥉\'];',
  '                            const colors = [\'from-amber-400 to-amber-500\',\'from-gray-300 to-gray-400\',\'from-amber-600 to-amber-700\'];',
  '                            return `',
  '                            <div class="border-2 ${idx===0?\'border-amber-400 bg-amber-50\':\'border-gray-200\'} rounded-xl p-5">',
  '                                <div class="flex items-center justify-between mb-3">',
  '                                    <div class="flex items-center gap-3">',
  '                                        <span class="text-3xl">${medals[idx]}</span>'
];
