var PP7_PART_3 = [
  '    <div id="loginModal" class="hidden fixed inset-0 bg-black bg-opacity-50 z-[9999] flex items-center justify-center p-4">',
  '        <div class="bg-white rounded-xl shadow-2xl max-w-md w-full p-8">',
  '            <div class="flex justify-between items-center mb-6">',
  '                <h2 class="text-2xl font-bold text-gray-800">เข้าสู่ระบบ</h2>',
  '                <button onclick="hideLogin()" class="text-gray-400 hover:text-gray-600">',
  '                    <i class="fas fa-times text-xl"></i>',
  '                </button>',
  '            </div>',
  '            <form onsubmit="handleLogin(event)">',
  '                <div class="mb-4">',
  '                    <label class="block text-sm font-medium text-gray-700 mb-2">เบอร์โทรศัพท์</label>',
  '                    <input type="tel" id="loginPhone" required class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-600">',
  '                </div>',
  '                <div class="mb-6">',
  '                    <label class="block text-sm font-medium text-gray-700 mb-2">รหัสผ่าน</label>',
  '                    <input type="password" id="loginPassword" required class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-600">',
  '                </div>',
  '                <button type="submit" class="w-full bg-purple-600 text-white py-3 rounded-lg hover:bg-purple-700 transition font-semibold">',
  '                    เข้าสู่ระบบ',
  '                </button>',
  '            </form>',
  '            <div class="text-center mt-4">',
  '                <p class="text-sm text-gray-600">ยังไม่มีบัญชี? <button onclick="hideLogin(); showRegister()" class="text-purple-600 hover:underline">ลงทะเบียน</button></p>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Register Modal -->',
  '    <div id="registerModal" class="hidden fixed inset-0 bg-black bg-opacity-50 z-[9999] flex items-center justify-center p-4">',
  '        <div class="bg-white rounded-xl shadow-2xl max-w-md w-full p-8 max-h-[90vh] overflow-y-auto">',
  '            <div class="flex justify-between items-center mb-6">',
  '                <h2 class="text-2xl font-bold text-gray-800">ลงทะเบียนผู้สมัคร</h2>',
  '                <button onclick="hideRegister()" class="text-gray-400 hover:text-gray-600">',
  '                    <i class="fas fa-times text-xl"></i>',
  '                </button>',
  '            </div>',
  '            <form onsubmit="handleRegister(event)">',
  '                <div class="mb-4">',
  '                    <label class="block text-sm font-medium text-gray-700 mb-2">ชื่อ-นามสกุล</label>',
  '                    <input type="text" id="regName" required class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-600">',
  '                </div>',
  '                <div class="mb-4">',
  '                    <label class="block text-sm font-medium text-gray-700 mb-2">เบอร์โทรศัพท์</label>',
  '                    <input type="tel" id="regPhone" required class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-600">',
  '                </div>',
  '                <div class="mb-4">',
  '                    <label class="block text-sm font-medium text-gray-700 mb-2">Email</label>',
  '                    <input type="email" id="regEmail" required class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-600">',
  '                </div>',
  '                <div class="mb-4">',
  '                    <label class="block text-sm font-medium text-gray-700 mb-2">รหัสผ่าน</label>',
  '                    <input type="password" id="regPassword" required class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-600">',
  '                </div>',
  '                <button type="submit" class="w-full bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 transition font-semibold">',
  '                    ลงทะเบียน',
  '                </button>',
  '            </form>',
  '            <div class="text-center mt-4">',
  '                <p class="text-sm text-gray-600">มีบัญชีแล้ว? <button onclick="hideRegister(); showLogin()" class="text-purple-600 hover:underline">เข้าสู่ระบบ</button></p>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <script>',
  '        // ===== DEMO DATA =====',
  '        const POSITIONS = [',
  '            { id: \'POS-001\', title: \'ช่างยนต์\', department: \'บริการ\', level: \'Junior\', salary: \'15,000 - 25,000 บาท\', location: \'ชลบุรี\', requirements: { education: \'ปวส.\', major: \'ช่างยนต์, เครื่องกล\', skills: [\'ซ่อมเครื่องยนต์\', \'ระบบไฟฟ้า\', \'การวินิจฉัยปัญหา\'], experience: \'0-2 ปี\' }, description: \'ซ่อมบำรุงและให้บริการลูกค้าด้านเครื่องยนต์\' },',
  '            { id: \'POS-002\', title: \'ที่ปรึกษางานขาย\', department: \'ขาย\', level: \'Entry\', salary: \'12,000 - 18,000 บาท + คอมมิชชั่น\', location: \'ชลบุรี\', requirements: { education: \'มัธยมศึกษา\', major: \'ไม่จำกัด\', skills: [\'การสื่อสาร\', \'การเจรจา\', \'Microsoft Office\'], experience: \'ไม่จำเป็น\' }, description: \'ให้คำปรึกษาและขายผลิตภัณฑ์ให้กับลูกค้า\' },',
  '            { id: \'POS-003\', title: \'ช่างเทคนิคคอมพิวเตอร์\', department: \'IT\', level: \'Junior\', salary: \'18,000 - 28,000 บาท\', location: \'ชลบุรี\', requirements: { education: \'ปวส.\', major: \'คอมพิวเตอร์, ไอที\', skills: [\'ซ่อมคอมพิวเตอร์\', \'ติดตั้งระบบ\', \'Network\'], experience: \'0-2 ปี\' }, description: \'ซ่อมบำรุงและติดตั้งระบบคอมพิวเตอร์\' },',
  '            { id: \'POS-004\', title: \'feel well\', department: \'บริการ\', level: \'Entry\', salary: \'13,000 - 20,000 บาท\', location: \'ชลบุรี\', requirements: { education: \'มัธยมศึกษา\', major: \'ไม่จำกัด\', skills: [\'การสื่อสาร\', \'การบริการ\', \'ความเป็นมิตร\'], experience: \'ไม่จำเป็น\' }, description: \'ให้บริการลูกค้าและดูแลความพึงพอใจ\' }',
  '        ];',
  '',
  '        const TESTS = {',
  '            attitude: { title: \'ทัศนคติ\', icon: \'fa-smile\', time: 20, questions: [',
  '                { id: \'att1\', text: \'เมื่อเผชิญกับปัญหาในการทำงาน คุณมักจะ...\', options: [\'หลีกเลี่ยงและรอให้คนอื่นแก้\', \'รู้สึกท้อแท้และยอมแพ้\', \'พยายามแก้ด้วยตัวเองก่อน\', \'ขอความช่วยเหลือจากทีม\', \'วิเคราะห์ปัญหาและหาทางแก้ไขอย่างเป็นระบบ\'] },',
  '                { id: \'att2\', text: \'คุณรู้สึกอย่างไรเมื่อได้รับคำวิจารณ์เชิงลบ?\', options: [\'โกรธและปฏิเสธ\', \'เสียใจและท้อแท้\', \'ยอมรับแต่ไม่เปลี่ยนแปลง\', \'นำมาพิจารณาและปรับปรุง\', \'ขอบคุณและนำไปพัฒนาทันที\'] },',
  '                { id: \'att3\', text: \'เมื่อต้องทำงานภายใต้ความกดดัน คุณ...\', options: [\'ทำงานไม่ได้เลย\', \'รู้สึกเครียดมาก\', \'พยายามทำให้เสร็จ\', \'จัดลำดับความสำคัญและทำงานต่อ\', \'ใช้ความกดดันเป็นแรงจูงใจ\'] }',
  '            ]},',
  '            skill: { title: \'ทักษะ\', icon: \'fa-tools\', time: 30, questions: [',
  '                { id: \'skill1\', text: \'คุณสามารถใช้ Microsoft Office ได้ในระดับใด?\', options: [\'ไม่สามารถใช้ได้เลย\', \'พื้นฐาน\', \'ปานกลาง\', \'ขั้นสูง\', \'เชี่ยวชาญ\'] },',
  '                { id: \'skill2\', text: \'คุณมีความสามารถในการใช้ภาษาอังกฤษในระดับใด?\', options: [\'ไม่สามารถใช้ได้เลย\', \'พื้นฐาน\', \'ปานกลาง\', \'ดี\', \'เชี่ยวชาญ\'] }',
  '            ]},',
  '            cc: { title: \'ทุนองค์กร (CC 7 ด้าน)\', icon: \'fa-star\', time: 25, questions: [',
  '                { id: \'cc1\', text: \'CC1: คุณเคยเป็นผู้นำทีมหรือไม่?\', options: [\'ไม่เคย\', \'เคยแต่ไม่ประสบความสำเร็จ\', \'เคยและทำได้ดี\', \'เป็นผู้นำที่สร้างทีมที่แข็งแกร่ง\', \'เป็นผู้นำที่สร้างแรงบันดาลใจ\'] },',
  '                { id: \'cc2\', text: \'CC2: คุณเคยสร้างนวัตกรรมหรือปรับปรุงกระบวนการทำงานหรือไม่?\', options: [\'ไม่เคย\', \'คิดแต่ไม่ได้ทำ\', \'ทำบ้าง\', \'ทำบ่อย\', \'ทำทุกครั้งที่มีโอกาส\'] }',
  '            ]},',
  '            e3p: { title: \'3E3P\', icon: \'fa-chart-line\', time: 15, questions: [',
  '                { id: \'e1\', text: \'3E-Engagement: คุณรู้สึกผูกพันกับองค์กรก่อนหน้าอย่างไร?\', options: [\'ไม่รู้สึก\', \'ทำงานตามหน้าที่\', \'รู้สึกดี\', \'ผูกพันมาก\', \'พร้อมทุ่มเท\'] },',
  '                { id: \'e2\', text: \'3E-Empowerment: คุณกล้าตัดสินใจในงานที่ได้รับมอบหมายหรือไม่?\', options: [\'ไม่กล้า\', \'รอคำสั่ง\', \'ตัดสินใจเล็กน้อย\', \'กล้าตัดสินใจ\', \'กล้าและรับผิดชอบ\'] }',
  '            ]}',
  '        };',
  '',
  '        // ===== STATE =====',
  '        let currentView = \'applicant\';',
  '        let currentStep = \'positions\';',
  '        let selectedPosition = null;',
  '        let applicantData = null;',
  '        let aiResult = null;',
  '        let currentTest = \'attitude\';',
  '        let currentQuestion = 0;',
  '        let testAnswers = { attitude: {}, skill: {}, cc: {}, e3p: {} };',
  '        let currentApplicantId = null;',
  '',
  '        // ===== INITIALIZATION =====',
  '        document.addEventListener(\'DOMContentLoaded\', async () => {',
  '            await initializeData();',
  '            switchView(\'applicant\');',
  '        });',
  '',
  '        async function initializeData() {',
  '            // โหลดข้อมูลตั้งต้นจาก JSON',
  '            try {',
  '                const response = await fetch(\'applicant-data.json\');',
  '                const initialData = await response.json();',
  '                ',
  '                // เก็บข้อมูลตั้งต้นใน localStorage (ถ้ายังไม่มี)',
  '                if (!localStorage.getItem(\'pkg_initial_loaded\')) {',
  '                    localStorage.setItem(\'pkg_initial_applicants\', JSON.stringify(initialData.initialApplicants));',
  '                    localStorage.setItem(\'pkg_positions\', JSON.stringify(initialData.positions));',
  '                    localStorage.setItem(\'pkg_banks\', JSON.stringify(initialData.banks));',
  '                    localStorage.setItem(\'pkg_hospitals\', JSON.stringify(initialData.hospitals));',
  '                    localStorage.setItem(\'pkg_reject_reasons\', JSON.stringify(initialData.rejectReasons));',
  '                    localStorage.setItem(\'pkg_interview_times\', JSON.stringify(initialData.interviewTimes));',
  '                    localStorage.setItem(\'pkg_initial_loaded\', \'true\');',
  '                }',
  '            } catch (error) {',
  '                console.error(\'Error loading initial data:\', error);',
  '            }',
  '            ',
  '            // โหลดข้อมูลผู้ใช้ demo',
  '            const users = JSON.parse(localStorage.getItem(\'pkg_users\') || \'[]\');',
  '            if (!users.find(u => u.phone === \'0812345678\')) {',
  '                users.push({ id: \'HR-DEMO\', phone: \'0812345678\', password: btoa(\'hr1234\'), name: \'HR Manager\', email: \'hr@pkg.com\', role: \'hr\', status: \'active\' });',
  '            }',
  '            if (!users.find(u => u.phone === \'0898765432\')) {',
  '                users.push({ id: \'APP-DEMO\', phone: \'0898765432\', password: btoa(\'app1234\'), name: \'นายสมชาย ใจดี\', email: \'somchai@test.com\', role: \'applicant\', status: \'active\' });',
  '            }',
  '            localStorage.setItem(\'pkg_users\', JSON.stringify(users));',
  '        }',
  '        ',
  '        // ฟังก์ชันดึงข้อมูลผู้สมัครทั้งหมด (ข้อมูลตั้งต้น + ข้อมูลใหม่)',
  '        function getAllApplicants() {',
  '            const initial = JSON.parse(localStorage.getItem(\'pkg_initial_applicants\') || \'[]\');',
  '            const newApps = JSON.parse(localStorage.getItem(\'pkg_applications\') || \'[]\');',
  '            return [...initial, ...newApps];',
  '        }',
  '',
  '        // ===== SWITCH VIEW =====',
  '        function switchView(view) {',
  '            currentView = view;',
  '            document.getElementById(\'view-applicant\').className = view === \'applicant\' ? \'flex-1 py-3 rounded-lg font-semibold bg-purple-600 text-white\' : \'flex-1 py-3 rounded-lg font-semibold bg-gray-200 text-gray-700\';',
  '            document.getElementById(\'view-hr\').className = view === \'hr\' ? \'flex-1 py-3 rounded-lg font-semibold bg-purple-600 text-white\' : \'flex-1 py-3 rounded-lg font-semibold bg-gray-200 text-gray-700\';',
  '            ',
  '            if (view === \'applicant\') {',
  '                currentStep = \'positions\';',
  '                renderApplicantView();',
  '            } else {',
  '                renderHRView();',
  '            }',
  '        }',
  '',
  '        // ===== RENDER APPLICANT VIEW =====',
  '        function renderApplicantView() {',
  '            const content = document.getElementById(\'content-area\');',
  '            if (currentStep === \'positions\') renderPositionsList();',
  '            else if (currentStep === \'application\') renderApplicationForm();',
  '            else if (currentStep === \'result\') renderAIResult();',
  '            else if (currentStep === \'test\') renderTestView();',
  '            else if (currentStep === \'testResult\') renderTestResult();',
  '            else if (currentStep === \'dashboard\') renderApplicantDashboard();',
  '        }',
  '',
  '        // ===== STEP 1: POSITIONS LIST =====',
  '        function renderPositionsList() {',
  '            const content = document.getElementById(\'content-area\');',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <h2 class="text-2xl font-bold text-gray-800 mb-6"><i class="fas fa-briefcase text-purple-600 mr-2"></i>ตำแหน่งงานที่เปิดรับ</h2>',
  '                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">',
  '                        ${POSITIONS.map(pos => `',
  '                            <div class="position-card border-2 border-gray-200 rounded-xl p-6 cursor-pointer hover:border-purple-600" onclick="selectPosition(\'${pos.id}\')">',
  '                                <div class="flex justify-between items-start mb-4">',
  '                                    <div>',
  '                                        <h3 class="text-xl font-bold text-gray-800 mb-2">${pos.title}</h3>',
  '                                        <p class="text-sm text-gray-600 mb-1"><i class="fas fa-building mr-1"></i>${pos.department}</p>',
  '                                        <p class="text-sm text-gray-600 mb-1"><i class="fas fa-chart-line mr-1"></i>${pos.level}</p>',
  '                                    </div>',
  '                                    <div class="text-right">',
  '                                        <p class="text-lg font-bold text-purple-600">${pos.salary}</p>',
  '                                        <p class="text-xs text-gray-500">${pos.location}</p>',
  '                                    </div>',
  '                                </div>',
  '                                <p class="text-sm text-gray-700 mb-4">${pos.description}</p>',
  '                                <div class="border-t pt-4">',
  '                                    <p class="text-xs font-semibold text-gray-600 mb-2">คุณสมบัติ:</p>',
  '                                    <ul class="text-xs text-gray-600 space-y-1">',
  '                                        <li><i class="fas fa-graduation-cap mr-1"></i>${pos.requirements.education} - ${pos.requirements.major}</li>',
  '                                        <li><i class="fas fa-tools mr-1"></i>${pos.requirements.skills.join(\', \')}</li>',
  '                                        <li><i class="fas fa-clock mr-1"></i>ประสบการณ์: ${pos.requirements.experience}</li>',
  '                                    </ul>',
  '                                </div>',
  '                                <button class="mt-4 w-full bg-purple-600 text-white py-2 rounded-lg hover:bg-purple-700 transition"><i class="fas fa-paper-plane mr-2"></i>สมัครงาน</button>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function selectPosition(positionId) {',
  '            selectedPosition = POSITIONS.find(p => p.id === positionId);',
  '            currentStep = \'application\';',
  '            renderApplicationForm();',
  '        }',
  '',
  '        // ===== STEP 2: APPLICATION FORM =====',
  '        function renderApplicationForm() {',
  '            // Redirect to full application form (form-register.html)',
  '            const positionId = selectedPosition ? selectedPosition.id : \'\';',
  '            window.location.href = `form-register.html?position=${positionId}`;',
  '        }',
  '',
  '        function backToPositions() { currentStep = \'positions\'; renderPositionsList(); }',
  '',
  '        // ===== SUBMIT APPLICATION & AI ANALYSIS =====',
  '        function submitApplication(event) {',
  '            event.preventDefault();',
  '            applicantData = {',
  '                firstname: document.getElementById(\'app-firstname\').value,',
  '                lastname: document.getElementById(\'app-lastname\').value,',
  '                phone: document.getElementById(\'app-phone\').value,',
  '                email: document.getElementById(\'app-email\').value,',
  '                education: document.getElementById(\'app-education\').value,',
  '                major: document.getElementById(\'app-major\').value,',
  '                gpa: document.getElementById(\'app-gpa\').value,',
  '                institution: document.getElementById(\'app-institution\').value,',
  '                skills: document.getElementById(\'app-skills\').value,',
  '                experience: document.getElementById(\'app-experience\').value || \'0\',',
  '                experienceDetail: document.getElementById(\'app-experience-detail\').value',
  '            };',
  '            ',
  '            // บันทึกข้อมูลผู้สมัครลง localStorage',
  '            const applications = JSON.parse(localStorage.getItem(\'pkg_applications\') || \'[]\');',
  '            currentApplicantId = \'APP-\' + Date.now().toString().slice(-6);',
  '            const newApp = {',
  '                id: currentApplicantId,',
  '                firstName: applicantData.firstname,',
  '                lastName: applicantData.lastname,',
  '                phone: applicantData.phone,',
  '                email: applicantData.email,',
  '                position: selectedPosition.title,',
  '                department: selectedPosition.department,',
  '                branch: selectedPosition.location,',
  '                status: \'new\',',
  '                appliedAt: new Date().toISOString(),',
  '                education: applicantData.education,',
  '                major: applicantData.major,',
  '                skills: applicantData.skills,',
  '                experience: applicantData.experience,',
  '                testScores: null,',
  '                aiScore: null,',
  '                interviewDate: null,',
  '                interviewTime: null,',
  '                startDate: null,',
  '                history: [{ action: \'สมัครงาน\', timestamp: new Date().toISOString(), note: \'ส่งใบสมัครสำเร็จ\' }]',
  '            };',
  '            applications.push(newApp);',
  '            localStorage.setItem(\'pkg_applications\', JSON.stringify(applications));',
  '            ',
  '            aiResult = analyzeApplication(applicantData, selectedPosition);',
  '            newApp.aiScore = aiResult.score;',
  '            localStorage.setItem(\'pkg_applications\', JSON.stringify(applications));',
  '            ',
  '            currentStep = \'result\';',
  '            renderAIResult();',
  '        }',
  '',
  '        function analyzeApplication(formData, position) {',
  '            let score = 0, reasons = [], suggestions = [];',
  '            const educationLevels = { \'มัธยมศึกษา\': 1, \'ปวส.\': 2, \'ปริญญาตรี\': 3, \'ปริญญาโท\': 4 };',
  '            const requiredLevel = position.requirements.education === \'ปวส. ขึ้นไป\' ? 2 : 2;',
  '            const applicantLevel = educationLevels[formData.education] || 0;',
  '            ',
  '            if (applicantLevel >= requiredLevel) { score += 30; reasons.push(\'✅ วุฒิการศึกษาตรงกับข้อกำหนด\'); }',
  '            else { reasons.push(\'⚠️ วุฒิการศึกษาไม่ตรงกับข้อกำหนด\'); suggestions.push(\'ต้องการวุฒิ \' + position.requirements.education); }',
  '            ',
  '            const majorKeywords = position.requirements.major.toLowerCase().split(\',\').map(m => m.trim());',
  '            const applicantMajor = formData.major.toLowerCase();',
  '            const majorMatch = majorKeywords.some(keyword => applicantMajor.includes(keyword) || keyword.includes(applicantMajor));',
  '            ',
  '            if (majorMatch || position.requirements.major.includes(\'ไม่จำกัด\')) { score += 25; reasons.push(\'✅ สาขาวิชาตรงกับข้อกำหนด\'); }',
  '            else { reasons.push(\'⚠️ สาขาวิชาไม่ตรงกับข้อกำหนดโดยตรง\'); suggestions.push(\'สาขาที่ต้องการ: \' + position.requirements.major); }',
  '            ',
  '            const requiredSkills = position.requirements.skills.map(s => s.toLowerCase());',
  '            const applicantSkills = formData.skills.toLowerCase().split(\',\').map(s => s.trim());',
  '            const skillMatch = requiredSkills.filter(skill => applicantSkills.some(appSkill => appSkill.includes(skill)));',
  '            ',
  '            if (skillMatch.length >= requiredSkills.length * 0.7) { score += 25; reasons.push(\'✅ มีทักษะที่ตรงกับข้อกำหนด (\' + skillMatch.length + \'/\' + requiredSkills.length + \')\'); }',
  '            else if (skillMatch.length > 0) { score += 15; reasons.push(\'⚠️ มีทักษะบางส่วน (\' + skillMatch.length + \'/\' + requiredSkills.length + \')\'); suggestions.push(\'ทักษะที่ต้องการ: \' + position.requirements.skills.join(\', \')); }',
  '            else { reasons.push(\'❌ ไม่มีทักษะที่ตรงกับข้อกำหนด\'); suggestions.push(\'ทักษะที่ต้องการ: \' + position.requirements.skills.join(\', \')); }',
  '            ',
  '            const expMatch = position.requirements.experience.includes(\'ไม่จำเป็น\') || parseInt(formData.experience) >= parseInt(position.requirements.experience);',
  '            if (expMatch) { score += 20; reasons.push(\'✅ มีประสบการณ์เพียงพอ\'); }',
  '            else { score += 10; reasons.push(\'⚠️ ประสบการณ์น้อยกว่าที่ต้องการ\'); suggestions.push(\'ประสบการณ์ที่ต้องการ: \' + position.requirements.experience); }',
  '            ',
  '            const isSuitable = score >= 70;',
  '            return { score, isSuitable, reasons, suggestions };',
  '        }',
  '',
  '        // ===== STEP 3: AI RESULT =====',
  '        function renderAIResult() {',
  '            const content = document.getElementById(\'content-area\');',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <h2 class="text-2xl font-bold text-gray-800 mb-2"><i class="fas fa-robot text-purple-600 mr-2"></i>ผลการวิเคราะห์จาก AI</h2>',
  '                    <p class="text-gray-600 mb-6">ตำแหน่ง: <strong>${selectedPosition.title}</strong></p>',
  '                    ',
  '                    <div class="bg-gradient-to-r ${aiResult.isSuitable ? \'from-green-500 to-green-600\' : \'from-orange-500 to-orange-600\'} text-white p-6 rounded-xl mb-6">',
  '                        <div class="flex justify-between items-center">',
  '                            <div>',
  '                                <p class="text-sm opacity-90 mb-1">คะแนนความเหมาะสม</p>',
  '                                <p class="text-5xl font-bold mb-2">${aiResult.score}/100</p>',
  '                                <p class="text-lg font-semibold">${aiResult.isSuitable ? \'✅ เหมาะสมกับตำแหน่งนี้\' : \'⚠️ ยังไม่เหมาะสมกับตำแหน่งนี้\'}</p>',
  '                            </div>',
  '                            <div class="text-6xl opacity-50">${aiResult.isSuitable ? \'✅\' : \'⚠️\'}</div>',
  '                        </div>',
  '                    </div>',
  '',
  '                    <div class="mb-6">',
  '                        <h3 class="text-lg font-semibold text-gray-700 mb-4"><i class="fas fa-list-check mr-2"></i>รายละเอียดการวิเคราะห์</h3>',
  '                        <div class="space-y-2">${aiResult.reasons.map(r => `<div class="bg-gray-50 p-3 rounded-lg"><p class="text-sm">${r}</p></div>`).join(\'\')}</div>',
  '                    </div>',
  '',
  '                    ${aiResult.suggestions.length > 0 ? `<div class="mb-6"><h3 class="text-lg font-semibold text-gray-700 mb-4"><i class="fas fa-lightbulb mr-2"></i>ข้อเสนอแนะ</h3><div class="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-lg"><ul class="text-sm text-yellow-800 space-y-1">${aiResult.suggestions.map(s => `<li>→ ${s}</li>`).join(\'\')}</ul></div></div>` : \'\'}',
  '',
  '                    ${aiResult.isSuitable ? `',
  '                        <div class="bg-green-50 border-l-4 border-green-400 p-4 rounded-lg mb-6">',
  '                            <div class="flex items-start"><div class="text-green-600 mr-2 mt-1">✅</div><div><p class="font-semibold text-green-800 mb-1">ยินดีด้วย! คุณสมบัติของคุณเหมาะสมกับตำแหน่งนี้</p><p class="text-sm text-green-700">ขั้นตอนถัดไป: ทำแบบทดสอบ 4 ชุด เพื่อประเมินศักยภาพ</p></div></div>',
  '                        </div>',
  '                        <button onclick="startTest()" class="w-full bg-purple-600 text-white py-3 rounded-lg hover:bg-purple-700 transition font-semibold"><i class="fas fa-tasks mr-2"></i>เริ่มทำแบบทดสอบ</button>',
  '                    ` : `',
  '                        <div class="flex space-x-4">',
  '                            <button onclick="backToPositions()" class="flex-1 bg-gray-300 text-gray-700 py-3 rounded-lg hover:bg-gray-400 transition">← เลือกตำแหน่งอื่น</button>',
  '                            <button onclick="switchView(\'hr\')" class="flex-1 bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 transition">👔 ดูมุมมอง HR</button>',
  '                        </div>',
  '                    `}',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        // ===== STEP 4: TEST =====',
  '        function startTest() {',
  '            currentStep = \'test\';',
  '            currentTest = \'attitude\';',
  '            currentQuestion = 0;',
  '            testAnswers = { attitude: {}, skill: {}, cc: {}, e3p: {} };',
  '            renderTestView();',
  '        }',
  '',
  '        function renderTestView() {',
  '            const content = document.getElementById(\'content-area\');',
  '            const test = TESTS[currentTest];',
  '            const question = test.questions[currentQuestion];',
  '            const totalQuestions = Object.values(TESTS).reduce((sum, t) => sum + t.questions.length, 0);',
  '            const answeredQuestions = Object.values(testAnswers).reduce((sum, t) => sum + Object.keys(t).length, 0);',
  '            const progress = (answeredQuestions / totalQuestions) * 100;',
  '            ',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <div class="flex justify-between items-center mb-6">',
  '                        <h2 class="text-2xl font-bold text-gray-800"><i class="fas fa-tasks text-purple-600 mr-2"></i>แบบทดสอบ</h2>',
  '                        <div class="text-sm text-gray-600">ความคืบหน้า: ${Math.round(progress)}%</div>',
  '                    </div>',
  '                    <div class="w-full bg-gray-200 rounded-full h-3 mb-6"><div class="bg-purple-600 h-3 rounded-full" style="width: ${progress}%"></div></div>',
  '                    ',
  '                    <div class="flex space-x-2 mb-6">',
  '                        ${Object.keys(TESTS).map(key => `',
  '                            <button onclick="switchTest(\'${key}\')" class="flex-1 py-2 rounded-lg text-sm font-semibold ${key === currentTest ? \'bg-purple-600 text-white\' : \'bg-gray-200 text-gray-700\'}">',
  '                                <i class="fas ${TESTS[key].icon} mr-1"></i>${TESTS[key].title}',
  '                            </button>',
  '                        `).join(\'\')}',
  '                    </div>',
  '',
  '                    <div class="mb-6">',
  '                        <div class="flex justify-between items-center mb-4">',
  '                            <h3 class="text-lg font-semibold text-gray-800">${test.title} - ข้อ ${currentQuestion + 1}/${test.questions.length}</h3>',
  '                            <span class="text-sm text-gray-500">เวลา: ${test.time} นาที</span>',
  '                        </div>',
  '                        <div class="bg-purple-50 border-l-4 border-purple-600 p-4 rounded-lg mb-6">',
  '                            <p class="text-gray-800 font-medium">${question.text}</p>',
  '                        </div>',
  '                        <div class="space-y-3">',
  '                            ${question.options.map((opt, idx) => `',
  '                                <div class="option-card border-2 border-gray-200 rounded-lg p-4 ${testAnswers[currentTest][question.id] === idx + 1 ? \'selected\' : \'\'}" onclick="selectAnswer(\'${currentTest}\', \'${question.id}\', ${idx + 1})">',
  '                                    <div class="flex items-center">',
  '                                        <div class="w-8 h-8 rounded-full border-2 ${testAnswers[currentTest][question.id] === idx + 1 ? \'bg-white text-purple-600\' : \'border-gray-300\'} flex items-center justify-center font-semibold mr-3">${String.fromCharCode(65 + idx)}</div>',
  '                                        <span class="flex-1">${opt}</span>',
  '                                    </div>',
  '                                </div>',
  '                            `).join(\'\')}'
];
