var PP7_PART_8 = [
  '                        if (company.positions) {',
  '                            company.positions.forEach(pos => {',
  '                                allPositions.push({',
  '                                    company: company.name,',
  '                                    ...pos',
  '                                });',
  '                            });',
  '                        }',
  '                    });',
  '                    externalTbody.innerHTML = allPositions.slice(0, 20).map(pos => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2">${pos.company}</td>',
  '                            <td class="px-3 py-2">${pos[\'สาขา\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${pos[\'ฝ่าย\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${pos[\'แผนก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${pos[\'ตำแหน่ง\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${pos[\'ตำแหน่งEn\'] || \'-\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render flowchart tax',
  '                const flowchartTbody = document.getElementById(\'flowchart-tbody\');',
  '                if (flowchartTbody && data.flowchartTax.companies) {',
  '                    flowchartTbody.innerHTML = data.flowchartTax.companies.map(company => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2 font-mono">${company.code}</td>',
  '                            <td class="px-3 py-2 font-semibold">${company.name}</td>',
  '                            <td class="px-3 py-2">${company.flows.S ? `<a href="${company.flows.S}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                            <td class="px-3 py-2">${company.flows.XL ? `<a href="${company.flows.XL}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                            <td class="px-3 py-2">${company.flows.S_M ? `<a href="${company.flows.S_M}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                            <td class="px-3 py-2">${company.flows.M_M ? `<a href="${company.flows.M_M}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                            <td class="px-3 py-2">${company.flows.XL_M ? `<a href="${company.flows.XL_M}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render internal companies',
  '                const internalTbody = document.getElementById(\'internal-tbody\');',
  '                if (internalTbody && data.internalCompanies.teams) {',
  '                    internalTbody.innerHTML = data.internalCompanies.teams.map(item => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2">${item[\'วันที่ส่ง\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'รหัสสมาชิก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ชื่อสมาชิก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ประเทศ\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บริษัท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ทีม\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บทบาท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'จุดมุ่งหมาย\'] || \'-\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '            } catch (error) {',
  '                console.error(\'Error loading business structure data:\', error);',
  '            }',
  '        }',
  '        ',
  '        // Load data when page loads',
  '        if (document.readyState === \'loading\') {',
  '            document.addEventListener(\'DOMContentLoaded\', loadBusinessStructureData);',
  '        } else {',
  '            loadBusinessStructureData();',
  '        }',
  '    </script>',
  '    <script>',
  '        /* ═══════════════════════════════════════════',
  '           PP7 KPI Dashboard — War Room Style',
  '           Renders measurement dashboards for P1-P7 tabs',
  '           Pure CSS bars/cards — no Chart.js dependency',
  '           ═══════════════════════════════════════════ */',
  '        var _pp7DashRendered = {};',
  '        function pctClass(pct){',
  '            if(pct>=90) return "g";',
  '            if(pct>=70) return "y";',
  '            return "r";',
  '        }',
  '        function statusColor(pct){',
  '            if(pct>=90) return "green";',
  '            if(pct>=70) return "yellow";',
  '            return "red";',
  '        }',
  '        function barColor(pct){',
  '            if(pct>=90) return "#10b981";',
  '            if(pct>=70) return "#f59e0b";',
  '            return "#ef4444";',
  '        }',
  '        function kpiCard(label,val,target,unit,pct){',
  '            var pc = pctClass(pct);',
  '            var st = statusColor(pct);',
  '            return \'<div class="pp7-kpi \'+st+\'"><div class="lbl">\'+label+\'</div>\'+',
  '                   \'<div class="val">\'+val+(unit?\' \'+unit:\'\')+\'</div>\'+',
  '                   \'<div class="tgt">เป้า: \'+target+(unit?\' \'+unit:\'\')+\'</div>\'+',
  '                   \'<div class="pct \'+pc+\'">\'+pct.toFixed(1)+\'%</div></div>\';',
  '        }',
  '        function barRow(label,actual,target,unit){',
  '            var pct = target>0 ? (actual/target*100) : 0;',
  '            var w = Math.min(pct,100);',
  '            var c = barColor(pct);',
  '            return \'<div class="pp7-bar-row"><div class="pp7-bar-label">\'+label+\'</div>\'+',
  '                   \'<div class="pp7-bar-track"><div class="pp7-bar-fill" style="width:\'+w+\'%;background:\'+c+\'">\'+pct.toFixed(0)+\'%</div></div>\'+',
  '                   \'<div class="pp7-bar-val">\'+actual+(unit?\' \'+unit:\'\')+\'</div></div>\';',
  '        }',
  '        function buildDashboard(containerId,title,icon,kpis,bars){',
  '            var c = document.getElementById(containerId);',
  '            if(!c) return;',
  '            var h = \'<div class="pp7-dash-title">\'+icon+\' \'+title+\'</div>\';',
  '            if(kpis && kpis.length){',
  '                h += \'<div class="pp7-kpi-row">\';',
  '                kpis.forEach(function(k){',
  '                    h += kpiCard(k.label,k.val,k.target,k.unit,k.pct);',
  '                });',
  '                h += \'</div>\';',
  '            }',
  '            if(bars && bars.length){',
  '                h += \'<div class="pp7-bar-chart">\';',
  '                bars.forEach(function(b){',
  '                    h += barRow(b.label,b.val,b.target,b.unit);',
  '                });',
  '                h += \'</div>\';',
  '            }',
  '            c.innerHTML = h;',
  '            _pp7DashRendered[containerId] = true;',
  '        }',
  '        function renderPP7Dashboard(tabName){',
  '            var map = {recruit:\'p1-dashboard\',assess:\'p2-dashboard\',match:\'p3-dashboard\',performance:\'p4-dashboard\',develop:\'p5-dashboard\',welfare:\'p6-dashboard\',quality:\'p7-dashboard\'};',
  '            var id = map[tabName];',
  '            if(!id || _pp7DashRendered[id]) return;',
  '            if(tabName===\'recruit\') renderP1Dash();',
  '            else if(tabName===\'assess\') renderP2Dash();',
  '            else if(tabName===\'match\') renderP3Dash();',
  '            else if(tabName===\'performance\') renderP4Dash();',
  '            else if(tabName===\'develop\') renderP5Dash();',
  '            else if(tabName===\'welfare\') renderP6Dash();',
  '            else if(tabName===\'quality\') renderP7Dash();',
  '        }',
  '        /* P1: แสวงหา — Recruitment Funnel */',
  '        function renderP1Dash(){',
  '            buildDashboard(\'p1-dashboard\',\'P1 แสวงหา — Recruitment Dashboard\',\'🔎\',',
  '                [{label:\'ผู้สมัครทั้งหมด\',val:7800,target:10000,unit:\'คน\',pct:78.0},',
  '                 {label:\'จ้างงานแล้ว\',val:2700,target:3000,unit:\'คน\',pct:90.0},',
  '                 {label:\'อยู่ใน Pipeline\',val:186,target:250,unit:\'คน\',pct:74.4},',
  '                 {label:\'เปิดอัตรารองรับ\',val:42,target:50,unit:\'ตำแหน่ง\',pct:84.0},',
  '                 {label:\'ส่ง Offer\',val:12,target:20,unit:\'คน\',pct:60.0},',
  '                 {label:\'อัตราคัดกรองผ่าน\',val:34.6,target:50,unit:\'%\',pct:69.2}],',
  '                [{label:\'Referral\',val:12,target:15,unit:\'คน\'},{label:\'LinkedIn\',val:8,target:10,unit:\'คน\'},{label:\'Job Board\',val:7,target:10,unit:\'คน\'},{label:\'Website\',val:6,target:8,unit:\'คน\'},{label:\'Agency\',val:5,target:7,unit:\'คน\'}]);',
  '        }',
  '        /* P2: หยั่งประเมิน — Assessment */',
  '        function renderP2Dash(){',
  '            buildDashboard(\'p2-dashboard\',\'P2 หยั่งประเมิน — Assessment Dashboard\',\'🧭\',',
  '                [{label:\'ผู้เข้าประเมิน\',val:186,target:250,unit:\'คน\',pct:74.4},',
  '                 {label:\'ประเมินเสร็จ\',val:152,target:200,unit:\'คน\',pct:76.0},',
  '                 {label:\'CC เฉลี่ย (7 ด้าน)\',val:3.5,target:4.0,unit:\'คะแนน\',pct:87.5},',
  '                 {label:\'ผ่านเกณฑ์ (≥3.0)\',val:138,target:180,unit:\'คน\',pct:76.7},',
  '                 {label:\'AI Score ทำนายผล\',val:82,target:90,unit:\'%\',pct:91.1}],',
  '                [{label:\'CC1 มุ่งเน้นลูกค้า\',val:3.8,target:4.0,unit:\'คะแนน\'},{label:\'CC2 ทำงานเป็นทีม\',val:3.6,target:4.0,unit:\'คะแนน\'},{label:\'CC3 แก้ปัญหา\',val:3.4,target:4.0,unit:\'คะแนน\'},{label:\'CC4 สื่อสาร\',val:3.2,target:4.0,unit:\'คะแนน\'},{label:\'CC5 ปรับตัว\',val:3.5,target:4.0,unit:\'คะแนน\'},{label:\'CC6 ความรับผิดชอบ\',val:3.7,target:4.0,unit:\'คะแนน\'},{label:\'CC7 ความเป็นมืออาชีพ\',val:3.9,target:4.0,unit:\'คะแนน\'}]);',
  '        }',
  '        /* P3: จับคู่คนกับงาน — Matching */',
  '        function renderP3Dash(){',
  '            buildDashboard(\'p3-dashboard\',\'P3 จับคู่คนกับงาน — Matching Dashboard\',\'🤝\',',
  '                [{label:\'ตำแหน่งเปิดรับ\',val:42,target:50,unit:\'ตำแหน่ง\',pct:84.0},',
  '                 {label:\'จับคู่สำเร็จ\',val:28,target:42,unit:\'คู่\',pct:66.7},',
  '                 {label:\'Match Score เฉลี่ย\',val:78,target:85,unit:\'%\',pct:91.8},',
  '                 {label:\'รอจับคู่\',val:14,target:42,unit:\'คน\',pct:33.3},',
  '                 {label:\'เข้าทดลองงาน\',val:22,target:28,unit:\'คน\',pct:78.6}],',
  '                [{label:\'Tech/IT\',val:8,target:12,unit:\'คู่\'},{label:\'Sales\',val:6,target:10,unit:\'คู่\'},{label:\'Operations\',val:5,target:8,unit:\'คู่\'},{label:\'Finance\',val:4,target:6,unit:\'คู่\'},{label:\'HR\',val:3,target:4,unit:\'คู่\'},{label:\'R&D\',val:2,target:2,unit:\'คู่\'}]);',
  '        }',
  '        /* P4: ประเมินผล — Performance */',
  '        function renderP4Dash(){',
  '            buildDashboard(\'p4-dashboard\',\'P4 ประเมินผล — Performance Dashboard\',\'📈\',',
  '                [{label:\'พนักงานรับการประเมิน\',val:1247,target:1247,unit:\'คน\',pct:100.0},',
  '                 {label:\'KPI ผ่านเกณฑ์\',val:1098,target:1247,unit:\'คน\',pct:88.1},',
  '                 {label:\'360° Review สำเร็จ\',val:980,target:1247,unit:\'คน\',pct:78.6},',
  '                 {label:\'เครดิตประจำปี\',val:1120,target:1247,unit:\'คน\',pct:89.8},',
  '                 {label:\'KPI เฉลี่ยองค์กร\',val:3.6,target:4.0,unit:\'คะแนน\',pct:90.0}],',
  '                [{label:\'Top (5)\',val:180,target:200,unit:\'คน\'},{label:\'Solid (4)\',val:420,target:500,unit:\'คน\'},{label:\'Develop (3)\',val:480,target:400,unit:\'คน\'},{label:\'Exceeds (4.5)\',val:95,target:100,unit:\'คน\'},{label:\'Meets (3.5)\',val:72,target:80,unit:\'คน\'}]);',
  '        }',
  '        /* P5: พัฒนา — Development */',
  '        function renderP5Dash(){',
  '            buildDashboard(\'p5-dashboard\',\'P5 พัฒนา — Development Dashboard\',\'🎓\',',
  '                [{label:\'พนักงานมี IDP\',val:1050,target:1247,unit:\'คน\',pct:84.2},',
  '                 {label:\'หลักสูตรเปิดสอน\',val:38,target:45,unit:\'หลักสูตร\',pct:84.4},',
  '                 {label:\'ผ่านการอบรม\',val:920,target:1200,unit:\'คน\',pct:76.7},',
  '                 {label:\'เส้นทางอาชีพ (Career Path)\',val:650,target:1247,unit:\'คน\',pct:52.1},',
  '                 {label:\'ชั่วโมงเรียนรู้เฉลี่ย\',val:28,target:40,unit:\'ชม./ปี\',pct:70.0}],',
  '                [{label:\'PMSG\',val:175,target:210,unit:\'คน\'},{label:\'AAMG\',val:280,target:340,unit:\'คน\'},{label:\'CPDG\',val:240,target:280,unit:\'คน\'},{label:\'RPLCG\',val:100,target:120,unit:\'คน\'},{label:\'RAFCOG\',val:70,target:85,unit:\'คน\'},{label:\'PGHG\',val:120,target:150,unit:\'คน\'}]);',
  '        }',
  '        /* P6: ค่าตอบแทน — Compensation */',
  '        function renderP6Dash(){',
  '            buildDashboard(\'p6-dashboard\',\'P6 ค่าตอบแทน — Compensation Dashboard\',\'💰\',',
  '                [{label:\'เงินเดือนในช่วง (Band)\',val:92,target:100,unit:\'%\',pct:92.0},',
  '                 {label:\'จ่ายโบนัสครบ\',val:1180,target:1247,unit:\'คน\',pct:94.6},',
  '                 {label:\'ปรับเงินเดือนตามผล\',val:1100,target:1247,unit:\'คน\',pct:88.2},',
  '                 {label:\'สวัสดิการครบ\',val:1240,target:1247,unit:\'คน\',pct:99.4},',
  '                 {label:\'Compa Ratio เฉลี่ย\',val:1.02,target:1.0,unit:\'อัตรา\',pct:102.0}],',
  '                [{label:\'PMSG\',val:95,target:100,unit:\'%\'},{label:\'AAMG\',val:88,target:100,unit:\'%\'},{label:\'CPDG\',val:91,target:100,unit:\'%\'},{label:\'RPLCG\',val:96,target:100,unit:\'%\'},{label:\'RAFCOG\',val:93,target:100,unit:\'%\'},{label:\'PGHG\',val:90,target:100,unit:\'%\'},{label:\'21RTG\',val:85,target:100,unit:\'%\'}]);',
  '        }',
  '        /* P7: คุณภาพชีวิต — Wellbeing */',
  '        function renderP7Dash(){',
  '            buildDashboard(\'p7-dashboard\',\'P7 คุณภาพชีวิต — Wellbeing Dashboard\',\'🌿\',',
  '                [{label:\'Engagement Score\',val:78,target:85,unit:\'%\',pct:91.8},',
  '                 {label:\'Retention Rate\',val:96.2,target:95,unit:\'%\',pct:100.0},',
  '                 {label:\'Turnover Rate\',val:3.8,target:5.0,unit:\'%\',pct:76.0},',
  '                 {label:\'Satisfaction Index\',val:4.1,target:4.5,unit:\'คะแนน\',pct:91.1},',
  '                 {label:\'พนักงานใหม่/เดือน\',val:12,target:15,unit:\'คน\',pct:80.0},',
  '                 {label:\'ลาออก/เดือน\',val:3,target:5,unit:\'คน\',pct:60.0}],',
  '                [{label:\'❤️ Health\',val:4.0,target:4.5,unit:\'คะแนน\'},{label:\'💎 Wealth\',val:3.8,target:4.5,unit:\'คะแนน\'},{label:\'🧘 Well-being\',val:4.2,target:4.5,unit:\'คะแนน\'},{label:\'⏰ Time\',val:3.9,target:4.5,unit:\'คะแนน\'},{label:\'🎉 Fun\',val:4.3,target:4.5,unit:\'คะแนน\'}]);',
  '        }',
  '    </script>',
  '</body>',
  '</html>',
  ''
];
