var PP7_PART_4 = [
  '                                    <div>',
  '                                        <h3 class="text-xl font-bold text-gray-800 mb-2">${pos.title}</h3>',
  '                                        <p class="text-sm text-gray-600 mb-1"><i class="fas fa-building mr-1"></i>${pos.department}</p>',
  '                                        <p class="text-sm text-gray-600 mb-1"><i class="fas fa-chart-line mr-1"></i>${pos.level}</p>',
  '                                    </div>',
  '                                    <div class="text-right">',
  '                                        <p class="text-lg font-bold text-purple-600">${pos.salary}</p>',
  '                                        <p class="text-xs text-gray-500">${pos.location}</p>',
  '                                    </div>',
  '                                </div>',
  '                                <p class="text-sm text-gray-700 mb-4">${pos.description}</p>',
  '                                <div class="border-t pt-4">',
  '                                    <p class="text-xs font-semibold text-gray-600 mb-2">คุณสมบัติ:</p>',
  '                                    <ul class="text-xs text-gray-600 space-y-1">',
  '                                        <li><i class="fas fa-graduation-cap mr-1"></i>${pos.requirements.education} - ${pos.requirements.major}</li>',
  '                                        <li><i class="fas fa-tools mr-1"></i>${pos.requirements.skills.join(\', \')}</li>',
  '                                        <li><i class="fas fa-clock mr-1"></i>ประสบการณ์: ${pos.requirements.experience}</li>',
  '                                    </ul>',
  '                                </div>',
  '                                <button class="mt-4 w-full bg-purple-600 text-white py-2 rounded-lg hover:bg-purple-700 transition"><i class="fas fa-paper-plane mr-2"></i>สมัครงาน</button>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function selectPosition(positionId) {',
  '            selectedPosition = POSITIONS.find(p => p.id === positionId);',
  '            currentStep = \'application\';',
  '            renderApplicationForm();',
  '        }',
  '',
  '        // ===== STEP 2: APPLICATION FORM =====',
  '        function renderApplicationForm() {',
  '            // Redirect to full application form (form-register.html)',
  '            const positionId = selectedPosition ? selectedPosition.id : \'\';',
  '            window.location.href = `form-register.html?position=${positionId}`;',
  '        }',
  '',
  '        function backToPositions() { currentStep = \'positions\'; renderPositionsList(); }',
  '',
  '        // ===== SUBMIT APPLICATION & AI ANALYSIS =====',
  '        function submitApplication(event) {',
  '            event.preventDefault();',
  '            applicantData = {',
  '                firstname: document.getElementById(\'app-firstname\').value,',
  '                lastname: document.getElementById(\'app-lastname\').value,',
  '                phone: document.getElementById(\'app-phone\').value,',
  '                email: document.getElementById(\'app-email\').value,',
  '                education: document.getElementById(\'app-education\').value,',
  '                major: document.getElementById(\'app-major\').value,',
  '                gpa: document.getElementById(\'app-gpa\').value,',
  '                institution: document.getElementById(\'app-institution\').value,',
  '                skills: document.getElementById(\'app-skills\').value,',
  '                experience: document.getElementById(\'app-experience\').value || \'0\',',
  '                experienceDetail: document.getElementById(\'app-experience-detail\').value',
  '            };',
  '            ',
  '            // บันทึกข้อมูลผู้สมัครลง localStorage',
  '            const applications = JSON.parse(localStorage.getItem(\'pkg_applications\') || \'[]\');',
  '            currentApplicantId = \'APP-\' + Date.now().toString().slice(-6);',
  '            const newApp = {',
  '                id: currentApplicantId,',
  '                firstName: applicantData.firstname,',
  '                lastName: applicantData.lastname,',
  '                phone: applicantData.phone,',
  '                email: applicantData.email,',
  '                position: selectedPosition.title,',
  '                department: selectedPosition.department,',
  '                branch: selectedPosition.location,',
  '                status: \'new\',',
  '                appliedAt: new Date().toISOString(),',
  '                education: applicantData.education,',
  '                major: applicantData.major,',
  '                skills: applicantData.skills,',
  '                experience: applicantData.experience,',
  '                testScores: null,',
  '                aiScore: null,',
  '                interviewDate: null,',
  '                interviewTime: null,',
  '                startDate: null,',
  '                history: [{ action: \'สมัครงาน\', timestamp: new Date().toISOString(), note: \'ส่งใบสมัครสำเร็จ\' }]',
  '            };',
  '            applications.push(newApp);',
  '            localStorage.setItem(\'pkg_applications\', JSON.stringify(applications));',
  '            ',
  '            aiResult = analyzeApplication(applicantData, selectedPosition);',
  '            newApp.aiScore = aiResult.score;',
  '            localStorage.setItem(\'pkg_applications\', JSON.stringify(applications));',
  '            ',
  '            currentStep = \'result\';',
  '            renderAIResult();',
  '        }',
  '',
  '        function analyzeApplication(formData, position) {',
  '            let score = 0, reasons = [], suggestions = [];',
  '            const educationLevels = { \'มัธยมศึกษา\': 1, \'ปวส.\': 2, \'ปริญญาตรี\': 3, \'ปริญญาโท\': 4 };',
  '            const requiredLevel = position.requirements.education === \'ปวส. ขึ้นไป\' ? 2 : 2;',
  '            const applicantLevel = educationLevels[formData.education] || 0;',
  '            ',
  '            if (applicantLevel >= requiredLevel) { score += 30; reasons.push(\'✅ วุฒิการศึกษาตรงกับข้อกำหนด\'); }',
  '            else { reasons.push(\'⚠️ วุฒิการศึกษาไม่ตรงกับข้อกำหนด\'); suggestions.push(\'ต้องการวุฒิ \' + position.requirements.education); }',
  '            ',
  '            const majorKeywords = position.requirements.major.toLowerCase().split(\',\').map(m => m.trim());',
  '            const applicantMajor = formData.major.toLowerCase();',
  '            const majorMatch = majorKeywords.some(keyword => applicantMajor.includes(keyword) || keyword.includes(applicantMajor));',
  '            ',
  '            if (majorMatch || position.requirements.major.includes(\'ไม่จำกัด\')) { score += 25; reasons.push(\'✅ สาขาวิชาตรงกับข้อกำหนด\'); }',
  '            else { reasons.push(\'⚠️ สาขาวิชาไม่ตรงกับข้อกำหนดโดยตรง\'); suggestions.push(\'สาขาที่ต้องการ: \' + position.requirements.major); }',
  '            ',
  '            const requiredSkills = position.requirements.skills.map(s => s.toLowerCase());',
  '            const applicantSkills = formData.skills.toLowerCase().split(\',\').map(s => s.trim());',
  '            const skillMatch = requiredSkills.filter(skill => applicantSkills.some(appSkill => appSkill.includes(skill)));',
  '            ',
  '            if (skillMatch.length >= requiredSkills.length * 0.7) { score += 25; reasons.push(\'✅ มีทักษะที่ตรงกับข้อกำหนด (\' + skillMatch.length + \'/\' + requiredSkills.length + \')\'); }',
  '            else if (skillMatch.length > 0) { score += 15; reasons.push(\'⚠️ มีทักษะบางส่วน (\' + skillMatch.length + \'/\' + requiredSkills.length + \')\'); suggestions.push(\'ทักษะที่ต้องการ: \' + position.requirements.skills.join(\', \')); }',
  '            else { reasons.push(\'❌ ไม่มีทักษะที่ตรงกับข้อกำหนด\'); suggestions.push(\'ทักษะที่ต้องการ: \' + position.requirements.skills.join(\', \')); }',
  '            ',
  '            const expMatch = position.requirements.experience.includes(\'ไม่จำเป็น\') || parseInt(formData.experience) >= parseInt(position.requirements.experience);',
  '            if (expMatch) { score += 20; reasons.push(\'✅ มีประสบการณ์เพียงพอ\'); }',
  '            else { score += 10; reasons.push(\'⚠️ ประสบการณ์น้อยกว่าที่ต้องการ\'); suggestions.push(\'ประสบการณ์ที่ต้องการ: \' + position.requirements.experience); }',
  '            ',
  '            const isSuitable = score >= 70;',
  '            return { score, isSuitable, reasons, suggestions };',
  '        }',
  '',
  '        // ===== STEP 3: AI RESULT =====',
  '        function renderAIResult() {',
  '            const content = document.getElementById(\'content-area\');',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <h2 class="text-2xl font-bold text-gray-800 mb-2"><i class="fas fa-robot text-purple-600 mr-2"></i>ผลการวิเคราะห์จาก AI</h2>',
  '                    <p class="text-gray-600 mb-6">ตำแหน่ง: <strong>${selectedPosition.title}</strong></p>',
  '                    ',
  '                    <div class="bg-gradient-to-r ${aiResult.isSuitable ? \'from-green-500 to-green-600\' : \'from-orange-500 to-orange-600\'} text-white p-6 rounded-xl mb-6">',
  '                        <div class="flex justify-between items-center">',
  '                            <div>',
  '                                <p class="text-sm opacity-90 mb-1">คะแนนความเหมาะสม</p>',
  '                                <p class="text-5xl font-bold mb-2">${aiResult.score}/100</p>',
  '                                <p class="text-lg font-semibold">${aiResult.isSuitable ? \'✅ เหมาะสมกับตำแหน่งนี้\' : \'⚠️ ยังไม่เหมาะสมกับตำแหน่งนี้\'}</p>',
  '                            </div>',
  '                            <div class="text-6xl opacity-50">${aiResult.isSuitable ? \'✅\' : \'⚠️\'}</div>',
  '                        </div>',
  '                    </div>',
  '',
  '                    <div class="mb-6">',
  '                        <h3 class="text-lg font-semibold text-gray-700 mb-4"><i class="fas fa-list-check mr-2"></i>รายละเอียดการวิเคราะห์</h3>',
  '                        <div class="space-y-2">${aiResult.reasons.map(r => `<div class="bg-gray-50 p-3 rounded-lg"><p class="text-sm">${r}</p></div>`).join(\'\')}</div>',
  '                    </div>',
  '',
  '                    ${aiResult.suggestions.length > 0 ? `<div class="mb-6"><h3 class="text-lg font-semibold text-gray-700 mb-4"><i class="fas fa-lightbulb mr-2"></i>ข้อเสนอแนะ</h3><div class="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-lg"><ul class="text-sm text-yellow-800 space-y-1">${aiResult.suggestions.map(s => `<li>→ ${s}</li>`).join(\'\')}</ul></div></div>` : \'\'}',
  '',
  '                    ${aiResult.isSuitable ? `',
  '                        <div class="bg-green-50 border-l-4 border-green-400 p-4 rounded-lg mb-6">',
  '                            <div class="flex items-start"><div class="text-green-600 mr-2 mt-1">✅</div><div><p class="font-semibold text-green-800 mb-1">ยินดีด้วย! คุณสมบัติของคุณเหมาะสมกับตำแหน่งนี้</p><p class="text-sm text-green-700">ขั้นตอนถัดไป: ทำแบบทดสอบ 4 ชุด เพื่อประเมินศักยภาพ</p></div></div>',
  '                        </div>',
  '                        <button onclick="startTest()" class="w-full bg-purple-600 text-white py-3 rounded-lg hover:bg-purple-700 transition font-semibold"><i class="fas fa-tasks mr-2"></i>เริ่มทำแบบทดสอบ</button>',
  '                    ` : `',
  '                        <div class="flex space-x-4">',
  '                            <button onclick="backToPositions()" class="flex-1 bg-gray-300 text-gray-700 py-3 rounded-lg hover:bg-gray-400 transition">← เลือกตำแหน่งอื่น</button>',
  '                            <button onclick="switchView(\'hr\')" class="flex-1 bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 transition">👔 ดูมุมมอง HR</button>',
  '                        </div>',
  '                    `}',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        // ===== STEP 4: TEST =====',
  '        function startTest() {',
  '            currentStep = \'test\';',
  '            currentTest = \'attitude\';',
  '            currentQuestion = 0;',
  '            testAnswers = { attitude: {}, skill: {}, cc: {}, e3p: {} };',
  '            renderTestView();',
  '        }',
  '',
  '        function renderTestView() {',
  '            const content = document.getElementById(\'content-area\');',
  '            const test = TESTS[currentTest];',
  '            const question = test.questions[currentQuestion];',
  '            const totalQuestions = Object.values(TESTS).reduce((sum, t) => sum + t.questions.length, 0);',
  '            const answeredQuestions = Object.values(testAnswers).reduce((sum, t) => sum + Object.keys(t).length, 0);',
  '            const progress = (answeredQuestions / totalQuestions) * 100;',
  '            ',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <div class="flex justify-between items-center mb-6">',
  '                        <h2 class="text-2xl font-bold text-gray-800"><i class="fas fa-tasks text-purple-600 mr-2"></i>แบบทดสอบ</h2>',
  '                        <div class="text-sm text-gray-600">ความคืบหน้า: ${Math.round(progress)}%</div>',
  '                    </div>',
  '                    <div class="w-full bg-gray-200 rounded-full h-3 mb-6"><div class="bg-purple-600 h-3 rounded-full" style="width: ${progress}%"></div></div>',
  '                    ',
  '                    <div class="flex space-x-2 mb-6">',
  '                        ${Object.keys(TESTS).map(key => `',
  '                            <button onclick="switchTest(\'${key}\')" class="flex-1 py-2 rounded-lg text-sm font-semibold ${key === currentTest ? \'bg-purple-600 text-white\' : \'bg-gray-200 text-gray-700\'}">',
  '                                <i class="fas ${TESTS[key].icon} mr-1"></i>${TESTS[key].title}',
  '                            </button>',
  '                        `).join(\'\')}',
  '                    </div>',
  '',
  '                    <div class="mb-6">',
  '                        <div class="flex justify-between items-center mb-4">',
  '                            <h3 class="text-lg font-semibold text-gray-800">${test.title} - ข้อ ${currentQuestion + 1}/${test.questions.length}</h3>',
  '                            <span class="text-sm text-gray-500">เวลา: ${test.time} นาที</span>',
  '                        </div>',
  '                        <div class="bg-purple-50 border-l-4 border-purple-600 p-4 rounded-lg mb-6">',
  '                            <p class="text-gray-800 font-medium">${question.text}</p>',
  '                        </div>',
  '                        <div class="space-y-3">',
  '                            ${question.options.map((opt, idx) => `',
  '                                <div class="option-card border-2 border-gray-200 rounded-lg p-4 ${testAnswers[currentTest][question.id] === idx + 1 ? \'selected\' : \'\'}" onclick="selectAnswer(\'${currentTest}\', \'${question.id}\', ${idx + 1})">',
  '                                    <div class="flex items-center">',
  '                                        <div class="w-8 h-8 rounded-full border-2 ${testAnswers[currentTest][question.id] === idx + 1 ? \'bg-white text-purple-600\' : \'border-gray-300\'} flex items-center justify-center font-semibold mr-3">${String.fromCharCode(65 + idx)}</div>',
  '                                        <span class="flex-1">${opt}</span>',
  '                                    </div>',
  '                                </div>',
  '                            `).join(\'\')}',
  '                        </div>',
  '                    </div>',
  '',
  '                    <div class="flex justify-between">',
  '                        <button onclick="prevQuestion()" ${currentTest === \'attitude\' && currentQuestion === 0 ? \'disabled\' : \'\'} class="bg-gray-300 text-gray-700 px-6 py-3 rounded-lg hover:bg-gray-400 transition disabled:opacity-50"><i class="fas fa-arrow-left mr-2"></i>ก่อนหน้า</button>',
  '                        ${currentTest === \'e3p\' && currentQuestion === test.questions.length - 1 ? `<button onclick="submitTest()" class="bg-green-600 text-white px-8 py-3 rounded-lg hover:bg-green-700 transition font-semibold"><i class="fas fa-check-circle mr-2"></i>ส่งคำตอบ</button>` : `<button onclick="nextQuestion()" class="bg-purple-600 text-white px-6 py-3 rounded-lg hover:bg-purple-700 transition">ถัดไป<i class="fas fa-arrow-right ml-2"></i></button>`}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function switchTest(test) { currentTest = test; currentQuestion = 0; renderTestView(); }',
  '        function selectAnswer(test, questionId, value) { testAnswers[test][questionId] = value; renderTestView(); }',
  '        function nextQuestion() { const test = TESTS[currentTest]; if (currentQuestion < test.questions.length - 1) currentQuestion++; else { const tests = Object.keys(TESTS); const idx = tests.indexOf(currentTest); if (idx < tests.length - 1) { currentTest = tests[idx + 1]; currentQuestion = 0; } } renderTestView(); }',
  '        function prevQuestion() { if (currentQuestion > 0) currentQuestion--; else { const tests = Object.keys(TESTS); const idx = tests.indexOf(currentTest); if (idx > 0) { currentTest = tests[idx - 1]; currentQuestion = TESTS[currentTest].questions.length - 1; } } renderTestView(); }',
  '',
  '        function submitTest() {',
  '            const totalQuestions = Object.values(TESTS).reduce((sum, t) => sum + t.questions.length, 0);',
  '            const answeredQuestions = Object.values(testAnswers).reduce((sum, t) => sum + Object.keys(t).length, 0);',
  '            if (answeredQuestions < totalQuestions) { if (!confirm(`คุณยังไม่ได้ตอบคำถาม ${totalQuestions - answeredQuestions} ข้อ ต้องการส่งคำตอบหรือไม่?`)) return; }',
  '            else { if (!confirm(\'ต้องการส่งคำตอบหรือไม่?\')) return; }',
  '            ',
  '            const scores = calculateTestScores();',
  '            ',
  '            // บันทึกคะแนนลง localStorage',
  '            const applications = JSON.parse(localStorage.getItem(\'pkg_applications\') || \'[]\');',
  '            const app = applications.find(a => a.id === currentApplicantId);',
  '            if (app) {',
  '                app.testScores = scores;',
  '                app.status = \'test_done\';',
  '                app.history.push({ action: \'ทำแบบทดสอบ\', timestamp: new Date().toISOString(), note: `คะแนนรวม: ${scores.overall}` });',
  '                localStorage.setItem(\'pkg_applications\', JSON.stringify(applications));',
  '            }',
  '            ',
  '            currentStep = \'testResult\';',
  '            renderTestResult(scores);',
  '        }',
  '',
  '        function calculateTestScores() {',
  '            const scores = {};',
  '            Object.keys(TESTS).forEach(key => {',
  '                const total = Object.values(testAnswers[key]).reduce((sum, v) => sum + v, 0);',
  '                const max = TESTS[key].questions.length * 5;',
  '                scores[key] = Math.round((total / max) * 100);',
  '            });',
  '            scores.overall = Math.round((scores.attitude + scores.skill + scores.cc + scores.e3p) / 4);',
  '            return scores;',
  '        }',
  '',
  '        function renderTestResult(scores) {',
  '            const content = document.getElementById(\'content-area\');',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <div class="text-center py-12">',
  '                        <div class="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6"><i class="fas fa-check-circle text-green-600 text-4xl"></i></div>',
  '                        <h2 class="text-2xl font-bold text-gray-800 mb-4">ส่งแบบทดสอบสำเร็จ!</h2>',
  '                        <p class="text-gray-600 mb-8">ขอบคุณที่ทำแบบทดสอบครบทั้ง 4 ชุด</p>',
  '                        ',
  '                        <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">',
  '                            <div class="bg-purple-50 p-4 rounded-lg"><i class="fas fa-smile text-2xl text-purple-600 mb-2"></i><p class="text-sm text-gray-600">ทัศนคติ</p><p class="text-2xl font-bold text-purple-600">${scores.attitude}</p></div>',
  '                            <div class="bg-blue-50 p-4 rounded-lg"><i class="fas fa-tools text-2xl text-blue-600 mb-2"></i><p class="text-sm text-gray-600">ทักษะ</p><p class="text-2xl font-bold text-blue-600">${scores.skill}</p></div>',
  '                            <div class="bg-yellow-50 p-4 rounded-lg"><i class="fas fa-star text-2xl text-yellow-600 mb-2"></i><p class="text-sm text-gray-600">CC 7 ด้าน</p><p class="text-2xl font-bold text-yellow-600">${scores.cc}</p></div>',
  '                            <div class="bg-green-50 p-4 rounded-lg"><i class="fas fa-chart-line text-2xl text-green-600 mb-2"></i><p class="text-sm text-gray-600">3E3P</p><p class="text-2xl font-bold text-green-600">${scores.e3p}</p></div>',
  '                        </div>',
  '                        ',
  '                        <div class="bg-gradient-to-r from-purple-600 to-indigo-600 text-white p-6 rounded-lg mb-8">',
  '                            <p class="text-lg font-semibold mb-2">คะแนนรวม</p>',
  '                            <p class="text-5xl font-bold">${scores.overall}</p>',
  '                            <p class="text-sm opacity-90 mt-2">จาก 100 คะแนน</p>',
  '                        </div>',
  '                        ',
  '                        <div class="bg-blue-50 border-l-4 border-blue-400 p-4 text-left mb-8">',
  '                            <div class="flex items-start"><i class="fas fa-info-circle text-blue-600 mr-2 mt-1"></i><div class="text-sm text-blue-700"><p class="font-semibold mb-2">ขั้นตอนถัดไป:</p><ol class="list-decimal list-inside space-y-1"><li>HR จะประเมินผลแบบทดสอบของคุณ</li><li>หากผ่านเกณฑ์ คุณจะได้รับการนัดสัมภาษณ์</li><li>ติดตามสถานะได้ที่หน้า Dashboard</li></ol></div></div>',
  '                        </div>',
  '                        ',
  '                        <button onclick="renderApplicantDashboard()" class="bg-purple-600 text-white px-8 py-3 rounded-lg hover:bg-purple-700 transition font-semibold"><i class="fas fa-tachometer-alt mr-2"></i>ดูสถานะใบสมัคร</button>',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        // ===== APPLICANT DASHBOARD =====',
  '        function renderApplicantDashboard() {',
  '            const content = document.getElementById(\'content-area\');',
  '            const applications = getAllApplicants();',
  '            const myApps = applications.filter(a => a.id === currentApplicantId);',
  '            ',
  '            if (myApps.length === 0) {',
  '                content.innerHTML = `<div class="bg-white rounded-xl shadow-lg p-6 text-center"><p class="text-gray-500">ยังไม่มีใบสมัคร</p><button onclick="renderPositionsList()" class="mt-4 bg-purple-600 text-white px-6 py-2 rounded-lg hover:bg-purple-700">สมัครงาน</button></div>`;',
  '                return;',
  '            }',
  '            ',
  '            const app = myApps[0];',
  '            const statusSteps = [',
  '                { key: \'new\', label: \'ส่งใบสมัคร\', icon: \'📝\' },',
  '                { key: \'test_done\', label: \'ทำแบบทดสอบ\', icon: \'📋\' },',
  '                { key: \'screened\', label: \'HR คัดกรอง\', icon: \'🎯\' },',
  '                { key: \'interview_scheduled\', label: \'นัดสัมภาษณ์\', icon: \'📅\' },',
  '                { key: \'interviewed\', label: \'สัมภาษณ์แล้ว\', icon: \'💬\' },',
  '                { key: \'assessed\', label: \'ประเมิน CC (P2)\', icon: \'🧭\' },',
  '                { key: \'matched\', label: \'จับคู่คนกับงาน (P3)\', icon: \'🤝\' },',
  '                { key: \'hired\', label: \'ผ่านคัดเลือก\', icon: \'✅\' },',
  '                { key: \'onboarded\', label: \'เริ่มงาน\', icon: \'🎉\' }',
  '            ];',
  '            ',
  '            const currentStepIndex = statusSteps.findIndex(s => s.key === app.status);',
  '            ',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <h2 class="text-2xl font-bold text-gray-800 mb-6"><i class="fas fa-tachometer-alt text-purple-600 mr-2"></i>สถานะใบสมัครของฉัน</h2>',
  '                    ',
  '                    <div class="bg-gradient-to-r from-purple-600 to-indigo-600 text-white p-6 rounded-xl mb-6">',
  '                        <div class="flex justify-between items-start">',
  '                            <div>',
  '                                <p class="text-sm opacity-90 mb-1">รหัสใบสมัคร</p>',
  '                                <p class="text-2xl font-bold mb-2">${app.id}</p>',
  '                                <p class="text-lg">${app.position} - ${app.department}</p>',
  '                                <p class="text-sm opacity-90">${app.branch}</p>',
  '                            </div>',
  '                            <div class="text-right">',
  '                                <p class="text-sm opacity-90">สมัครเมื่อ</p>',
  '                                <p class="text-sm">${new Date(app.appliedAt).toLocaleDateString(\'th-TH\')}</p>',
  '                            </div>',
  '                        </div>',
  '                    </div>',
  '                    ',
  '                    <div class="mb-6">',
  '                        <h3 class="text-lg font-semibold text-gray-700 mb-4">สถานะการดำเนินการ</h3>',
  '                        <div class="status-timeline">',
  '                            ${statusSteps.map((step, idx) => {',
  '                                let statusClass = \'pending\';',
  '                                if (idx < currentStepIndex) statusClass = \'completed\';',
  '                                else if (idx === currentStepIndex) statusClass = \'current\';',
  '                                ',
  '                                return `',
  '                                    <div class="status-item ${statusClass}">',
  '                                        <div class="flex items-start">',
  '                                            <div class="flex-1">',
  '                                                <p class="font-semibold text-gray-800">${step.icon} ${step.label}</p>',
  '                                                ${idx <= currentStepIndex ? `<p class="text-sm text-gray-600">${getStepDescription(step.key, app)}</p>` : \'\'}',
  '                                            </div>',
  '                                            ${idx < currentStepIndex ? \'<i class="fas fa-check-circle text-green-600"></i>\' : \'\'}',
  '                                            ${idx === currentStepIndex ? \'<i class="fas fa-spinner fa-spin text-blue-600"></i>\' : \'\'}',
  '                                        </div>',
  '                                    </div>',
  '                                `;',
  '                            }).join(\'\')}',
  '                        </div>',
  '                    </div>',
  '                    ',
  '                    ${app.aiScore ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">คะแนน AI</h3>',
  '                            <div class="bg-gradient-to-r from-purple-500 to-indigo-500 text-white p-4 rounded-lg">',
  '                                <div class="flex justify-between items-center">',
  '                                    <div>',
  '                                        <p class="text-sm opacity-90">คะแนนความเหมาะสม</p>',
  '                                        <p class="text-3xl font-bold">${app.aiScore}/100</p>',
  '                                    </div>',
  '                                    <i class="fas fa-robot text-4xl opacity-50"></i>',
  '                                </div>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    ${app.testScores ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">คะแนนแบบทดสอบ</h3>',
  '                            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">',
  '                                <div class="bg-purple-50 p-4 rounded-lg text-center"><p class="text-sm text-gray-600">ทัศนคติ</p><p class="text-2xl font-bold text-purple-600">${app.testScores.attitude}</p></div>',
  '                                <div class="bg-blue-50 p-4 rounded-lg text-center"><p class="text-sm text-gray-600">ทักษะ</p><p class="text-2xl font-bold text-blue-600">${app.testScores.skill}</p></div>',
  '                                <div class="bg-yellow-50 p-4 rounded-lg text-center"><p class="text-sm text-gray-600">CC 7 ด้าน</p><p class="text-2xl font-bold text-yellow-600">${app.testScores.cc}</p></div>',
  '                                <div class="bg-green-50 p-4 rounded-lg text-center"><p class="text-sm text-gray-600">3E3P</p><p class="text-2xl font-bold text-green-600">${app.testScores.e3p}</p></div>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    ${app.interviewDate ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">นัดสัมภาษณ์</h3>',
  '                            <div class="bg-orange-50 border-l-4 border-orange-400 p-4 rounded-lg">',
  '                                <p class="font-semibold text-orange-800">📅 วันที่: ${app.interviewDate}</p>'
];
