var PP7_PART_9 = [
  '/* ═══════════════════════════════════════════',
  '           PP7 Advanced Features — Individual Tracking,',
  '           Time-Based Filtering, Company Filter, P1-P7 Journey',
  '           Pure CSS — no Chart.js (GAS sandbox safe)',
  '           No showTab override — uses setInterval polling',
  '           ═══════════════════════════════════════════ */',
  '',
  '        /* ── Sample Person Data (20 people with full P1-P7 journey) ── */',
  '        var PP7_PEOPLE = [',
  '            {id:"PP7-001",name:"สมชาย ใจดี",company:"PMSG",dept:"Sales",position:"Sales Executive",appliedDate:"2025-01-15",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"in_progress",p6:"completed",p7:"in_progress",ccScore:3.6,matchScore:82,kpiScore:3.8,aiScore:78,engagement:76,salary:25000,bonus:30000,training:28,devProgress:65},',
  '            {id:"PP7-002",name:"สมหญิง รักงาน",company:"AAMG",dept:"Operations",position:"Ops Manager",appliedDate:"2025-02-20",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"completed",p6:"completed",p7:"completed",ccScore:3.9,matchScore:88,kpiScore:4.2,aiScore:85,engagement:82,salary:45000,bonus:55000,training:40,devProgress:90},',
  '            {id:"PP7-003",name:"วิชัย เก่งจริง",company:"CPDG",dept:"Tech/IT",position:"Senior Developer",appliedDate:"2025-03-10",p1:"completed",p2:"completed",p3:"completed",p4:"in_progress",p5:"in_progress",p6:"not_started",p7:"not_started",ccScore:3.4,matchScore:75,kpiScore:3.5,aiScore:72,engagement:68,salary:38000,bonus:20000,training:22,devProgress:45},',
  '            {id:"PP7-004",name:"มาลี ขยันสู้",company:"PMSG",dept:"Finance",position:"Accountant",appliedDate:"2025-01-28",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"completed",p6:"completed",p7:"in_progress",ccScore:3.7,matchScore:80,kpiScore:3.9,aiScore:76,engagement:74,salary:32000,bonus:35000,training:32,devProgress:78},',
  '            {id:"PP7-005",name:"ประวิทย์ มุ่งมั่น",company:"AAMG",dept:"HR",position:"HR Specialist",appliedDate:"2025-04-05",p1:"completed",p2:"completed",p3:"in_progress",p4:"not_started",p5:"not_started",p6:"not_started",p7:"not_started",ccScore:3.5,matchScore:70,kpiScore:0,aiScore:68,engagement:0,salary:0,bonus:0,training:12,devProgress:20},',
  '            {id:"PP7-006",name:"จันทรา พาที",company:"CPDG",dept:"R&D",position:"Research Analyst",appliedDate:"2025-02-14",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"completed",p6:"in_progress",p7:"not_started",ccScore:3.8,matchScore:85,kpiScore:4.0,aiScore:80,engagement:71,salary:42000,bonus:40000,training:36,devProgress:82},',
  '            {id:"PP7-007",name:"เอกชน ตั้งใจ",company:"PMSG",dept:"Sales",position:"Sales Manager",appliedDate:"2025-03-22",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"in_progress",p6:"completed",p7:"completed",ccScore:4.0,matchScore:90,kpiScore:4.3,aiScore:88,engagement:85,salary:55000,bonus:70000,training:38,devProgress:88},',
  '            {id:"PP7-008",name:"รัตนา บุญมี",company:"AAMG",dept:"Operations",position:"Ops Supervisor",appliedDate:"2025-04-18",p1:"completed",p2:"completed",p3:"completed",p4:"in_progress",p5:"not_started",p6:"not_started",p7:"not_started",ccScore:3.3,matchScore:72,kpiScore:3.2,aiScore:70,engagement:65,salary:30000,bonus:15000,training:18,devProgress:30},',
  '            {id:"PP7-009",name:"กิตติ สุขสันต์",company:"CPDG",dept:"Tech/IT",position:"IT Support",appliedDate:"2025-01-08",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"completed",p6:"completed",p7:"completed",ccScore:3.6,matchScore:79,kpiScore:3.7,aiScore:75,engagement:79,salary:28000,bonus:32000,training:30,devProgress:75},',
  '            {id:"PP7-010",name:"สุนันทา ใสสะอาด",company:"PMSG",dept:"Finance",position:"Financial Analyst",appliedDate:"2025-05-02",p1:"completed",p2:"in_progress",p3:"not_started",p4:"not_started",p5:"not_started",p6:"not_started",p7:"not_started",ccScore:3.2,matchScore:68,kpiScore:0,aiScore:65,engagement:0,salary:0,bonus:0,training:5,devProgress:10},',
  '            {id:"PP7-011",name:"บุญรักษ์ ทศพร",company:"AAMG",dept:"Sales",position:"Account Executive",appliedDate:"2025-02-25",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"in_progress",p6:"in_progress",p7:"not_started",ccScore:3.5,matchScore:76,kpiScore:3.6,aiScore:73,engagement:70,salary:35000,bonus:28000,training:25,devProgress:55},',
  '            {id:"PP7-012",name:"อัจฉรา ปัญญาดี",company:"CPDG",dept:"R&D",position:"Data Scientist",appliedDate:"2025-03-15",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"completed",p6:"completed",p7:"in_progress",ccScore:4.1,matchScore:92,kpiScore:4.4,aiScore:90,engagement:86,salary:50000,bonus:60000,training:42,devProgress:92},',
  '            {id:"PP7-013",name:"ธีระ กล้าหาญ",company:"PMSG",dept:"Operations",position:"Warehouse Manager",appliedDate:"2025-04-10",p1:"completed",p2:"completed",p3:"completed",p4:"in_progress",p5:"in_progress",p6:"not_started",p7:"not_started",ccScore:3.4,matchScore:71,kpiScore:3.3,aiScore:69,engagement:66,salary:33000,bonus:18000,training:20,devProgress:35},',
  '            {id:"PP7-014",name:"พิมพ์ใจ งามพริ้ง",company:"AAMG",dept:"HR",position:"Recruiter",appliedDate:"2025-01-20",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"completed",p6:"completed",p7:"completed",ccScore:3.8,matchScore:84,kpiScore:4.1,aiScore:82,engagement:80,salary:30000,bonus:38000,training:34,devProgress:80},',
  '            {id:"PP7-015",name:"นเรศวร เชิดชู",company:"CPDG",dept:"Sales",position:"Regional Sales Lead",appliedDate:"2025-05-12",p1:"completed",p2:"completed",p3:"in_progress",p4:"not_started",p5:"not_started",p6:"not_started",p7:"not_started",ccScore:3.6,matchScore:78,kpiScore:0,aiScore:74,engagement:0,salary:0,bonus:0,training:8,devProgress:15},',
  '            {id:"PP7-016",name:"ปิยะ วัฒนชัย",company:"PMSG",dept:"Tech/IT",position:"System Admin",appliedDate:"2025-02-08",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"in_progress",p6:"completed",p7:"in_progress",ccScore:3.5,matchScore:77,kpiScore:3.6,aiScore:74,engagement:73,salary:36000,bonus:30000,training:26,devProgress:60},',
  '            {id:"PP7-017",name:"กานต์พร ส่องแสง",company:"AAMG",dept:"Finance",position:"Treasury Analyst",appliedDate:"2025-03-28",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"completed",p6:"in_progress",p7:"not_started",ccScore:3.7,matchScore:81,kpiScore:3.8,aiScore:77,engagement:72,salary:40000,bonus:35000,training:30,devProgress:70},',
  '            {id:"PP7-018",name:"ชาญชัย แข็งแรง",company:"CPDG",dept:"Operations",position:"Logistics Officer",appliedDate:"2025-04-22",p1:"completed",p2:"in_progress",p3:"not_started",p4:"not_started",p5:"not_started",p6:"not_started",p7:"not_started",ccScore:3.1,matchScore:65,kpiScore:0,aiScore:62,engagement:0,salary:0,bonus:0,training:3,devProgress:5},',
  '            {id:"PP7-019",name:"ดวงใจ เมตตา",company:"PMSG",dept:"R&D",position:"Product Researcher",appliedDate:"2025-01-30",p1:"completed",p2:"completed",p3:"completed",p4:"completed",p5:"completed",p6:"completed",p7:"completed",ccScore:3.9,matchScore:86,kpiScore:4.0,aiScore:83,engagement:84,salary:43000,bonus:48000,training:38,devProgress:85},',
  '            {id:"PP7-020",name:"อนุชา ก้าวไกล",company:"AAMG",dept:"Tech/IT",position:"QA Engineer",appliedDate:"2025-05-05",p1:"completed",p2:"completed",p3:"completed",p4:"in_progress",p5:"not_started",p6:"not_started",p7:"not_started",ccScore:3.4,matchScore:73,kpiScore:3.4,aiScore:71,engagement:67,salary:32000,bonus:12000,training:15,devProgress:25}',
  '        ];',
  '',
  '        var PP7_COMPANIES = ["PMSG","AAMG","CPDG"];',
  '        var PP7_DEPTS = ["Sales","Operations","Tech/IT","Finance","HR","R&D"];',
  '        var PP7_MONTHS = ["01","02","03","04","05","06","07","08","09","10","11","12"];',
  '        var PP7_MONTH_NAMES = ["ม.ค.","ก.พ.","มี.ค.","เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย.","ต.ค.","พ.ย.","ธ.ค."];',
  '        var PP7_STEPS = ["p1","p2","p3","p4","p5","p6","p7"];',
  '        var PP7_STEP_NAMES = ["P1 แสวงหา","P2 หยั่งประเมิน","P3 จับคู่","P4 ประเมินผล","P5 พัฒนา","P6 ค่าตอบแทน","P7 คุณภาพชีวิต"];',
  '        var PP7_STEP_ICONS = ["🔎","🧭","🤝","📈","🎓","💰","🌿"];',
  '',
  '        /* ── Filter State ── */',
  '        var pp7Filter = {person:"all", month:"all", year:"all", company:"all", view:"dashboard"};',
  '',
  '        /* ── Inject CSS once ── */',
  '        var _pp7CSSInjected = false;',
  '        function pp7InjectCSS(){',
  '            if(_pp7CSSInjected) return;',
  '            _pp7CSSInjected = true;',
  '            var style = document.createElement("style");',
  '            style.textContent = `',
  '        .pp7-filter-bar{background:#fff;border-radius:10px;padding:12px 16px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,.08);border:1px solid #e2e8f0;display:flex;flex-wrap:wrap;gap:10px;align-items:center}',
  '        .pp7-filter-bar .lbl{font-size:.75rem;font-weight:700;color:#475569;margin-right:4px}',
  '        .pp7-filter-bar select{padding:6px 10px;border:1px solid #cbd5e1;border-radius:6px;font-size:.8rem;font-family:Prompt,sans-serif;background:#f8fafc;color:#1e293b;cursor:pointer}',
  '        .pp7-filter-bar select:focus{outline:none;border-color:#3b82f6;box-shadow:0 0 0 2px rgba(59,130,246,.15)}',
  '        .pp7-filter-bar .pp7-btn{padding:6px 14px;border:none;border-radius:6px;font-size:.78rem;font-weight:600;cursor:pointer;font-family:Prompt,sans-serif;transition:all .15s}',
  '        .pp7-btn-dashboard{background:#3b82f6;color:#fff}.pp7-btn-dashboard:hover{background:#2563eb}',
  '        .pp7-btn-individual{background:#8b5cf6;color:#fff}.pp7-btn-individual:hover{background:#7c3aed}',
  '        .pp7-btn-active{background:#1e293b!important;color:#fff!important}',
  '        .pp7-filter-info{font-size:.72rem;color:#64748b;margin-left:auto}',
  '        .pp7-journey{background:#fff;border-radius:12px;padding:24px;box-shadow:0 1px 3px rgba(0,0,0,.08);border:1px solid #e2e8f0;margin-bottom:24px}',
  '        .pp7-journey-header{display:flex;align-items:center;gap:12px;margin-bottom:20px;padding-bottom:14px;border-bottom:2px solid #e2e8f0}',
  '        .pp7-journey-avatar{width:56px;height:56px;border-radius:50%;background:linear-gradient(135deg,#667eea,#764ba2);display:flex;align-items:center;justify-content:center;color:#fff;font-size:1.4rem;font-weight:700;flex-shrink:0}',
  '        .pp7-journey-name{font-size:1.2rem;font-weight:700;color:#1e293b}',
  '        .pp7-journey-meta{font-size:.8rem;color:#64748b;margin-top:2px}',
  '        .pp7-journey-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:10px;margin-bottom:20px}',
  '        .pp7-journey-stat{background:#f8fafc;border-radius:8px;padding:10px 8px;text-align:center;border:1px solid #e2e8f0}',
  '        .pp7-journey-stat .js-lbl{font-size:.65rem;color:#64748b;font-weight:600}',
  '        .pp7-journey-stat .js-val{font-size:1.1rem;font-weight:800;color:#1e293b}',
  '        .pp7-timeline{position:relative;padding-left:2.5rem}',
  '        .pp7-timeline::before{content:"";position:absolute;left:1rem;top:0;bottom:0;width:3px;background:#e2e8f0;border-radius:2px}',
  '        .pp7-tl-item{position:relative;padding-bottom:1.5rem}',
  '        .pp7-tl-item::before{content:"";position:absolute;left:-1.6rem;top:.2rem;width:1.2rem;height:1.2rem;border-radius:50%;border:3px solid #fff;z-index:1}',
  '        .pp7-tl-item.completed::before{background:#10b981}',
  '        .pp7-tl-item.in_progress::before{background:#3b82f6;animation:pp7pulse 2s infinite}',
  '        .pp7-tl-item.not_started::before{background:#cbd5e1}',
  '        @keyframes pp7pulse{0%,100%{box-shadow:0 0 0 0 rgba(59,130,246,.7)}50%{box-shadow:0 0 0 .5rem rgba(59,130,246,0)}}',
  '        .pp7-tl-card{background:#f8fafc;border-radius:8px;padding:12px 14px;border:1px solid #e2e8f0}',
  '        .pp7-tl-card.completed{border-left:4px solid #10b981}',
  '        .pp7-tl-card.in_progress{border-left:4px solid #3b82f6}',
  '        .pp7-tl-card.not_started{border-left:4px solid #cbd5e1;opacity:.6}',
  '        .pp7-tl-title{font-size:.9rem;font-weight:700;color:#1e293b;display:flex;align-items:center;gap:6px}',
  '        .pp7-tl-status{font-size:.68rem;font-weight:600;padding:2px 8px;border-radius:6px;display:inline-block}',
  '        .pp7-tl-status.completed{background:#d1fae5;color:#065f46}',
  '        .pp7-tl-status.in_progress{background:#dbeafe;color:#1e40af}',
  '        .pp7-tl-status.not_started{background:#f1f5f9;color:#64748b}',
  '        .pp7-tl-detail{font-size:.75rem;color:#64748b;margin-top:4px}',
  '        .pp7-person-table{width:100%;border-collapse:collapse;font-size:.78rem}',
  '        .pp7-person-table th{background:#f1f5f9;padding:8px 10px;text-align:left;font-weight:700;color:#475569;border-bottom:2px solid #e2e8f0;position:sticky;top:0}',
  '        .pp7-person-table td{padding:6px 10px;border-bottom:1px solid #f1f5f9;color:#334155}',
  '        .pp7-person-table tr:hover{background:#f8fafc}',
  '        .pp7-person-table .pp7-mini-badge{font-size:.62rem;padding:1px 6px;border-radius:4px;font-weight:600}',
  '        .pp7-badge-completed{background:#d1fae5;color:#065f46}',
  '        .pp7-badge-in_progress{background:#dbeafe;color:#1e40af}',
  '        .pp7-badge-not_started{background:#f1f5f9;color:#94a3b8}',
  '        .pp7-scroll{overflow-x:auto;max-height:400px;overflow-y:auto}',
  '        .pp7-comp-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-top:14px}',
  '        .pp7-comp-card{background:#f8fafc;border-radius:10px;padding:14px;border:1px solid #e2e8f0;text-align:center}',
  '        .pp7-comp-card h4{font-size:.85rem;font-weight:700;color:#1e293b;margin:0 0 8px}',
  '        .pp7-comp-card .pp7-comp-val{font-size:1.3rem;font-weight:800;color:#3b82f6}',
  '        @media(max-width:768px){.pp7-filter-bar{flex-direction:column;align-items:stretch}.pp7-filter-info{margin-left:0}}',
  '            `;',
  '            document.head.appendChild(style);',
  '        }',
  '',
  '        /* ── Get filtered people ── */',
  '        function pp7GetFilteredPeople(){',
  '            return PP7_PEOPLE.filter(function(p){',
  '                if(pp7Filter.company!=="all" && p.company!==pp7Filter.company) return false;',
  '                if(pp7Filter.month!=="all"){',
  '                    var m = p.appliedDate.split("-")[1];',
  '                    if(m!==pp7Filter.month) return false;',
  '                }',
  '                if(pp7Filter.year!=="all"){',
  '                    var y = p.appliedDate.split("-")[0];',
  '                    if(y!==pp7Filter.year) return false;',
  '                }',
  '                if(pp7Filter.person!=="all" && p.id!==pp7Filter.person) return false;',
  '                return true;',
  '            });',
  '        }',
  '',
  '        /* ── Build filter bar HTML (uses string concatenation, no escaping issues) ── */',
  '        function pp7BuildFilterBar(tabName){',
  '            var personOpts = "<option value=\\"all\\">ทั้งหมด (All People)</option>" +',
  '                PP7_PEOPLE.map(function(p){return "<option value=\\""+p.id+"\\">"+p.name+" ("+p.company+")</option>";}).join("");',
  '            var companyOpts = "<option value=\\"all\\">ทุกบริษัท</option>" +',
  '                PP7_COMPANIES.map(function(c){return "<option value=\\""+c+"\\">"+c+"</option>";}).join("");',
  '            var monthOpts = "<option value=\\"all\\">ทุกเดือน</option>" +',
  '                PP7_MONTHS.map(function(m,i){return "<option value=\\""+m+"\\">"+PP7_MONTH_NAMES[i]+"</option>";}).join("");',
  '            var yearOpts = "<option value=\\"all\\">ทุกปี</option><option value=\\"2025\\">2025</option><option value=\\"2024\\">2024</option>";',
  '            var h = "";',
  '            h += "<div class=\\"pp7-filter-bar\\" id=\\"pp7-filter-"+tabName+"\\">";',
  '            h += "<span class=\\"lbl\\">👤 บุคคล:</span><select id=\\"pp7-fp-"+tabName+"\\" onchange=\\"pp7OnFilter("+JSON.stringify(tabName)+")\\">"+personOpts+"</select>";',
  '            h += "<span class=\\"lbl\\">🏢 บริษัท:</span><select id=\\"pp7-fc-"+tabName+"\\" onchange=\\"pp7OnFilter("+JSON.stringify(tabName)+")\\">"+companyOpts+"</select>";',
  '            h += "<span class=\\"lbl\\">📅 เดือน:</span><select id=\\"pp7-fm-"+tabName+"\\" onchange=\\"pp7OnFilter("+JSON.stringify(tabName)+")\\">"+monthOpts+"</select>";',
  '            h += "<span class=\\"lbl\\">📅 ปี:</span><select id=\\"pp7-fy-"+tabName+"\\" onchange=\\"pp7OnFilter("+JSON.stringify(tabName)+")\\">"+yearOpts+"</select>";',
  '            var dashActive = pp7Filter.view==="dashboard" ? " pp7-btn-active" : "";',
  '            var indActive = pp7Filter.view==="individual" ? " pp7-btn-active" : "";',
  '            h += "<button class=\\"pp7-btn pp7-btn-dashboard"+dashActive+"\\" onclick=\\"pp7SetView("+JSON.stringify(tabName)+",\'dashboard\')\\">📊 Dashboard</button>";',
  '            h += "<button class=\\"pp7-btn pp7-btn-individual"+indActive+"\\" onclick=\\"pp7SetView("+JSON.stringify(tabName)+",\'individual\')\\">👤 Individual</button>";',
  '            h += "<span class=\\"pp7-filter-info\\" id=\\"pp7-finfo-"+tabName+"\\"></span>";',
  '            h += "</div>";',
  '            return h;',
  '        }',
  '',
  '        /* ── Handle filter change ── */',
  '        function pp7OnFilter(tabName){',
  '            var fp = document.getElementById("pp7-fp-"+tabName);',
  '            var fc = document.getElementById("pp7-fc-"+tabName);',
  '            var fm = document.getElementById("pp7-fm-"+tabName);',
  '            var fy = document.getElementById("pp7-fy-"+tabName);',
  '            if(fp) pp7Filter.person = fp.value;',
  '            if(fc) pp7Filter.company = fc.value;',
  '            if(fm) pp7Filter.month = fm.value;',
  '            if(fy) pp7Filter.year = fy.value;',
  '            pp7RenderTab(tabName);',
  '        }',
  '',
  '        /* ── Set view mode ── */',
  '        function pp7SetView(tabName,view){',
  '            pp7Filter.view = view;',
  '            var bar = document.getElementById("pp7-filter-"+tabName);',
  '            if(bar){',
  '                var btns = bar.querySelectorAll(".pp7-btn");',
  '                btns.forEach(function(b){b.classList.remove("pp7-btn-active");});',
  '                if(view==="dashboard"){',
  '                    var db = bar.querySelector(".pp7-btn-dashboard");',
  '                    if(db) db.classList.add("pp7-btn-active");',
  '                } else {',
  '                    var ind = bar.querySelector(".pp7-btn-individual");',
  '                    if(ind) ind.classList.add("pp7-btn-active");',
  '                }',
  '            }',
  '            pp7RenderTab(tabName);',
  '        }',
  '',
  '        /* ── Render tab (dashboard or individual) ── */',
  '        function pp7RenderTab(tabName){',
  '            var dashId = {recruit:"p1-dashboard",assess:"p2-dashboard",match:"p3-dashboard",performance:"p4-dashboard",develop:"p5-dashboard",welfare:"p6-dashboard",quality:"p7-dashboard"}[tabName];',
  '            if(!dashId) return;',
  '            var container = document.getElementById(dashId);',
  '            if(!container) return;',
  '            var people = pp7GetFilteredPeople();',
  '            var finfo = document.getElementById("pp7-finfo-"+tabName);',
  '            if(finfo) finfo.textContent = "แสดง " + people.length + " คน";',
  '            if(pp7Filter.view==="individual"){',
  '                container.innerHTML = pp7RenderIndividualView(tabName,people);',
  '                _pp7DashRendered[dashId] = true;',
  '            } else {',
  '                _pp7DashRendered[dashId] = false;',
  '                pp7RenderFilteredDashboard(tabName,people);',
  '            }',
  '        }',
  '',
  '        /* ── Filtered dashboard (rebuilds KPIs based on filter) ── */',
  '        function pp7RenderFilteredDashboard(tabName,people){',
  '            var dashId = {recruit:"p1-dashboard",assess:"p2-dashboard",match:"p3-dashboard",performance:"p4-dashboard",develop:"p5-dashboard",welfare:"p6-dashboard",quality:"p7-dashboard"}[tabName];',
  '            var titles = {recruit:["P1 แสวงหา — Recruitment Dashboard","🔎"],assess:["P2 หยั่งประเมิน — Assessment Dashboard","🧭"],match:["P3 จับคู่คนกับงาน — Matching Dashboard","🤝"],performance:["P4 ประเมินผล — Performance Dashboard","📈"],develop:["P5 พัฒนา — Development Dashboard","🎓"],welfare:["P6 ค่าตอบแทน — Compensation Dashboard","💰"],quality:["P7 คุณภาพชีวิต — Wellbeing Dashboard","🌿"]};',
  '            var t = titles[tabName];',
  '            var n = people.length;',
  '            if(n===0){',
  '                buildDashboard(dashId,t[0],t[1],',
  '                    [{label:"ไม่มีข้อมูล",val:0,target:0,unit:"",pct:0}],[]);',
  '                return;',
  '            }',
  '            var kpis, bars;',
  '            if(tabName==="recruit"){',
  '                var applied = n;',
  '                var hired = people.filter(function(p){return p.p3==="completed";}).length;',
  '                var inPipe = people.filter(function(p){return p.p1==="completed"&&p.p3!=="completed";}).length;',
  '                var offers = people.filter(function(p){return p.p4==="completed"||p.p5==="completed";}).length;',
  '                var avgAi = Math.round(people.reduce(function(s,p){return s+p.aiScore;},0)/n);',
  '                kpis = [',
  '                    {label:"ผู้สมัคร (กรอง)",val:applied,target:20,unit:"คน",pct:applied/20*100},',
  '                    {label:"จ้างงานแล้ว",val:hired,target:applied,unit:"คน",pct:applied>0?hired/applied*100:0},',
  '                    {label:"อยู่ใน Pipeline",val:inPipe,target:applied,unit:"คน",pct:applied>0?inPipe/applied*100:0},',
  '                    {label:"ส่ง Offer",val:offers,target:applied,unit:"คน",pct:applied>0?offers/applied*100:0},',
  '                    {label:"AI Score เฉลี่ย",val:avgAi,target:90,unit:"%",pct:avgAi/90*100}',
  '                ];',
  '                bars = pp7CompanyBars(people);',
  '            } else if(tabName==="assess"){',
  '                var assessed = people.filter(function(p){return p.p2==="completed";}).length;',
  '                var passed = people.filter(function(p){return p.ccScore>=3.0;}).length;',
  '                var avgCC = people.reduce(function(s,p){return s+p.ccScore;},0)/n;',
  '                var avgAi2 = Math.round(people.reduce(function(s,p){return s+p.aiScore;},0)/n);',
  '                kpis = [',
  '                    {label:"ผู้เข้าประเมิน",val:assessed,target:n,unit:"คน",pct:n>0?assessed/n*100:0},',
  '                    {label:"ประเมินเสร็จ",val:assessed,target:n,unit:"คน",pct:n>0?assessed/n*100:0},',
  '                    {label:"CC เฉลี่ย",val:avgCC.toFixed(1),target:4.0,unit:"คะแนน",pct:avgCC/4*100},',
  '                    {label:"ผ่านเกณฑ์ (≥3.0)",val:passed,target:n,unit:"คน",pct:n>0?passed/n*100:0},',
  '                    {label:"AI Score เฉลี่ย",val:avgAi2,target:90,unit:"%",pct:avgAi2/90*100}',
  '                ];',
  '                bars = pp7DeptBars(people);',
  '            } else if(tabName==="match"){',
  '                var matched = people.filter(function(p){return p.p3==="completed";}).length;',
  '                var avgMatch = Math.round(people.reduce(function(s,p){return s+p.matchScore;},0)/n);',
  '                var waiting = people.filter(function(p){return p.p2==="completed"&&p.p3!=="completed";}).length;',
  '                var avgCCm = people.reduce(function(s,p){return s+p.ccScore;},0)/n;',
  '                kpis = [',
  '                    {label:"จับคู่สำเร็จ",val:matched,target:n,unit:"คู่",pct:n>0?matched/n*100:0},',
  '                    {label:"Match Score เฉลี่ย",val:avgMatch,target:85,unit:"%",pct:avgMatch/85*100},',
  '                    {label:"รอจับคู่",val:waiting,target:n,unit:"คน",pct:n>0?waiting/n*100:0},',
  '                    {label:"CC เฉลี่ย",val:avgCCm.toFixed(1),target:4.0,unit:"คะแนน",pct:avgCCm/4*100}',
  '                ];',
  '                bars = pp7DeptBars(people);',
  '            } else if(tabName==="performance"){',
  '                var evaluated = people.filter(function(p){return p.p4==="completed";}).length;',
  '                var passedK = people.filter(function(p){return p.kpiScore>=3.5;}).length;',
  '                var avgKpi = people.reduce(function(s,p){return s+(p.kpiScore||0);},0)/n;',
  '                var avgMatchP = Math.round(people.reduce(function(s,p){return s+p.matchScore;},0)/n);',
  '                kpis = [',
  '                    {label:"รับการประเมิน",val:evaluated,target:n,unit:"คน",pct:n>0?evaluated/n*100:0},',
  '                    {label:"KPI ผ่านเกณฑ์",val:passedK,target:evaluated,unit:"คน",pct:evaluated>0?passedK/evaluated*100:0},',
  '                    {label:"KPI เฉลี่ย",val:avgKpi.toFixed(1),target:4.0,unit:"คะแนน",pct:avgKpi/4*100},',
  '                    {label:"Match Score เฉลี่ย",val:avgMatchP,target:85,unit:"%",pct:avgMatchP/85*100}',
  '                ];',
  '                bars = pp7CompanyBars(people);',
  '            } else if(tabName==="develop"){',
  '                var hasIdp = people.filter(function(p){return p.p5==="completed"||p.p5==="in_progress";}).length;',
  '                var avgTrain = Math.round(people.reduce(function(s,p){return s+p.training;},0)/n);',
  '                var avgDev = Math.round(people.reduce(function(s,p){return s+p.devProgress;},0)/n);',
  '                var avgCCd = people.reduce(function(s,p){return s+p.ccScore;},0)/n;',
  '                kpis = [',
  '                    {label:"มี IDP",val:hasIdp,target:n,unit:"คน",pct:n>0?hasIdp/n*100:0},',
  '                    {label:"ชั่วโมงเรียนรู้เฉลี่ย",val:avgTrain,target:40,unit:"ชม.",pct:avgTrain/40*100},',
  '                    {label:"Dev Progress เฉลี่ย",val:avgDev,target:100,unit:"%",pct:avgDev},',
  '                    {label:"CC เฉลี่ย",val:avgCCd.toFixed(1),target:4.0,unit:"คะแนน",pct:avgCCd/4*100}',
  '                ];',
  '                bars = pp7CompanyBars(people);',
  '            } else if(tabName==="welfare"){',
  '                var hasComp = people.filter(function(p){return p.p6==="completed"||p.p6==="in_progress";}).length;',
  '                var avgSal = Math.round(people.reduce(function(s,p){return s+p.salary;},0)/n);',
  '                var avgBonus = Math.round(people.reduce(function(s,p){return s+p.bonus;},0)/n);',
  '                kpis = [',
  '                    {label:"มีค่าตอบแทน",val:hasComp,target:n,unit:"คน",pct:n>0?hasComp/n*100:0},',
  '                    {label:"เงินเดือนเฉลี่ย",val:avgSal.toLocaleString(),target:50000,unit:"฿",pct:avgSal/50000*100},',
  '                    {label:"โบนัสเฉลี่ย",val:avgBonus.toLocaleString(),target:50000,unit:"฿",pct:avgBonus/50000*100},',
  '                    {label:"Compa Ratio",val:(avgSal/50000).toFixed(2),target:1.0,unit:"อัตรา",pct:avgSal/50000*100}',
  '                ];',
  '                bars = pp7CompanyBars(people);',
  '            } else if(tabName==="quality"){',
  '                var hasEng = people.filter(function(p){return p.engagement>0;}).length;',
  '                var avgEng = Math.round(people.reduce(function(s,p){return s+p.engagement;},0)/n);',
  '                var completed = people.filter(function(p){return p.p7==="completed";}).length;',
  '                var avgCCq = people.reduce(function(s,p){return s+p.ccScore;},0)/n;',
  '                kpis = [',
  '                    {label:"Engagement เฉลี่ย",val:avgEng,target:85,unit:"%",pct:avgEng/85*100},',
  '                    {label:"ครบ P1-P7",val:completed,target:n,unit:"คน",pct:n>0?completed/n*100:0},',
  '                    {label:"มีข้อมูล Wellbeing",val:hasEng,target:n,unit:"คน",pct:n>0?hasEng/n*100:0},',
  '                    {label:"CC เฉลี่ย",val:avgCCq.toFixed(1),target:4.0,unit:"คะแนน",pct:avgCCq/4*100}',
  '                ];',
  '                bars = pp7CompanyBars(people);',
  '            }',
  '            buildDashboard(dashId,t[0],t[1],kpis,bars);',
  '            /* Add company comparison below */',
  '            var c = document.getElementById(dashId);',
  '            if(c) c.innerHTML += pp7CompanyComparison(people);',
  '        }',
  '',
  '        /* ── Company bars helper ── */',
  '        function pp7CompanyBars(people){',
  '            return PP7_COMPANIES.map(function(co){',
  '                var cnt = people.filter(function(p){return p.company===co;}).length;',
  '                return {label:co,val:cnt,target:people.length,unit:"คน"};',
  '            });',
  '        }',
  '        function pp7DeptBars(people){',
  '            return PP7_DEPTS.map(function(d){',
  '                var cnt = people.filter(function(p){return p.dept===d;}).length;',
  '                return {label:d,val:cnt,target:people.length,unit:"คน"};',
  '            });',
  '        }',
  '',
  '        /* ── Company comparison cards ── */',
  '        function pp7CompanyComparison(people){',
  '            if(people.length===0) return "";',
  '            var h = "<div class=\\"pp7-comp-grid\\">";',
  '            PP7_COMPANIES.forEach(function(co){',
  '                var cp = people.filter(function(p){return p.company===co;});',
  '                if(cp.length===0) return;',
  '                var avgCC = (cp.reduce(function(s,p){return s+p.ccScore;},0)/cp.length).toFixed(1);',
  '                var avgMatch = Math.round(cp.reduce(function(s,p){return s+p.matchScore;},0)/cp.length);',
  '                var avgEng = Math.round(cp.reduce(function(s,p){return s+p.engagement;},0)/cp.length);',
  '                var completed = cp.filter(function(p){return p.p7==="completed";}).length;',
  '                h += "<div class=\\"pp7-comp-card\\"><h4>"+co+" ("+cp.length+" คน)</h4>";',
  '                h += "<div class=\\"pp7-comp-val\\">"+avgMatch+"%</div>";',
  '                h += "<div style=\\"font-size:.7rem;color:#64748b;margin-top:4px\\">Match เฉลี่ย</div>";',
  '                h += "<div style=\\"font-size:.72rem;color:#475569;margin-top:6px\\">CC: "+avgCC+" | Eng: "+avgEng+"%</div>";',
  '                h += "<div style=\\"font-size:.72rem;color:#10b981;margin-top:2px\\">ครบ P7: "+completed+" คน</div></div>";',
  '            });',
  '            h += "</div>";',
  '            return h;',
  '        }',
  '',
  '        /* ── Individual Journey View ── */',
  '        function pp7RenderIndividualView(tabName,people){',
  '            if(people.length===0) return "<p style=\\"text-align:center;color:#64748b;padding:20px\\">ไม่มีข้อมูลตามตัวกรองที่เลือก</p>";',
  '            /* If specific person selected, show their journey */',
  '            if(pp7Filter.person!=="all" && people.length===1){',
  '                return pp7RenderPersonJourney(people[0]);',
  '            }',
  '            /* Otherwise show table of all people with journey badges */',
  '            var h = "";',
  '            h += "<div style=\\"margin-bottom:12px;font-size:.85rem;color:#475569\\">เลือกบุคคลจากดรอปดาวน์ด้านบนเพื่อดู P1-P7 Journey หรือคลิกที่แถวในตารางด้านล่าง</div>";',
  '            h += "<div class=\\"pp7-scroll\\"><table class=\\"pp7-person-table\\"><thead><tr><th>รหัส</th><th>ชื่อ</th><th>บริษัท</th><th>แผนก</th><th>ตำแหน่ง</th><th>วันสมัคร</th><th>P1</th><th>P2</th><th>P3</th><th>P4</th><th>P5</th><th>P6</th><th>P7</th><th>CC</th><th>Match</th><th>KPI</th><th>AI</th><th>Eng</th></tr></thead><tbody>";',
  '            people.forEach(function(p){',
  '                h += "<tr style=\\"cursor:pointer\\" onclick=\\"pp7SelectPerson("+JSON.stringify(tabName)+","+JSON.stringify(p.id)+")\\"><td>"+p.id+"</td><td style=\\"font-weight:600\\">"+p.name+"</td><td>"+p.company+"</td><td>"+p.dept+"</td><td style=\\"font-size:.72rem\\">"+p.position+"</td><td style=\\"font-size:.72rem\\">"+pp7FmtDate(p.appliedDate)+"</td>";',
  '                PP7_STEPS.forEach(function(s){',
  '                    h += "<td><span class=\\"pp7-mini-badge pp7-badge-"+p[s]+"\\">"+pp7StatusShort(p[s])+"</span></td>";',
  '                });',
  '                h += "<td>"+p.ccScore.toFixed(1)+"</td><td>"+p.matchScore+"%</td><td>"+(p.kpiScore?p.kpiScore.toFixed(1):"-")+"</td><td>"+p.aiScore+"%</td><td>"+(p.engagement?p.engagement+"%":"-")+"</td></tr>";',
  '            });',
  '            h += "</tbody></table></div>";',
  '            return h;',
  '        }',
  '',
  '        /* ── Single person journey ── */',
  '        function pp7RenderPersonJourney(p){',
  '            var initials = p.name.substring(0,2);',
  '            var completedCount = PP7_STEPS.filter(function(s){return p[s]==="completed";}).length;',
  '            var overallPct = Math.round(completedCount/7*100);',
  '            var colorCode = overallPct>=80 ? "#10b981" : overallPct>=50 ? "#f59e0b" : "#ef4444";',
  '            var h = "";',
  '            h += "<div class=\\"pp7-journey\\">";',
  '            h += "<div class=\\"pp7-journey-header\\"><div class=\\"pp7-journey-avatar\\">"+initials+"</div>";',
  '            h += "<div><div class=\\"pp7-journey-name\\">"+p.name+"</div>";',
  '            h += "<div class=\\"pp7-journey-meta\\">"+p.id+" | "+p.company+" | "+p.dept+" | "+p.position+" | สมัคร: "+pp7FmtDate(p.appliedDate)+"</div></div>";',
  '            h += "<div style=\\"margin-left:auto;text-align:right\\"><div style=\\"font-size:1.5rem;font-weight:800;color:"+colorCode+"\\">"+overallPct+"%</div><div style=\\"font-size:.7rem;color:#64748b\\">เสร็จสิ้น "+completedCount+"/7 ขั้น</div></div></div>";',
  '            /* Stats grid */',
  '            h += "<div class=\\"pp7-journey-stats\\">";',
  '            h += pp7JourneyStat("CC Score",p.ccScore.toFixed(1));',
  '            h += pp7JourneyStat("Match Score",p.matchScore+"%");',
  '            h += pp7JourneyStat("KPI Score",p.kpiScore?p.kpiScore.toFixed(1):"-");',
  '            h += pp7JourneyStat("AI Score",p.aiScore+"%");',
  '            h += pp7JourneyStat("Engagement",p.engagement?p.engagement+"%":"-");',
  '            h += pp7JourneyStat("เงินเดือน",p.salary?p.salary.toLocaleString()+"฿":"-");',
  '            h += pp7JourneyStat("โบนัส",p.bonus?p.bonus.toLocaleString()+"฿":"-");',
  '            h += pp7JourneyStat("ชม.อบรม",p.training+" ชม.");',
  '            h += pp7JourneyStat("Dev Progress",p.devProgress+"%");',
  '            h += "</div>";',
  '            /* Timeline */',
  '            h += "<div class=\\"pp7-timeline\\">";',
  '            PP7_STEPS.forEach(function(s,i){',
  '                var status = p[s];',
  '                var statusLabel = status==="completed" ? "เสร็จสิ้น ✅" : status==="in_progress" ? "กำลังดำเนิน 🔄" : "ยังไม่เริ่ม ⏳";',
  '                var detail = pp7StepDetail(s,p);',
  '                h += "<div class=\\"pp7-tl-item "+status+"\\"><div class=\\"pp7-tl-card "+status+"\\"><div class=\\"pp7-tl-title\\">"+PP7_STEP_ICONS[i]+" "+PP7_STEP_NAMES[i]+" <span class=\\"pp7-tl-status "+status+"\\">"+statusLabel+"</span></div><div class=\\"pp7-tl-detail\\">"+detail+"</div></div></div>";',
  '            });',
  '            h += "</div>";',
  '            h += "</div>";',
  '            return h;',
  '        }',
  '',
  '        function pp7JourneyStat(label,val){',
  '            return "<div class=\\"pp7-journey-stat\\"><div class=\\"js-lbl\\">"+label+"</div><div class=\\"js-val\\">"+val+"</div></div>";',
  '        }',
  '',
  '        function pp7StepDetail(step,p){',
  '            var d = {',
  '                p1:"สมัครงานเมื่อ "+pp7FmtDate(p.appliedDate)+" | AI Score: "+p.aiScore+"%",',
  '                p2:"CC Score: "+p.ccScore.toFixed(1)+" คะแนน (7 ด้าน) | ผ่านเกณฑ์: "+(p.ccScore>=3.0?"✅":"❌"),',
  '                p3:"Match Score: "+p.matchScore+"% | ตำแหน่ง: "+p.position+" | แผนก: "+p.dept,',
  '                p4:"KPI Score: "+(p.kpiScore?p.kpiScore.toFixed(1):"-")+" | ผลประเมิน: "+(p.kpiScore>=3.5?"ผ่าน":"รอพัฒนา"),',
  '                p5:"ชม.อบรม: "+p.training+" ชม. | Dev Progress: "+p.devProgress+"% | IDP: "+(p.p5==="completed"?"ครบ":"กำลังดำเนิน"),',
  '                p6:"เงินเดือน: "+(p.salary?p.salary.toLocaleString()+"฿":"-")+" | โบนัส: "+(p.bonus?p.bonus.toLocaleString()+"฿":"-"),',
  '                p7:"Engagement: "+(p.engagement?p.engagement+"%":"-")+" | คุณภาพชีวิต: "+(p.p7==="completed"?"สมดุล":"รอประเมิน")',
  '            };',
  '            return d[step]||"";',
  '        }',
  '',
  '        function pp7StatusShort(s){',
  '            if(s==="completed") return "✅";',
  '            if(s==="in_progress") return "🔄";',
  '            return "⏳";',
  '        }',
  '',
  '        function pp7FmtDate(d){',
  '            var parts = d.split("-");',
  '            var m = parseInt(parts[1])-1;',
  '            return PP7_MONTH_NAMES[m]+" "+parts[0];',
  '        }',
  '',
  '        /* ── Select person from table ── */',
  '        function pp7SelectPerson(tabName,personId){',
  '            pp7Filter.person = personId;',
  '            var sel = document.getElementById("pp7-fp-"+tabName);',
  '            if(sel) sel.value = personId;',
  '            pp7RenderTab(tabName);',
  '        }',
  '',
  '        /* ── Inject filter bar before dashboard ── */',
  '        var _pp7FilterInjected = {};',
  '        function pp7InjectFilterBar(tabName){',
  '            var dashId = {recruit:"p1-dashboard",assess:"p2-dashboard",match:"p3-dashboard",performance:"p4-dashboard",develop:"p5-dashboard",welfare:"p6-dashboard",quality:"p7-dashboard"}[tabName];',
  '            if(!dashId || _pp7FilterInjected[dashId]) return;',
  '            var dash = document.getElementById(dashId);',
  '            if(!dash) return;',
  '            pp7InjectCSS();',
  '            var bar = document.createElement("div");',
  '            bar.innerHTML = pp7BuildFilterBar(tabName);',
  '            var filterBar = bar.firstChild;',
  '            dash.parentNode.insertBefore(filterBar, dash);',
  '            _pp7FilterInjected[dashId] = true;',
  '        }',
  '',
  '        /* ── Poll for active tab and inject filter bar + render ── */',
  '        /* NO showTab override — uses setInterval polling instead */',
  '        var _pp7CurrentTab = null;',
  '        var _pp7PollCount = 0;',
  '        var _pp7TabIds = ["recruit","assess","match","performance","develop","welfare","quality"];',
  '',
  '        function pp7DetectActiveTab(){',
  '            for(var i=0; i<_pp7TabIds.length; i++){',
  '                var t = _pp7TabIds[i];',
  '                var el = document.getElementById(t+"-tab");',
  '                if(el){',
  '                    var cls = el.className || "";',
  '                    var parent = el.parentElement;',
  '                    var parentCls = parent ? (parent.className||"") : "";',
  '                    /* Check if this tab is active */',
  '                    if(cls.indexOf("active")>=0 || parentCls.indexOf("active")>=0){',
  '                        return t;',
  '                    }',
  '                }',
  '            }',
  '            return null;',
  '        }',
  '',
  '        function pp7PollAndRender(){',
  '            _pp7PollCount++;',
  '            var activeTab = pp7DetectActiveTab();',
  '            if(activeTab && activeTab !== _pp7CurrentTab){',
  '                _pp7CurrentTab = activeTab;',
  '                /* Tab changed — inject filter bar and render */',
  '                setTimeout(function(){',
  '                    pp7InjectFilterBar(activeTab);',
  '                    var dashId = {recruit:"p1-dashboard",assess:"p2-dashboard",match:"p3-dashboard",performance:"p4-dashboard",develop:"p5-dashboard",welfare:"p6-dashboard",quality:"p7-dashboard"}[activeTab];',
  '                    if(dashId) _pp7DashRendered[dashId] = false;',
  '                    pp7RenderTab(activeTab);',
  '                }, 50);',
  '            }',
  '            /* Also check if filter bar is missing (e.g. after first load) */',
  '            if(activeTab){',
  '                var dashId = {recruit:"p1-dashboard",assess:"p2-dashboard",match:"p3-dashboard",performance:"p4-dashboard",develop:"p5-dashboard",welfare:"p6-dashboard",quality:"p7-dashboard"}[activeTab];',
  '                if(dashId && !_pp7FilterInjected[dashId]){',
  '                    pp7InjectFilterBar(activeTab);',
  '                    pp7RenderTab(activeTab);',
  '                }',
  '            }',
  '        }',
  '',
  '        /* Start polling after page load */',
  '        if(document.readyState === "loading"){',
  '            document.addEventListener("DOMContentLoaded", function(){',
  '                pp7InjectCSS();',
  '                setInterval(pp7PollAndRender, 500);',
  '            });',
  '        } else {',
  '            pp7InjectCSS();',
  '            setInterval(pp7PollAndRender, 500);',
  '        }',
  '',
  '        /* ── Monthly trend data (aggregated) ── */',
  '        function pp7MonthlyTrends(){',
  '            var trends = [];',
  '            PP7_MONTHS.forEach(function(m,i){',
  '                var monthPeople = PP7_PEOPLE.filter(function(p){return p.appliedDate.split("-")[1]===m;});',
  '                if(monthPeople.length>0){',
  '                    var avgCC = monthPeople.reduce(function(s,p){return s+p.ccScore;},0)/monthPeople.length;',
  '                    var avgMatch = monthPeople.reduce(function(s,p){return s+p.matchScore;},0)/monthPeople.length;',
  '                    var avgEng = monthPeople.reduce(function(s,p){return s+p.engagement;},0)/monthPeople.length;',
  '                    trends.push({month:PP7_MONTH_NAMES[i],count:monthPeople.length,avgCC:avgCC,avgMatch:avgMatch,avgEng:avgEng});',
  '                }',
  '            });',
  '            return trends;',
  '        }',
  '',
  '        /* ── Yearly summary ── */',
  '        function pp7YearlySummary(year){',
  '            var yp = PP7_PEOPLE.filter(function(p){return p.appliedDate.split("-")[0]===year;});',
  '            if(yp.length===0) return null;',
  '            return {',
  '                year:year,',
  '                total:yp.length,',
  '                completed:yp.filter(function(p){return p.p7==="completed";}).length,',
  '                inProgress:yp.filter(function(p){return PP7_STEPS.some(function(s){return p[s]==="in_progress";});}).length,',
  '                avgCC:(yp.reduce(function(s,p){return s+p.ccScore;},0)/yp.length).toFixed(1),',
  '                avgMatch:Math.round(yp.reduce(function(s,p){return s+p.matchScore;},0)/yp.length),',
  '                avgEng:Math.round(yp.reduce(function(s,p){return s+p.engagement;},0)/yp.length),',
  '                avgSalary:Math.round(yp.reduce(function(s,p){return s+p.salary;},0)/yp.length)',
  '            };',
  '        }',
];