var PP7_PART_5 = [
  '                                <p class="text-sm text-orange-700">⏰ เวลา: ${app.interviewTime}</p>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    ${app.startDate ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">วันเริ่มงาน</h3>',
  '                            <div class="bg-green-50 border-l-4 border-green-400 p-4 rounded-lg">',
  '                                <p class="font-semibold text-green-800">🎉 วันเริ่มงาน: ${app.startDate}</p>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    ${app.rejectReason ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">ผลการคัดเลือก</h3>',
  '                            <div class="bg-red-50 border-l-4 border-red-400 p-4 rounded-lg">',
  '                                <p class="font-semibold text-red-800">❌ ไม่ผ่านการคัดเลือก</p>',
  '                                <p class="text-sm text-red-700">เหตุผล: ${app.rejectReason}</p>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    <div class="flex space-x-4">',
  '                        <button onclick="renderPositionsList()" class="flex-1 bg-gray-300 text-gray-700 py-3 rounded-lg hover:bg-gray-400 transition"><i class="fas fa-briefcase mr-2"></i>สมัครตำแหน่งอื่น</button>',
  '                        <button onclick="switchView(\'hr\')" class="flex-1 bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 transition"><i class="fas fa-user-tie mr-2"></i>ดูมุมมอง HR</button>',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function getStepDescription(stepKey, app) {',
  '            const descriptions = {',
  '                \'new\': `ส่งใบสมัครเมื่อ ${new Date(app.appliedAt).toLocaleDateString(\'th-TH\')}`,',
  '                \'test_done\': `ทำแบบทดสอบเสร็จสิ้น คะแนนรวม: ${app.testScores?.overall || \'-\'}`,',
  '                \'screened\': \'HR คัดกรองผ่าน กำลังรอนัดสัมภาษณ์\',',
  '                \'interview_scheduled\': `นัดสัมภาษณ์วันที่ ${app.interviewDate} เวลา ${app.interviewTime}`,',
  '                \'interviewed\': `สัมภาษณ์เสร็จสิ้น ${app.interviewNotes ? \'- \' + app.interviewNotes : \'\'}`,',
  '                \'assessed\': `ประเมิน CC เสร็จสิ้น คะแนน CC: ${app.ccScore || \'-\'}`,',
  '                \'matched\': `จับคู่กับตำแหน่ง ${app.matchedPosition || \'รอจับคู่\'}`,',
  '                \'hired\': \'ผ่านคัดเลือก ยินดีด้วย!\',',
  '                \'onboarded\': `เริ่มงานวันที่ ${app.startDate}`',
  '            };',
  '            return descriptions[stepKey] || \'\';',
  '        }',
  '',
  '        // ===== RENDER HR VIEW =====',
  '        function renderHRView() {',
  '            const content = document.getElementById(\'content-area\');',
  '            const applications = getAllApplicants(); // ดึงข้อมูลทั้งหมด (ตั้งต้น + ใหม่)',
  '            ',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <h2 class="text-2xl font-bold text-gray-800 mb-6"><i class="fas fa-user-tie text-purple-600 mr-2"></i>มุมมอง HR - Dashboard</h2>',
  '                    ',
  '                    <div class="grid grid-cols-2 md:grid-cols-6 gap-4 mb-6">',
  '                        <div class="bg-blue-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-gray-800">${applications.length}</p><p class="text-xs text-gray-600">ทั้งหมด</p></div>',
  '                        <div class="bg-blue-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-blue-600">${applications.filter(a => a.status === \'new\').length}</p><p class="text-xs text-gray-600">ใหม่</p></div>',
  '                        <div class="bg-purple-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-purple-600">${applications.filter(a => a.status === \'test_done\').length}</p><p class="text-xs text-gray-600">ทำแบบทดสอบแล้ว</p></div>',
  '                        <div class="bg-orange-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-orange-600">${applications.filter(a => a.status === \'screened\').length}</p><p class="text-xs text-gray-600">คัดกรองแล้ว</p></div>',
  '                        <div class="bg-pink-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-pink-600">${applications.filter(a => a.status === \'interview_scheduled\').length}</p><p class="text-xs text-gray-600">นัดสัมภาษณ์</p></div>',
  '                        <div class="bg-green-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-green-600">${applications.filter(a => a.status === \'hired\').length}</p><p class="text-xs text-gray-600">จ้างงาน</p></div>',
  '                    </div>',
  '',
  '                    <h3 class="text-lg font-semibold text-gray-700 mb-4">📋 รายการผู้สมัครทั้งหมด (${applications.length} คน)</h3>',
  '                    <div class="space-y-4">',
  '                        ${applications.map(app => `',
  '                            <div class="border border-gray-200 rounded-lg p-4">',
  '                                <div class="flex justify-between items-start mb-3">',
  '                                    <div>',
  '                                        <h4 class="font-bold text-gray-800">${app.firstName} ${app.lastName}</h4>',
  '                                        <p class="text-sm text-gray-600">${app.position} | ${app.department} | ${app.branch}</p>',
  '                                        ${app.phone ? `<p class="text-xs text-gray-500">📞 ${app.phone} | ✉️ ${app.email || \'-\'}</p>` : \'\'}',
  '                                    </div>',
  '                                    <span class="px-3 py-1 ${getStatusBadgeClass(app.status)} rounded-full text-sm font-semibold">${getStatusText(app.status)}</span>',
  '                                </div>',
  '                                ',
  '                                ${app.aiScore ? `',
  '                                    <div class="mb-3 p-3 bg-purple-50 rounded-lg">',
  '                                        <p class="text-sm font-semibold text-purple-800 mb-1">🤖 คะแนน AI: ${app.aiScore}/100</p>',
  '                                        <div class="w-full bg-gray-200 rounded-full h-2">',
  '                                            <div class="bg-purple-600 h-2 rounded-full" style="width: ${app.aiScore}%"></div>',
  '                                        </div>',
  '                                    </div>',
  '                                ` : \'\'}',
  '                                ',
  '                                ${app.testScores ? `',
  '                                    <div class="mb-3 grid grid-cols-4 gap-2 text-center">',
  '                                        <div class="bg-purple-50 p-2 rounded"><p class="text-xs text-gray-600">ทัศนคติ</p><p class="font-bold text-purple-600">${app.testScores.attitude}</p></div>',
  '                                        <div class="bg-blue-50 p-2 rounded"><p class="text-xs text-gray-600">ทักษะ</p><p class="font-bold text-blue-600">${app.testScores.skill}</p></div>',
  '                                        <div class="bg-yellow-50 p-2 rounded"><p class="text-xs text-gray-600">CC</p><p class="font-bold text-yellow-600">${app.testScores.cc}</p></div>',
  '                                        <div class="bg-green-50 p-2 rounded"><p class="text-xs text-gray-600">3E3P</p><p class="font-bold text-green-600">${app.testScores.e3p}</p></div>',
  '                                    </div>',
  '                                ` : \'\'}',
  '                                ',
  '                                ${app.rejectReason ? `',
  '                                    <div class="mb-3 p-3 bg-red-50 rounded-lg">',
  '                                        <p class="text-sm text-red-800">❌ เหตุผลไม่ผ่าน: ${app.rejectReason}</p>',
  '                                    </div>',
  '                                ` : \'\'}',
  '                                ',
  '                                <div class="flex flex-wrap gap-2">',
  '                                    ${app.status === \'new\' || app.status === \'pending\' ? `<button onclick="screenApplicant(\'${app.id}\')" class="px-3 py-1 bg-purple-600 text-white rounded-lg hover:bg-purple-700 text-sm">✅ คัดกรอง</button>` : \'\'}',
  '                                    ${app.status === \'test_done\' ? `<button onclick="screenApplicant(\'${app.id}\')" class="px-3 py-1 bg-purple-600 text-white rounded-lg hover:bg-purple-700 text-sm">✅ คัดกรอง</button>` : \'\'}',
  '                                    ${app.status === \'screened\' ? `<button onclick="scheduleInterview(\'${app.id}\')" class="px-3 py-1 bg-orange-600 text-white rounded-lg hover:bg-orange-700 text-sm">📅 นัดสัมภาษณ์</button>` : \'\'}',
  '                                    ${app.status === \'interview_scheduled\' ? `<button onclick="markInterviewed(\'${app.id}\')" class="px-3 py-1 bg-pink-600 text-white rounded-lg hover:bg-pink-700 text-sm">💬 สัมภาษณ์แล้ว</button>` : \'\'}',
  '                                    ${app.status === \'interviewed\' ? `<button onclick="finalizeResult(\'${app.id}\')" class="px-3 py-1 bg-green-600 text-white rounded-lg hover:bg-green-700 text-sm">🏆 สรุปผล (ผ่าน)</button>` : \'\'}',
  '                                    ${app.status === \'hired\' ? `<button onclick="onboard(\'${app.id}\')" class="px-3 py-1 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 text-sm">🤝 นัดเริ่มงาน</button>` : \'\'}',
  '                                    <button onclick="viewApplicantDetail(\'${app.id}\')" class="px-3 py-1 bg-gray-600 text-white rounded-lg hover:bg-gray-700 text-sm">👁️ ดูรายละเอียด</button>',
  '                                </div>',
  '                            </div>',
  '                        `).join(\'\') || \'<p class="text-gray-500 text-center py-8">ยังไม่มีผู้สมัคร</p>\'}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function getStatusBadgeClass(status) {',
  '            const classes = {',
  '                \'new\': \'bg-blue-100 text-blue-800\',',
  '                \'test_done\': \'bg-purple-100 text-purple-800\',',
  '                \'screened\': \'bg-orange-100 text-orange-800\',',
  '                \'interview_scheduled\': \'bg-pink-100 text-pink-800\',',
  '                \'interviewed\': \'bg-yellow-100 text-yellow-800\',',
  '                \'hired\': \'bg-green-100 text-green-800\',',
  '                \'onboarded\': \'bg-indigo-100 text-indigo-800\'',
  '            };',
  '            return classes[status] || \'bg-gray-100 text-gray-800\';',
  '        }',
  '',
  '        function getStatusText(status) {',
  '            const texts = {',
  '                \'new\': \'ใหม่\',',
  '                \'test_done\': \'ทำแบบทดสอบแล้ว\',',
  '                \'screened\': \'คัดกรองแล้ว\',',
  '                \'interview_scheduled\': \'นัดสัมภาษณ์\',',
  '                \'interviewed\': \'สัมภาษณ์แล้ว\',',
  '                \'hired\': \'ผ่านคัดเลือก\',',
  '                \'onboarded\': \'เริ่มงาน\'',
  '            };',
  '            return texts[status] || status;',
  '        }',
  '',
  '        function screenApplicant(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                app.status = \'screened\';',
  '                app.history.push({ action: \'คัดกรอง\', timestamp: new Date().toISOString(), note: \'HR คัดกรองผ่าน\' });',
  '                saveApplicantData(app);',
  '                alert(\'✅ คัดกรองผู้สมัครแล้ว!\');',
  '                renderHRView();',
  '            }',
  '        }',
  '',
  '        function scheduleInterview(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                const date = prompt(\'วันที่สัมภาษณ์ (เช่น 25/07/2569):\', \'25/07/2569\');',
  '                const time = prompt(\'เวลาสัมภาษณ์ (เช่น 10:00 น.):\', \'10:00 น.\');',
  '                if (date && time) {',
  '                    app.status = \'interview_scheduled\';',
  '                    app.interviewDate = date;',
  '                    app.interviewTime = time;',
  '                    app.history.push({ action: \'นัดสัมภาษณ์\', timestamp: new Date().toISOString(), note: `วันที่ ${date} เวลา ${time}` });',
  '                    saveApplicantData(app);',
  '                    alert(`✅ นัดสัมภาษณ์แล้ว!\\n\\nวันที่: ${date}\\nเวลา: ${time}`);',
  '                    renderHRView();',
  '                }',
  '            }',
  '        }',
  '',
  '        function markInterviewed(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                // แสดงฟอร์มสัมภาษณ์',
  '                const interviewNotes = prompt(\'บันทึกผลการสัมภาษณ์ (เช่น ผ่าน/ไม่ผ่าน/สำรอง):\', \'ผ่าน - มีศักยภาพดี\');',
  '                if (interviewNotes !== null) {',
  '                    app.status = \'interviewed\';',
  '                    app.interviewNotes = interviewNotes;',
  '                    app.history.push({ action: \'สัมภาษณ์\', timestamp: new Date().toISOString(), note: interviewNotes });',
  '                    saveApplicantData(app);',
  '                    alert(\'✅ บันทึกผลการสัมภาษณ์แล้ว!\\n\\n\' + interviewNotes);',
  '                    renderHRView();',
  '                }',
  '            }',
  '        }',
  '',
  '        function finalizeResult(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                app.status = \'hired\';',
  '                app.history.push({ action: \'สรุปผล\', timestamp: new Date().toISOString(), note: \'ผ่านคัดเลือก\' });',
  '                saveApplicantData(app);',
  '                alert(\'✅ สรุปผล: ผ่าน!\');',
  '                renderHRView();',
  '            }',
  '        }',
  '',
  '        function onboard(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                const startDate = prompt(\'วันเริ่มงาน (เช่น 01/08/2569):\', \'01/08/2569\');',
  '                if (startDate) {',
  '                    app.status = \'onboarded\';',
  '                    app.startDate = startDate;',
  '                    app.history.push({ action: \'นัดเริ่มงาน\', timestamp: new Date().toISOString(), note: `วันเริ่มงาน: ${startDate}` });',
  '                    saveApplicantData(app);',
  '                    alert(`✅ นัดเริ่มงานแล้ว!\\n\\nวันเริ่มงาน: ${startDate}`);',
  '                    renderHRView();',
  '                }',
  '            }',
  '        }',
  '',
  '        function saveApplicantData(app) {',
  '            // ตรวจสอบว่าเป็นข้อมูลตั้งต้นหรือข้อมูลใหม่',
  '            const initial = JSON.parse(localStorage.getItem(\'pkg_initial_applicants\') || \'[]\');',
  '            const newApps = JSON.parse(localStorage.getItem(\'pkg_applications\') || \'[]\');',
  '            ',
  '            const initialIndex = initial.findIndex(a => a.id === app.id);',
  '            if (initialIndex !== -1) {',
  '                // เป็นข้อมูลตั้งต้น',
  '                initial[initialIndex] = app;',
  '                localStorage.setItem(\'pkg_initial_applicants\', JSON.stringify(initial));',
  '            } else {',
  '                // เป็นข้อมูลใหม่',
  '                const newIndex = newApps.findIndex(a => a.id === app.id);',
  '                if (newIndex !== -1) {',
  '                    newApps[newIndex] = app;',
  '                } else {',
  '                    newApps.push(app);',
  '                }',
  '                localStorage.setItem(\'pkg_applications\', JSON.stringify(newApps));',
  '            }',
  '        }',
  '',
  '        function viewApplicantDetail(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                let detail = `📋 รายละเอียดผู้สมัคร\\n\\n`;',
  '                detail += `รหัส: ${app.id}\\n`;',
  '                detail += `ชื่อ: ${app.firstName} ${app.lastName}\\n`;',
  '                if (app.phone) detail += `เบอร์: ${app.phone}\\n`;',
  '                if (app.email) detail += `Email: ${app.email}\\n`;',
  '                detail += `ตำแหน่ง: ${app.position}\\n`;',
  '                detail += `แผนก: ${app.department}\\n`;',
  '                detail += `สาขา: ${app.branch}\\n`;',
  '                if (app.education) detail += `วุฒิ: ${app.education}\\n`;',
  '                if (app.major) detail += `สาขาวิชา: ${app.major}\\n`;',
  '                if (app.skills) detail += `ทักษะ: ${app.skills}\\n`;',
  '                if (app.experience) detail += `ประสบการณ์: ${app.experience} ปี\\n`;',
  '                if (app.aiScore) detail += `\\n🤖 คะแนน AI: ${app.aiScore}/100\\n`;',
  '                if (app.testScores) detail += `\\n📋 คะแนนแบบทดสอบ:\\n  ทัศนคติ: ${app.testScores.attitude}\\n  ทักษะ: ${app.testScores.skill}\\n  CC: ${app.testScores.cc}\\n  3E3P: ${app.testScores.e3p}\\n  รวม: ${app.testScores.overall}\\n`;',
  '                if (app.interviewDate) detail += `\\n📅 นัดสัมภาษณ์: ${app.interviewDate} ${app.interviewTime}\\n`;',
  '                if (app.startDate) detail += `\\n🎉 วันเริ่มงาน: ${app.startDate}\\n`;',
  '                if (app.rejectReason) detail += `\\n❌ เหตุผลไม่ผ่าน: ${app.rejectReason}\\n`;',
  '                detail += `\\n📜 ประวัติ:\\n`;',
  '                app.history.forEach(h => {',
  '                    detail += `  - ${h.action}: ${new Date(h.timestamp).toLocaleString(\'th-TH\')} (${h.note})\\n`;',
  '                });',
  '                alert(detail);',
  '            }',
  '        }',
  '',
  '        // ===== TAB SWITCHING =====',
  '        function showTab(tabName) {',
  '            // Hide all tabs',
  '            const tabs = document.querySelectorAll(\'[id^="tab-"]\');',
  '            tabs.forEach(tab => tab.classList.add(\'hidden\'));',
  '            ',
  '            // Show selected tab',
  '            const targetTab = document.getElementById(\'tab-\' + tabName);',
  '            if (targetTab) {',
  '                targetTab.classList.remove(\'hidden\');',
  '            }',
  '            ',
  '            // Update sidebar active state',
  '            document.querySelectorAll(\'.nav-item\').forEach(item => {',
  '                item.classList.remove(\'active\');',
  '                if (item.getAttribute(\'data-tab\') === tabName) {',
  '                    item.classList.add(\'active\');',
  '                }',
  '            });',
  '            ',
  '            // Close mobile sidebar',
  '            document.getElementById(\'sidebar\').classList.remove(\'open\');',
  '            ',
  '            // Scroll to top',
  '            window.scrollTo({ top: 0, behavior: \'smooth\' });',
  '        }',
  '',
  '        // ===== MODAL FUNCTIONS =====',
  '        function showLogin() { document.getElementById(\'loginModal\').classList.remove(\'hidden\'); }',
  '        function hideLogin() { document.getElementById(\'loginModal\').classList.add(\'hidden\'); }',
  '        function showRegister() { window.location.href = \'form-register.html\'; }',
  '        function hideRegister() { document.getElementById(\'registerModal\').classList.add(\'hidden\'); }',
  '        ',
  '        // ===== ACTION MODAL FUNCTIONS =====',
  '        function showActionModal(actionType) {',
  '            const modal = document.getElementById(\'actionModal\');',
  '            const title = document.getElementById(\'actionModalTitle\');',
  '            const content = document.getElementById(\'actionModalContent\');',
  '            ',
  '            const actions = {',
  '                \'new-applicant\': {',
  '                    title: \'📥 เพิ่มผู้สมัครงานใหม่\',',
  '                    content: `',
  '                        <div class="space-y-4">',
  '                            <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">',
  '                                <p class="text-sm text-blue-800"><strong>ข้อมูลจะเข้า Database 1:</strong> Stock ผู้สมัคร</p>',
  '                            </div>',
  '                            <form id="newApplicantForm" class="space-y-3">',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ชื่อ-นามสกุล *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">เบอร์โทรศัพท์ *</label>',
  '                                    <input type="tel" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>',
  '                                    <input type="email" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งที่สนใจ</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" placeholder="ไม่จำเป็นต้องระบุ">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">Resume/CV</label>',
  '                                    <input type="file" accept=".pdf,.doc,.docx" class="w-full px-3 py-2 border border-gray-300 rounded-lg">',
  '                                </div>',
  '                                <button type="submit" class="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition">เพิ่มผู้สมัคร</button>',
  '                            </form>',
  '                        </div>',
  '                    `',
  '                },',
  '                \'new-position\': {',
  '                    title: \'🏗️ ขออัตรากำลังคน / สร้างโครงสร้างใหม่\',',
  '                    content: `',
  '                        <div class="space-y-4">',
  '                            <div class="bg-green-50 border border-green-200 rounded-lg p-4">',
  '                                <p class="text-sm text-green-800"><strong>ข้อมูลจะเข้า Database 2:</strong> ข้อมูลโครงสร้าง</p>',
  '                            </div>',
  '                            <form id="newPositionForm" class="space-y-3">',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ประเภทคำขอ *</label>',
  '                                    <select required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                        <option value="">-- เลือก --</option>',
  '                                        <option value="new-position">เพิ่มตำแหน่งใหม่</option>',
  '                                        <option value="new-team">สร้างทีมใหม่</option>',
  '                                        <option value="new-company">สร้างบริษัทใหม่</option>',
  '                                    </select>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">บริษัท *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ทีม / ฝ่าย</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งงาน *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">จำนวนที่รับ</label>',
  '                                    <input type="number" min="1" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">คุณสมบัติ</label>',
  '                                    <textarea rows="3" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500"></textarea>',
  '                                </div>',
  '                                <button type="submit" class="w-full bg-green-600 text-white py-2 rounded-lg hover:bg-green-700 transition">สร้างโครงสร้าง</button>',
  '                            </form>',
  '                        </div>',
  '                    `',
  '                },',
  '                \'transfer\': {',
  '                    title: \'🔄 โอนย้ายสมาชิก\',',
  '                    content: `',
  '                        <div class="space-y-4">',
  '                            <div class="bg-orange-50 border border-orange-200 rounded-lg p-4">',
  '                                <p class="text-sm text-orange-800"><strong>ข้อมูลจะเข้า Database 2:</strong> อัพเดทโครงสร้างสมาชิก</p>',
  '                            </div>',
  '                            <form id="transferForm" class="space-y-3">',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">รหัสสมาชิก *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500" placeholder="เช่น X5102012">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ชื่อสมาชิก</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500" readonly>'
];
