var PP7_PART_7 = [
  '        }',
  '',
  '        function renderP2Result(ccScores) {',
  '            const container = document.getElementById(\'p2-content\');',
  '            const overall = calcCCOverall(ccScores);',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <div class="text-center mb-6">',
  '                        <div class="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4"><i class="fas fa-check-circle text-green-600 text-4xl"></i></div>',
  '                        <h2 class="text-2xl font-bold text-gray-800 mb-2">ประเมิน CC เสร็จสิ้น!</h2>',
  '                        <p class="text-gray-600">${p2CurrentApplicant.firstName} ${p2CurrentApplicant.lastName}</p>',
  '                    </div>',
  '                    <div class="bg-gradient-to-r from-purple-600 to-indigo-600 text-white p-6 rounded-xl text-center mb-6">',
  '                        <p class="text-sm opacity-90 mb-1">คะแนน CC รวม</p>',
  '                        <p class="text-5xl font-bold">${overall}</p>',
  '                        <p class="text-sm opacity-75 mt-1">จาก 100 คะแนน</p>',
  '                    </div>',
  '                    <div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">',
  '                        ${CC_DIMENSIONS.map(cc => `',
  '                            <div class="p-3 rounded-lg text-center" style="background:${cc.color}15">',
  '                                <div class="text-xl mb-1">${cc.icon}</div>',
  '                                <div class="text-xs font-bold" style="color:${cc.color}">${cc.key}</div>',
  '                                <div class="text-xs text-gray-600 mb-1">${cc.name}</div>',
  '                                <div class="text-xl font-bold" style="color:${cc.color}">${ccScores[cc.key]}</div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                    <div class="flex justify-center mb-6" style="max-width:400px;margin:0 auto">',
  '                        <canvas id="p2RadarChart" width="400" height="400"></canvas>',
  '                    </div>',
  '                    <div class="flex gap-4">',
  '                        <button onclick="renderP2()" class="flex-1 bg-gray-300 text-gray-700 py-3 rounded-lg hover:bg-gray-400"><i class="fas fa-arrow-left mr-2"></i>กลับรายการ</button>',
  '                        <button onclick="sendToP3(\'${p2CurrentApplicant.id}\')" class="flex-1 bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 font-semibold"><i class="fas fa-arrow-right mr-2"></i>ส่งไป P3 จับคู่</button>',
  '                    </div>',
  '                </div>',
  '            `;',
  '            // Draw radar chart',
  '            setTimeout(() => drawP2Radar(ccScores), 100);',
  '        }',
  '',
  '        function drawP2Radar(ccScores) {',
  '            const ctx = document.getElementById(\'p2RadarChart\');',
  '            if (!ctx) return;',
  '            if (p2RadarChart) { p2RadarChart.destroy(); p2RadarChart = null; }',
  '            p2RadarChart = new Chart(ctx, {',
  '                type: \'radar\',',
  '                data: {',
  '                    labels: CC_DIMENSIONS.map(c => c.key + \' \' + c.name),',
  '                    datasets: [{',
  '                        label: \'CC Score\',',
  '                        data: CC_DIMENSIONS.map(c => ccScores[c.key]),',
  '                        backgroundColor: \'rgba(139, 92, 246, 0.2)\',',
  '                        borderColor: \'rgba(139, 92, 246, 1)\',',
  '                        borderWidth: 2,',
  '                        pointBackgroundColor: CC_DIMENSIONS.map(c => c.color),',
  '                        pointRadius: 5',
  '                    }]',
  '                },',
  '                options: {',
  '                    responsive: true,',
  '                    scales: {',
  '                        r: {',
  '                            beginAtZero: true,',
  '                            max: 100,',
  '                            ticks: { stepSize: 20, font: { size: 10 } },',
  '                            pointLabels: { font: { size: 11, family: \'Prompt\' } }',
  '                        }',
  '                    },',
  '                    plugins: { legend: { display: false } }',
  '                }',
  '            });',
  '        }',
  '',
  '        function sendToP3(appId) {',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (app) {',
  '                app.status = \'assessed\';',
  '                if (!app.history) app.history = [];',
  '                app.history.push({ action:\'ส่งไป P3\', timestamp: new Date().toISOString(), note:\'พร้อมจับคู่ตำแหน่งงาน\' });',
  '                saveApplicantData(app);',
  '            }',
  '            showTab(\'match\');',
  '            renderP3();',
  '        }',
  '',
  '        // ============================================================',
  '        // ===== P3: ระบบจับคู่คนกับงาน (Job Matching) =====',
  '        // ============================================================',
  '',
  '        const P3_JOB_POSITIONS = [',
  '            { id:\'JOB-001\', title:\'ช่างยนต์\', department:\'บริการ\', level:\'Junior\', salary:\'15,000-25,000\', requiredCC:{CC1:50,CC2:60,CC3:60,CC4:60,CC5:80,CC6:70,CC7:40}, requiredSkills:[\'ซ่อมเครื่องยนต์\',\'ระบบไฟฟ้า\',\'การวินิจฉัยปัญหา\'], education:\'ปวส.\' },',
  '            { id:\'JOB-002\', title:\'ที่ปรึกษางานขาย\', department:\'ขาย\', level:\'Entry\', salary:\'12,000-18,000+Comm\', requiredCC:{CC1:60,CC2:70,CC3:80,CC4:70,CC5:60,CC6:50,CC7:80}, requiredSkills:[\'การสื่อสาร\',\'การเจรจา\',\'Microsoft Office\'], education:\'มัธยมศึกษา\' },',
  '            { id:\'JOB-003\', title:\'ช่างเทคนิคคอมพิวเตอร์\', department:\'IT\', level:\'Junior\', salary:\'18,000-28,000\', requiredCC:{CC1:50,CC2:70,CC3:60,CC4:60,CC5:70,CC6:90,CC7:40}, requiredSkills:[\'ซ่อมคอมพิวเตอร์\',\'Network\',\'ติดตั้งระบบ\'], education:\'ปวส.\' },',
  '            { id:\'JOB-004\', title:\'feel well\', department:\'บริการ\', level:\'Entry\', salary:\'13,000-20,000\', requiredCC:{CC1:50,CC2:50,CC3:70,CC4:80,CC5:60,CC6:40,CC7:90}, requiredSkills:[\'การสื่อสาร\',\'การบริการ\',\'ความเป็นมิตร\'], education:\'มัธยมศึกษา\' },',
  '            { id:\'JOB-005\', title:\'หัวหน้าช่าง\', department:\'บริการ\', level:\'Senior\', salary:\'25,000-35,000\', requiredCC:{CC1:90,CC2:70,CC3:70,CC4:80,CC5:80,CC6:80,CC7:60}, requiredSkills:[\'ซ่อมเครื่องยนต์\',\'ระบบไฟฟ้า\',\'ผู้นำทีม\'], education:\'ปวส.\' },',
  '            { id:\'JOB-006\', title:\'ผู้จัดการสาขา\', department:\'บริหาร\', level:\'Manager\', salary:\'35,000-50,000\', requiredCC:{CC1:90,CC2:80,CC3:90,CC4:90,CC5:80,CC6:70,CC7:80}, requiredSkills:[\'การบริหาร\',\'การสื่อสาร\',\'การเจรจา\'], education:\'ปริญญาตรี\' }',
  '        ];',
  '',
  '        function getP3Candidates() {',
  '            const all = getAllApplicants();',
  '            return all.filter(a => a.status === \'assessed\');',
  '        }',
  '',
  '        function calcMatchScore(applicant, job) {',
  '            if (!applicant.ccScores) return 0;',
  '            // CC Match (60%)',
  '            let ccMatch = 0;',
  '            CC_DIMENSIONS.forEach(cc => {',
  '                const appScore = applicant.ccScores[cc.key] || 0;',
  '                const reqScore = job.requiredCC[cc.key] || 50;',
  '                const diff = appScore - reqScore;',
  '                if (diff >= 0) ccMatch += 100;',
  '                else ccMatch += Math.max(0, 100 + diff * 2);',
  '            });',
  '            ccMatch = ccMatch / 7;',
  '            // Skill Match (25%)',
  '            const appSkills = (applicant.skills || \'\').toLowerCase().split(\',\').map(s=>s.trim());',
  '            const reqSkills = job.requiredSkills.map(s=>s.toLowerCase());',
  '            const skillMatched = reqSkills.filter(rs => appSkills.some(as => as.includes(rs) || rs.includes(as)));',
  '            const skillScore = reqSkills.length > 0 ? (skillMatched.length / reqSkills.length) * 100 : 50;',
  '            // Experience Match (15%)',
  '            const exp = parseInt(applicant.experience || 0);',
  '            const expScore = job.level === \'Entry\' ? (exp >= 0 ? 100 : 50) :',
  '                             job.level === \'Junior\' ? Math.min(100, 50 + exp * 15) :',
  '                             job.level === \'Senior\' ? Math.min(100, 40 + exp * 12) :',
  '                             Math.min(100, 30 + exp * 10);',
  '            return Math.round(ccMatch * 0.6 + skillScore * 0.25 + expScore * 0.15);',
  '        }',
  '',
  '        function getTopMatches(applicant) {',
  '            return P3_JOB_POSITIONS.map(job => ({',
  '                ...job,',
  '                matchScore: calcMatchScore(applicant, job)',
  '            })).sort((a,b) => b.matchScore - a.matchScore).slice(0, 3);',
  '        }',
  '',
  '        function renderP3() {',
  '            initP2SampleData();',
  '            const candidates = getP3Candidates();',
  '            const container = document.getElementById(\'p3-content\');',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                    <div class="flex items-center justify-between mb-4">',
  '                        <h2 class="text-xl font-bold text-gray-800"><i class="fas fa-users text-emerald-600 mr-2"></i>ผู้สมัครรอจับคู่ (${candidates.length} คน)</h2>',
  '                        <span class="text-sm text-gray-500">สถานะ: assessed (ผ่าน P2 แล้ว)</span>',
  '                    </div>',
  '                    ${candidates.length === 0 ? \'<p class="text-gray-500 text-center py-8">ไม่มีผู้สมัครรอจับคู่ — กรุณาประเมิน CC ใน P2 ก่อน</p>\' : `',
  '                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">',
  '                        ${candidates.map(app => `',
  '                            <div class="border-2 border-gray-200 rounded-xl p-4 card-hover cursor-pointer hover:border-emerald-500" onclick="startP3Match(\'${app.id}\')">',
  '                                <div class="flex items-center gap-3 mb-3">',
  '                                    <div class="w-12 h-12 bg-emerald-100 rounded-full flex items-center justify-center text-xl font-bold text-emerald-600">${app.firstName.charAt(0)}</div>',
  '                                    <div>',
  '                                        <h3 class="font-bold text-gray-800">${app.firstName} ${app.lastName}</h3>',
  '                                        <p class="text-xs text-gray-500">${app.position || \'ไม่ระบุ\'}</p>',
  '                                    </div>',
  '                                </div>',
  '                                ${app.ccScores ? `',
  '                                    <div class="mb-2">',
  '                                        <div class="text-xs text-gray-600 mb-1">CC Score: <strong class="text-purple-600">${calcCCOverall(app.ccScores)}</strong></div>',
  '                                        <div class="w-full bg-gray-200 rounded-full h-2"><div class="bg-purple-600 h-2 rounded-full" style="width:${calcCCOverall(app.ccScores)}%"></div></div>',
  '                                    </div>',
  '                                    <div class="flex flex-wrap gap-1">',
  '                                        ${CC_DIMENSIONS.map(cc => `<span class="text-xs px-1.5 py-0.5 rounded" style="background:${cc.color}20;color:${cc.color}">${cc.key}:${app.ccScores[cc.key]}</span>`).join(\'\')}',
  '                                    </div>',
  '                                ` : \'\'}',
  '                                <div class="mt-3 text-xs text-emerald-600 font-semibold">🎯 คลิกเพื่อจับคู่ตำแหน่ง</div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>`}',
  '                </div>',
  '                <div class="bg-gradient-to-r from-emerald-50 to-teal-50 rounded-xl p-6 border border-emerald-200">',
  '                    <h3 class="font-bold text-gray-800 mb-3">📋 ตำแหน่งงานที่เปิดรับ (${P3_JOB_POSITIONS.length} ตำแหน่ง)</h3>',
  '                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">',
  '                        ${P3_JOB_POSITIONS.map(job => `',
  '                            <div class="bg-white p-3 rounded-lg shadow-sm">',
  '                                <div class="font-bold text-gray-800 text-sm">${job.title}</div>',
  '                                <div class="text-xs text-gray-500">${job.department} | ${job.level} | ${job.salary} ฿</div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function startP3Match(appId) {',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (!app || !app.ccScores) return;',
  '            const topMatches = getTopMatches(app);',
  '            const container = document.getElementById(\'p3-content\');',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <button onclick="renderP3()" class="mb-4 text-emerald-600 hover:text-emerald-800 text-sm"><i class="fas fa-arrow-left mr-1"></i>กลับรายการ</button>',
  '                    <div class="flex items-center gap-4 mb-6">',
  '                        <div class="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center text-2xl font-bold text-emerald-600">${app.firstName.charAt(0)}</div>',
  '                        <div>',
  '                            <h2 class="text-2xl font-bold text-gray-800">${app.firstName} ${app.lastName}</h2>',
  '                            <p class="text-gray-600">CC Score: <strong class="text-purple-600">${calcCCOverall(app.ccScores)}</strong> | ประสบการณ์: ${app.experience || 0} ปี</p>',
  '                        </div>',
  '                    </div>',
  '',
  '                    <!-- CC Radar -->',
  '                    <div class="flex justify-center mb-6" style="max-width:350px;margin:0 auto">',
  '                        <canvas id="p3RadarChart" width="350" height="350"></canvas>',
  '                    </div>',
  '',
  '                    <h3 class="text-xl font-bold text-gray-800 mb-4"><i class="fas fa-trophy text-amber-500 mr-2"></i>Top 3 ตำแหน่งที่เหมาะสม</h3>',
  '                    <div class="space-y-4 mb-6">',
  '                        ${topMatches.map((job, idx) => {',
  '                            const medals = [\'🥇\',\'🥈\',\'🥉\'];',
  '                            const colors = [\'from-amber-400 to-amber-500\',\'from-gray-300 to-gray-400\',\'from-amber-600 to-amber-700\'];',
  '                            return `',
  '                            <div class="border-2 ${idx===0?\'border-amber-400 bg-amber-50\':\'border-gray-200\'} rounded-xl p-5">',
  '                                <div class="flex items-center justify-between mb-3">',
  '                                    <div class="flex items-center gap-3">',
  '                                        <span class="text-3xl">${medals[idx]}</span>',
  '                                        <div>',
  '                                            <h4 class="font-bold text-gray-800 text-lg">${job.title}</h4>',
  '                                            <p class="text-sm text-gray-600">${job.department} | ${job.level} | ${job.salary} ฿</p>',
  '                                        </div>',
  '                                    </div>',
  '                                    <div class="text-center">',
  '                                        <div class="text-3xl font-bold ${idx===0?\'text-amber-600\':\'text-gray-700\'}">${job.matchScore}</div>',
  '                                        <div class="text-xs text-gray-500">Match Score</div>',
  '                                    </div>',
  '                                </div>',
  '                                <div class="w-full bg-gray-200 rounded-full h-3 mb-3">',
  '                                    <div class="h-3 rounded-full bg-gradient-to-r ${colors[idx]}" style="width:${job.matchScore}%"></div>',
  '                                </div>',
  '                                <div class="grid grid-cols-2 gap-2 text-xs">',
  '                                    <div class="bg-white p-2 rounded">',
  '                                        <span class="text-gray-500">ทักษะที่ต้องการ:</span>',
  '                                        <span class="text-gray-700 ml-1">${job.requiredSkills.join(\', \')}</span>',
  '                                    </div>',
  '                                    <div class="bg-white p-2 rounded">',
  '                                        <span class="text-gray-500">วุฒิ:</span>',
  '                                        <span class="text-gray-700 ml-1">${job.education}</span>',
  '                                    </div>',
  '                                </div>',
  '                            </div>`;',
  '                        }).join(\'\')}',
  '                    </div>',
  '',
  '                    <div class="flex flex-col sm:flex-row gap-4">',
  '                        <button onclick="hireApplicant(\'${app.id}\',\'${topMatches[0].title}\')" class="flex-1 bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 font-semibold text-lg"><i class="fas fa-user-check mr-2"></i>รับเข้าทำงาน</button>',
  '                        <button onclick="createMember(\'${app.id}\')" class="flex-1 bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 font-semibold text-lg"><i class="fas fa-id-card mr-2"></i>สร้างสมาชิก</button>',
  '                    </div>',
  '                </div>',
  '            `;',
  '            // Draw radar',
  '            setTimeout(() => {',
  '                const ctx = document.getElementById(\'p3RadarChart\');',
  '                if (!ctx) return;',
  '                new Chart(ctx, {',
  '                    type: \'radar\',',
  '                    data: {',
  '                        labels: CC_DIMENSIONS.map(c => c.key),',
  '                        datasets: [{',
  '                            label: \'CC Score\',',
  '                            data: CC_DIMENSIONS.map(c => app.ccScores[c.key]),',
  '                            backgroundColor: \'rgba(16, 185, 129, 0.2)\',',
  '                            borderColor: \'rgba(16, 185, 129, 1)\',',
  '                            borderWidth: 2,',
  '                            pointBackgroundColor: CC_DIMENSIONS.map(c => c.color),',
  '                            pointRadius: 4',
  '                        }]',
  '                    },',
  '                    options: {',
  '                        responsive: true,',
  '                        scales: { r: { beginAtZero: true, max: 100, ticks: { stepSize: 20, font:{size:9} }, pointLabels: { font:{size:11, family:\'Prompt\'} } } },',
  '                        plugins: { legend: { display: false } }',
  '                    }',
  '                });',
  '            }, 100);',
  '        }',
  '',
  '        function hireApplicant(appId, position) {',
  '            if (!confirm(`ยืนยันรับ ${position} เข้าทำงาน?`)) return;',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (app) {',
  '                app.status = \'hired\';',
  '                app.hiredPosition = position;',
  '                app.hiredDate = new Date().toISOString().split(\'T\')[0];',
  '                if (!app.history) app.history = [];',
  '                app.history.push({ action:\'รับเข้าทำงาน\', timestamp: new Date().toISOString(), note: `ตำแหน่ง: ${position}` });',
  '                saveApplicantData(app);',
  '                alert(`✅ รับเข้าทำงานสำเร็จ!\\n\\nชื่อ: ${app.firstName} ${app.lastName}\\nตำแหน่ง: ${position}\\nวันที่: ${app.hiredDate}`);',
  '                renderP3();',
  '            }',
  '        }',
  '',
  '        function createMember(appId) {',
  '            if (!confirm(\'สร้างสมาชิกใหม่ในระบบ?\')) return;',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (app) {',
  '                // Save to members list',
  '                const members = JSON.parse(localStorage.getItem(\'pkg_members\') || \'[]\');',
  '                const memberId = \'MEM-\' + Date.now().toString().slice(-6);',
  '                const newMember = {',
  '                    id: memberId,',
  '                    applicantId: app.id,',
  '                    firstName: app.firstName,',
  '                    lastName: app.lastName,',
  '                    phone: app.phone || \'\',',
  '                    email: app.email || \'\',',
  '                    position: app.position || \'\',',
  '                    department: app.department || \'\',',
  '                    branch: app.branch || \'\',',
  '                    ccScores: app.ccScores || {},',
  '                    ccOverall: calcCCOverall(app.ccScores || {}),',
  '                    education: app.education || \'\',',
  '                    experience: app.experience || \'0\',',
  '                    skills: app.skills || \'\',',
  '                    joinedAt: new Date().toISOString(),',
  '                    status: \'active\'',
  '                };',
  '                members.push(newMember);',
  '                localStorage.setItem(\'pkg_members\', JSON.stringify(members));',
  '                // Update applicant status',
  '                app.status = \'member\';',
  '                if (!app.history) app.history = [];',
  '                app.history.push({ action:\'สร้างสมาชิก\', timestamp: new Date().toISOString(), note: `รหัสสมาชิก: ${memberId}` });',
  '                saveApplicantData(app);',
  '                alert(`✅ สร้างสมาชิกสำเร็จ!\\n\\nรหัสสมาชิก: ${memberId}\\nชื่อ: ${app.firstName} ${app.lastName}\\nCC Score: ${newMember.ccOverall}`);',
  '                renderP3();',
  '            }',
  '        }',
  '',
  '        // Hook P2/P3 render on tab show',
  '        const _origShowTab = showTab;',
  '        showTab = function(tabName) {',
  '            _origShowTab(tabName);',
  '            if (tabName === \'assess\') renderP2();',
  '            if (tabName === \'match\') renderP3();',
  '            renderPP7Dashboard(tabName);',
  '        };',
  '    </script>',
  '    <script>',
  '        // Load business structure data',
  '        async function loadBusinessStructureData() {',
  '            try {',
  '                const response = await fetch(\'business-structure-data.json\');',
  '                const data = await response.json();',
  '                ',
  '                // Update last updated',
  '                document.getElementById(\'last-updated\').textContent = data.meta.lastUpdated;',
  '                ',
  '                // Render tax structure',
  '                const taxTbody = document.getElementById(\'tax-tbody\');',
  '                if (taxTbody && data.taxStructure.sampleData) {',
  '                    taxTbody.innerHTML = data.taxStructure.sampleData.map(item => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2">${item[\'รหัสสมาชิก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ชื่อสมาชิก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ประเทศ\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บริษัท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'สาขา\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ตำแหน่งงาน\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'คุณสมบัติ\'] || \'-\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render admin structure',
  '                const adminTbody = document.getElementById(\'admin-tbody\');',
  '                if (adminTbody && data.adminStructure.sampleData) {',
  '                    adminTbody.innerHTML = data.adminStructure.sampleData.map(item => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2">${item[\'ประเทศ\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บริษัท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ทีม\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'กรุ๊ป\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บทบาท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'จุดมุ่งหมายทีม\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'เป้าหมายทีม\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'ตัววัดผลทีม\'] || \'-\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render external companies grid',
  '                const externalGrid = document.getElementById(\'external-companies-grid\');',
  '                if (externalGrid && data.externalCompanies.companies) {',
  '                    const allCompanies = [...data.externalCompanies.companies, ...(data.externalCompanies.otherCompanies || [])];',
  '                    externalGrid.innerHTML = allCompanies.map(company => `',
  '                        <div class="bg-purple-50 p-3 rounded-lg text-center">',
  '                            <div class="text-2xl font-bold text-purple-600">${company.code}</div>',
  '                            <p class="text-xs text-gray-600">${company.name}</p>',
  '                        </div>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render external positions table',
  '                const externalTbody = document.getElementById(\'external-tbody\');',
  '                if (externalTbody && data.externalCompanies.companies) {',
  '                    let allPositions = [];',
  '                    data.externalCompanies.companies.forEach(company => {'
];
