var PP7_PART_5 = [
  '',
  '        function saveApplicantData(app) {',
  '            // ตรวจสอบว่าเป็นข้อมูลตั้งต้นหรือข้อมูลใหม่',
  '            const initial = JSON.parse(localStorage.getItem(\'pkg_initial_applicants\') || \'[]\');',
  '            const newApps = JSON.parse(localStorage.getItem(\'pkg_applications\') || \'[]\');',
  '            ',
  '            const initialIndex = initial.findIndex(a => a.id === app.id);',
  '            if (initialIndex !== -1) {',
  '                // เป็นข้อมูลตั้งต้น',
  '                initial[initialIndex] = app;',
  '                localStorage.setItem(\'pkg_initial_applicants\', JSON.stringify(initial));',
  '            } else {',
  '                // เป็นข้อมูลใหม่',
  '                const newIndex = newApps.findIndex(a => a.id === app.id);',
  '                if (newIndex !== -1) {',
  '                    newApps[newIndex] = app;',
  '                } else {',
  '                    newApps.push(app);',
  '                }',
  '                localStorage.setItem(\'pkg_applications\', JSON.stringify(newApps));',
  '            }',
  '        }',
  '',
  '        function viewApplicantDetail(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                let detail = `📋 รายละเอียดผู้สมัคร\\n\\n`;',
  '                detail += `รหัส: ${app.id}\\n`;',
  '                detail += `ชื่อ: ${app.firstName} ${app.lastName}\\n`;',
  '                if (app.phone) detail += `เบอร์: ${app.phone}\\n`;',
  '                if (app.email) detail += `Email: ${app.email}\\n`;',
  '                detail += `ตำแหน่ง: ${app.position}\\n`;',
  '                detail += `แผนก: ${app.department}\\n`;',
  '                detail += `สาขา: ${app.branch}\\n`;',
  '                if (app.education) detail += `วุฒิ: ${app.education}\\n`;',
  '                if (app.major) detail += `สาขาวิชา: ${app.major}\\n`;',
  '                if (app.skills) detail += `ทักษะ: ${app.skills}\\n`;',
  '                if (app.experience) detail += `ประสบการณ์: ${app.experience} ปี\\n`;',
  '                if (app.aiScore) detail += `\\n🤖 คะแนน AI: ${app.aiScore}/100\\n`;',
  '                if (app.testScores) detail += `\\n📋 คะแนนแบบทดสอบ:\\n  ทัศนคติ: ${app.testScores.attitude}\\n  ทักษะ: ${app.testScores.skill}\\n  CC: ${app.testScores.cc}\\n  3E3P: ${app.testScores.e3p}\\n  รวม: ${app.testScores.overall}\\n`;',
  '                if (app.interviewDate) detail += `\\n📅 นัดสัมภาษณ์: ${app.interviewDate} ${app.interviewTime}\\n`;',
  '                if (app.startDate) detail += `\\n🎉 วันเริ่มงาน: ${app.startDate}\\n`;',
  '                if (app.rejectReason) detail += `\\n❌ เหตุผลไม่ผ่าน: ${app.rejectReason}\\n`;',
  '                detail += `\\n📜 ประวัติ:\\n`;',
  '                app.history.forEach(h => {',
  '                    detail += `  - ${h.action}: ${new Date(h.timestamp).toLocaleString(\'th-TH\')} (${h.note})\\n`;',
  '                });',
  '                alert(detail);',
  '            }',
  '        }',
  '',
  '        // ===== TAB SWITCHING =====',
  '        function showTab(tabName) {',
  '            // Hide all tabs',
  '            const tabs = document.querySelectorAll(\'[id^="tab-"]\');',
  '            tabs.forEach(tab => tab.classList.add(\'hidden\'));',
  '            ',
  '            // Show selected tab',
  '            const targetTab = document.getElementById(\'tab-\' + tabName);',
  '            if (targetTab) {',
  '                targetTab.classList.remove(\'hidden\');',
  '            }',
  '            ',
  '            // Update sidebar active state',
  '            document.querySelectorAll(\'.nav-item\').forEach(item => {',
  '                item.classList.remove(\'active\');',
  '                if (item.getAttribute(\'data-tab\') === tabName) {',
  '                    item.classList.add(\'active\');',
  '                }',
  '            });',
  '            ',
  '            // Close mobile sidebar',
  '            document.getElementById(\'sidebar\').classList.remove(\'open\');',
  '            ',
  '            // Scroll to top',
  '            window.scrollTo({ top: 0, behavior: \'smooth\' });',
  '        }',
  '',
  '        // ===== MODAL FUNCTIONS =====',
  '        function showLogin() { document.getElementById(\'loginModal\').classList.remove(\'hidden\'); }',
  '        function hideLogin() { document.getElementById(\'loginModal\').classList.add(\'hidden\'); }',
  '        function showRegister() { window.location.href = \'form-register.html\'; }',
  '        function hideRegister() { document.getElementById(\'registerModal\').classList.add(\'hidden\'); }',
  '        ',
  '        // ===== ACTION MODAL FUNCTIONS =====',
  '        function showActionModal(actionType) {',
  '            const modal = document.getElementById(\'actionModal\');',
  '            const title = document.getElementById(\'actionModalTitle\');',
  '            const content = document.getElementById(\'actionModalContent\');',
  '            ',
  '            const actions = {',
  '                \'new-applicant\': {',
  '                    title: \'📥 เพิ่มผู้สมัครงานใหม่\',',
  '                    content: `',
  '                        <div class="space-y-4">',
  '                            <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">',
  '                                <p class="text-sm text-blue-800"><strong>ข้อมูลจะเข้า Database 1:</strong> Stock ผู้สมัคร</p>',
  '                            </div>',
  '                            <form id="newApplicantForm" class="space-y-3">',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ชื่อ-นามสกุล *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">เบอร์โทรศัพท์ *</label>',
  '                                    <input type="tel" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>',
  '                                    <input type="email" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งที่สนใจ</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500" placeholder="ไม่จำเป็นต้องระบุ">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">Resume/CV</label>',
  '                                    <input type="file" accept=".pdf,.doc,.docx" class="w-full px-3 py-2 border border-gray-300 rounded-lg">',
  '                                </div>',
  '                                <button type="submit" class="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition">เพิ่มผู้สมัคร</button>',
  '                            </form>',
  '                        </div>',
  '                    `',
  '                },',
  '                \'new-position\': {',
  '                    title: \'🏗️ ขออัตรากำลังคน / สร้างโครงสร้างใหม่\',',
  '                    content: `',
  '                        <div class="space-y-4">',
  '                            <div class="bg-green-50 border border-green-200 rounded-lg p-4">',
  '                                <p class="text-sm text-green-800"><strong>ข้อมูลจะเข้า Database 2:</strong> ข้อมูลโครงสร้าง</p>',
  '                            </div>',
  '                            <form id="newPositionForm" class="space-y-3">',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ประเภทคำขอ *</label>',
  '                                    <select required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                        <option value="">-- เลือก --</option>',
  '                                        <option value="new-position">เพิ่มตำแหน่งใหม่</option>',
  '                                        <option value="new-team">สร้างทีมใหม่</option>',
  '                                        <option value="new-company">สร้างบริษัทใหม่</option>',
  '                                    </select>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">บริษัท *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ทีม / ฝ่าย</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งงาน *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">จำนวนที่รับ</label>',
  '                                    <input type="number" min="1" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">คุณสมบัติ</label>',
  '                                    <textarea rows="3" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500"></textarea>',
  '                                </div>',
  '                                <button type="submit" class="w-full bg-green-600 text-white py-2 rounded-lg hover:bg-green-700 transition">สร้างโครงสร้าง</button>',
  '                            </form>',
  '                        </div>',
  '                    `',
  '                },',
  '                \'transfer\': {',
  '                    title: \'🔄 โอนย้ายสมาชิก\',',
  '                    content: `',
  '                        <div class="space-y-4">',
  '                            <div class="bg-orange-50 border border-orange-200 rounded-lg p-4">',
  '                                <p class="text-sm text-orange-800"><strong>ข้อมูลจะเข้า Database 2:</strong> อัพเดทโครงสร้างสมาชิก</p>',
  '                            </div>',
  '                            <form id="transferForm" class="space-y-3">',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">รหัสสมาชิก *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500" placeholder="เช่น X5102012">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ชื่อสมาชิก</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500" readonly>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">บริษัทเดิม</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50" readonly>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">บริษัทใหม่ *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ทีมใหม่ *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งใหม่</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">เหตุผล</label>',
  '                                    <textarea rows="2" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500"></textarea>',
  '                                </div>',
  '                                <button type="submit" class="w-full bg-orange-600 text-white py-2 rounded-lg hover:bg-orange-700 transition">โอนย้าย</button>',
  '                            </form>',
  '                        </div>',
  '                    `',
  '                },',
  '                \'promotion\': {',
  '                    title: \'📈 เลื่อนตำแหน่ง (Promotion)\',',
  '                    content: `',
  '                        <div class="space-y-4">',
  '                            <div class="bg-red-50 border border-red-200 rounded-lg p-4">',
  '                                <p class="text-sm text-red-800"><strong>ข้อมูลจะเข้า Database 2:</strong> อัพเดทตำแหน่งสมาชิก</p>',
  '                            </div>',
  '                            <form id="promotionForm" class="space-y-3">',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">รหัสสมาชิก *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500" placeholder="เช่น X5102012">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ชื่อสมาชิก</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50" readonly>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งเดิม</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50" readonly>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งใหม่ *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ระดับใหม่</label>',
  '                                    <select class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">',
  '                                        <option value="">-- เลือก --</option>',
  '                                        <option value="staff">Staff</option>',
  '                                        <option value="senior">Senior</option>',
  '                                        <option value="lead">Team Lead</option>',
  '                                        <option value="manager">Manager</option>',
  '                                        <option value="director">Director</option>',
  '                                    </select>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">วันที่มีผล *</label>',
  '                                    <input type="date" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">เหตุผล</label>',
  '                                    <textarea rows="2" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500"></textarea>',
  '                                </div>',
  '                                <button type="submit" class="w-full bg-red-600 text-white py-2 rounded-lg hover:bg-red-700 transition">เลื่อนตำแหน่ง</button>',
  '                            </form>',
  '                        </div>',
  '                    `',
  '                }',
  '            };',
  '            ',
  '            const action = actions[actionType];',
  '            if (action) {',
  '                title.textContent = action.title;',
  '                content.innerHTML = action.content;',
  '                modal.classList.remove(\'hidden\');',
  '                ',
  '                // Add form submit handlers',
  '                setTimeout(() => {',
  '                    const form = content.querySelector(\'form\');',
  '                    if (form) {',
  '                        form.addEventListener(\'submit\', (e) => {',
  '                            e.preventDefault();',
  '                            alert(\'✅ บันทึกข้อมูลสำเร็จ! (Demo - ยังไม่เชื่อม Backend)\');',
  '                            hideActionModal();',
  '                        });',
  '                    }',
  '                }, 100);',
  '            }',
  '        }',
  '        ',
  '        function hideActionModal() {',
  '            document.getElementById(\'actionModal\').classList.add(\'hidden\');',
  '        }',
  '        ',
  '        function handleLogin(event) {',
  '            event.preventDefault();',
  '            const phone = document.getElementById(\'loginPhone\').value;',
  '            const password = document.getElementById(\'loginPassword\').value;',
  '            const users = JSON.parse(localStorage.getItem(\'pkg_users\') || \'[]\');',
  '            const user = users.find(u => u.phone === phone && u.password === btoa(password));',
  '            if (user) {',
  '                localStorage.setItem(\'pkg_current_user\', JSON.stringify(user));',
  '                alert(\'✅ เข้าสู่ระบบสำเร็จ!\\n\\nชื่อ: \' + user.name + \'\\nบทบาท: \' + (user.role === \'hr\' ? \'HR\' : \'ผู้สมัคร\'));',
  '                hideLogin();',
  '                if (user.role === \'hr\') {',
  '                    switchView(\'hr\');',
  '                } else {',
  '                    renderApplicantDashboard();',
  '                }',
  '                document.getElementById(\'recruit-system\').scrollIntoView({behavior:\'smooth\'});',
  '            } else {',
  '                alert(\'❌ เบอร์โทรหรือรหัสผ่านไม่ถูกต้อง\');',
  '            }',
  '        }',
  '        ',
  '        function handleRegister(event) {',
  '            event.preventDefault();',
  '            const name = document.getElementById(\'regName\').value;',
  '            const phone = document.getElementById(\'regPhone\').value;',
  '            const email = document.getElementById(\'regEmail\').value;',
  '            const password = document.getElementById(\'regPassword\').value;',
  '            const users = JSON.parse(localStorage.getItem(\'pkg_users\') || \'[]\');',
  '            if (users.find(u => u.phone === phone)) {',
  '                alert(\'❌ เบอร์โทรนี้ถูกใช้แล้ว\');',
  '                return;',
  '            }',
  '            const newUser = {',
  '                id: \'APP-\' + Date.now().toString().slice(-6),',
  '                name, phone, email,',
  '                password: btoa(password),',
  '                role: \'applicant\',',
  '                status: \'active\',',
  '                createdAt: new Date().toISOString()',
  '            };',
  '            users.push(newUser);',
  '            localStorage.setItem(\'pkg_users\', JSON.stringify(users));',
  '            alert(\'✅ ลงทะเบียนสำเร็จ! กรุณาเข้าสู่ระบบ\');',
  '            hideRegister();',
  '            showLogin();',
  '        }',
  '',
  '        // ============================================================',
  '        // ===== P2: ระบบหยั่งประเมิน (CC Assessment) =====',
  '        // ============================================================',
  '',
  '        const CC_DIMENSIONS = [',
  '            { key: \'CC1\', name: \'Servant Leadership\', icon: \'🫂\', color: \'#8b5cf6\',',
  '              questions: [',
  '                \'คุณให้ความสำคัญกับความต้องการของทีมมากกว่าความต้องการส่วนตัวหรือไม่?\',',
  '                \'คุณเคยช่วยเหลือสมาชิกในทีมให้พัฒนาทักษะหรือไม่?\',',
  '                \'คุณเปิดรับฟังความคิดเห็นของผู้อื่นก่อนตัดสินใจหรือไม่?\',',
  '                \'คุณยินดีรับผิดชอบแทนทีมเมื่อเกิดข้อผิดพลาดหรือไม่?\'',
  '              ]},',
  '            { key: \'CC2\', name: \'Adaptive Innovation\', icon: \'💡\', color: \'#3b82f6\',',
  '              questions: [',
  '                \'คุณพร้อมปรับตัวเมื่อสถานการณ์เปลี่ยนหรือไม่?\',',
  '                \'คุณเคยเสนอแนวทางใหม่เพื่อปรับปรุงงานหรือไม่?\',',
  '                \'คุณเรียนรู้เทคโนโลยี/เครื่องมือใหม่ได้เร็วแค่ไหน?\',',
  '                \'คุณกล้าทดลองวิธีทำงานแบบใหม่ที่ไม่เคยทำมาก่อนหรือไม่?\',',
  '                \'คุณมองปัญหาเป็นโอกาสในการสร้างนวัตกรรมหรือไม่?\'',
  '              ]},',
  '            { key: \'CC3\', name: \'Trust-Based Value Creation\', icon: \'🤝\', color: \'#10b981\',',
  '              questions: [',
  '                \'คุณสร้างความไว้วางใจกับลูกค้า/เพื่อนร่วมงานอย่างไร?\',',
  '                \'คุณยึดมั่นในจริยธรรมทางธุรกิจแม้ในสถานการณ์ยากลำบากหรือไม่?\',',
  '                \'คุณสร้างมูลค่าเพิ่มให้กับองค์กรเกินกว่าที่ได้รับมอบหมายหรือไม่?\',',
  '                \'คุณรักษาความลับขององค์กรและลูกค้าอย่างเคร่งครัดหรือไม่?\'',
  '              ]},',
  '            { key: \'CC4\', name: \'Consensus-Driven Teamwork\', icon: \'👥\', color: \'#f59e0b\',',
  '              questions: [',
  '                \'คุณทำงานร่วมกับผู้อื่นได้ดีแค่ไหน?\',',
  '                \'คุณหาจุดร่วมในความแตกต่างของทีมได้อย่างไร?\',',
  '                \'คุณยอมประนีประนอมเพื่อประโยชน์ของทีมหรือไม่?\',',
  '                \'คุณสื่อสารอย่างเปิดเผยและตรงไปตรงมาหรือไม่?\',',
  '                \'คุณสนับสนุนการตัดสินใจแบบฉันทามติหรือไม่?\'',
  '              ]},',
  '            { key: \'CC5\', name: \'Disciplined Professionalism\', icon: \'🎯\', color: \'#ef4444\',',
  '              questions: [',
  '                \'คุณตรงต่อเวลาและปฏิบัติตามกฎระเบียบหรือไม่?\',',
  '                \'คุณทำงานให้เสร็จตามกำหนดเวลาอย่างมีคุณภาพหรือไม่?\',',
  '                \'คุณรับผิดชอบต่อผลงานของตัวเองหรือไม่?\',',
  '                \'คุณรักษามาตรฐานวิชาชีพในงานที่ทำหรือไม่?\'',
  '              ]},',
  '            { key: \'CC6\', name: \'Technology Mastery\', icon: \'💻\', color: \'#06b6d4\',',
  '              questions: [',
  '                \'คุณใช้เครื่องมือดิจิทัล/เทคโนโลยีในงานได้คล่องแคล่วแค่ไหน?\',',
  '                \'คุณติดตามเทรนด์เทคโนโลยีในสายงานของคุณหรือไม่?\',',
  '                \'คุณสามารถสอนหรือช่วยเหลือผู้อื่นด้านเทคโนโลยีได้หรือไม่?\',',
  '                \'คุณใช้ข้อมูล/ระบบในการตัดสินใจทำงานหรือไม่?\',',
  '                \'คุณเรียนรู้ระบบใหม่ได้เร็วแค่ไหน?\'',
  '              ]},',
  '            { key: \'CC7\', name: \'Humor & Joy\', icon: \'😊\', color: \'#ec4899\',',
  '              questions: [',
  '                \'คุณสร้างบรรยากาศที่ดีในที่ทำงานได้อย่างไร?\',',
  '                \'คุณใช้เสียงหัวเราะเพื่อคลายเครียดในทีมหรือไม่?\',',
  '                \'คุณมองโลกในแง่ดีแม้ในสถานการณ์ยากลำบากหรือไม่?\',',
  '                \'คุณทำให้เพื่อนร่วมงานรู้สึกมีคุณค่าและได้รับการยอมรับหรือไม่?\'',
  '              ]}',
  '        ];',
  '',
  '        // ===== P2 State =====',
  '        let p2CurrentApplicant = null;',
  '        let p2CurrentCC = 0;',
  '        let p2CurrentQuestion = 0;',
  '        let p2Answers = {};',
  '        let p2RadarChart = null;',
  '',
  '        function initP2SampleData() {',
  '            const initial = JSON.parse(localStorage.getItem(\'pkg_initial_applicants\') || \'[]\');',
  '            const sampleIds = [\'P2-SAMPLE-001\',\'P2-SAMPLE-002\',\'P2-SAMPLE-003\',\'P2-SAMPLE-004\',\'P2-SAMPLE-005\'];',
  '            const samples = [',
  '                { id:\'P2-SAMPLE-001\', firstName:\'สมชาย\', lastName:\'ใจดี\', position:\'ช่างยนต์\', department:\'บริการ\', branch:\'ชลบุรี\', status:\'test_done\', phone:\'0810000001\', email:\'somchai@test.com\', education:\'ปวส.\', major:\'ช่างยนต์\', skills:\'ซ่อมเครื่องยนต์, ระบบไฟฟ้า, การวินิจฉัยปัญหา\', experience:\'3\', aiScore:82, appliedAt:\'2026-07-20T08:00:00Z\', testScores:{attitude:85,skill:80,cc:85,e3p:78,overall:82}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-20T08:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-21T10:00:00Z\',note:\'คะแนนรวม: 82\'}] },'
];
