var PP7_PART_1 = [
  '<!DOCTYPE html>',
  '<html lang="th">',
  '<head>',
  '    <meta charset="UTF-8">',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '    <title>PKG Recruitment - ระบบรับสมัครงาน</title>',
  '    <style id="tailwind-inline"></style>',
  '    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">',
  '    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>',
  '    <style>',
  '        @import url(\'https://fonts.googleapis.com/css2?family=Prompt:wght@300;400;500;600;700&display=swap\');',
  '        * { font-family: \'Prompt\', sans-serif; }',
  '        .gradient-bg { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }',
  '        .card-hover { transition: all 0.3s ease; }',
  '        .card-hover:hover { transform: translateY(-5px); box-shadow: 0 20px 25px -5px rgba(0,0,0,0.1); }',
  '        .option-card { transition: all 0.2s ease; cursor: pointer; }',
  '        .option-card:hover { transform: translateX(5px); background: #f3f4f6; }',
  '        .option-card.selected { background: #667eea; color: white; border-color: #667eea; }',
  '        .status-timeline { position: relative; padding-left: 2rem; }',
  '        .status-timeline::before { content: \'\'; position: absolute; left: 0.75rem; top: 0; bottom: 0; width: 2px; background: #e5e7eb; }',
  '        .status-item { position: relative; padding-bottom: 1.5rem; }',
  '        .status-item::before { content: \'\'; position: absolute; left: -1.5rem; top: 0.25rem; width: 1rem; height: 1rem; border-radius: 50%; background: #e5e7eb; border: 2px solid white; }',
  '        .status-item.completed::before { background: #10b981; }',
  '        .status-item.current::before { background: #3b82f6; animation: pulse 2s infinite; }',
  '        .status-item.pending::before { background: #e5e7eb; }',
  '        @keyframes pulse { 0%, 100% { box-shadow: 0 0 0 0 rgba(59, 130, 246, 0.7); } 50% { box-shadow: 0 0 0 0.5rem rgba(59, 130, 246, 0); } }',
  '        ',
  '        /* Sidebar Styles */',
  '        .sidebar { position: fixed; left: 0; top: 0; bottom: 0; width: 260px; background: linear-gradient(180deg, #0f172a 0%, #1e3a5f 100%); color: #fff; z-index: 50; overflow-y: auto; transition: transform .3s; box-shadow: 4px 0 20px rgba(15,23,42,.1); }',
  '        .sidebar-header { padding: 1.25rem 1rem; border-bottom: 1px solid rgba(255,255,255,.1); }',
  '        .sidebar-header h2 { font-size: 1rem; font-weight: 700; color: #fff; margin: 0; }',
  '        .sidebar-header p { font-size: .7rem; color: #94a3b8; margin-top: .25rem; }',
  '        .sidebar-section { padding: .75rem 0; }',
  '        .sidebar-section-title { padding: .5rem 1rem; font-size: .65rem; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: .05em; }',
  '        .nav-item { display: flex; align-items: center; gap: .75rem; padding: .65rem 1rem; color: #cbd5e1; font-size: .85rem; cursor: pointer; border: none; background: none; width: 100%; text-align: left; transition: all .15s; font-family: \'Prompt\', sans-serif; border-left: 3px solid transparent; }',
  '        .nav-item:hover { background: rgba(255,255,255,.05); color: #fff; }',
  '        .nav-item.active { background: rgba(59,130,246,.15); color: #60a5fa; border-left-color: #3b82f6; }',
  '        .nav-item-icon { font-size: 1.1rem; width: 1.5rem; text-align: center; }',
  '        .main-content { margin-left: 260px; min-height: 100vh; background: #f1f5f9; }',
  '        @media (max-width: 768px) {',
  '            .sidebar { transform: translateX(-100%); }',
  '            .sidebar.open { transform: translateX(0); }',
  '            .main-content { margin-left: 0; }',
  '        }',
  '        .mobile-menu-btn { display: none; position: fixed; top: 1rem; left: 1rem; z-index: 60; background: #3b82f6; color: white; border: none; border-radius: 0.5rem; padding: 0.5rem 0.75rem; cursor: pointer; }',
  '        @media (max-width: 768px) { .mobile-menu-btn { display: block; } }',
  '    </style>',
  '</head>',
  '<body class="bg-gray-50">',
  '    <!-- Mobile Menu Button -->',
  '    <button class="mobile-menu-btn" onclick="document.getElementById(\'sidebar\').classList.toggle(\'open\')">☰</button>',
  '',
  '    <!-- Language Selector -->',
  '    <div class="fixed top-4 right-4 z-50 bg-white rounded-lg shadow-lg p-2 flex gap-2">',
  '        <button onclick="setLanguage(\'th\')" id="lang-th" class="px-3 py-1 rounded text-sm font-medium bg-blue-600 text-white">🇹🇭 ไทย</button>',
  '        <button onclick="setLanguage(\'lo\')" id="lang-lo" class="px-3 py-1 rounded text-sm font-medium bg-gray-200 text-gray-700 hover:bg-gray-300">🇱🇦 ລາວ</button>',
  '        <button onclick="setLanguage(\'km\')" id="lang-km" class="px-3 py-1 rounded text-sm font-medium bg-gray-200 text-gray-700 hover:bg-gray-300">🇰🇭 ខ្មែរ</button>',
  '    </div>',
  '',
  '    <!-- Sidebar Navigation -->',
  '    <aside id="sidebar" class="sidebar">',
  '        <div class="sidebar-header">',
  '            <h2>📊 PP7 System</h2>',
  '            <p>ระบบบริหารบุคลากร</p>',
  '        </div>',
  '        ',
  '        <div class="sidebar-section">',
  '            <div class="sidebar-section-title">📋 Core PP7</div>',
  '            <button class="nav-item active" data-tab="landing" onclick="showTab(\'landing\')">',
  '                <span class="nav-item-icon">🏠</span>หน้าหลัก',
  '            </button>',
  '            <button class="nav-item" data-tab="recruit" onclick="showTab(\'recruit\')">',
  '                <span class="nav-item-icon">🔎</span>P1 แสวงหา',
  '            </button>',
  '            <button class="nav-item" data-tab="assess" onclick="showTab(\'assess\')">',
  '                <span class="nav-item-icon">🧭</span>P2 หยั่งประเมิน',
  '            </button>',
  '            <button class="nav-item" data-tab="match" onclick="showTab(\'match\')">',
  '                <span class="nav-item-icon">🤝</span>P3 จับคู่คนกับงาน',
  '            </button>',
  '            <button class="nav-item" data-tab="performance" onclick="showTab(\'performance\')">',
  '                <span class="nav-item-icon">📈</span>P4 ประเมินผล',
  '            </button>',
  '            <button class="nav-item" data-tab="develop" onclick="showTab(\'develop\')">',
  '                <span class="nav-item-icon">🎓</span>P5 พัฒนา',
  '            </button>',
  '            <button class="nav-item" data-tab="welfare" onclick="showTab(\'welfare\')">',
  '                <span class="nav-item-icon">💰</span>P6 ค่าตอบแทน',
  '            </button>',
  '            <button class="nav-item" data-tab="quality" onclick="showTab(\'quality\')">',
  '                <span class="nav-item-icon">🌿</span>P7 คุณภาพชีวิต',
  '            </button>',
  '        </div>',
  '        ',
  '        <div class="sidebar-section">',
  '            <div class="sidebar-section-title">📚 เอกสารอ้างอิง</div>',
  '            <button class="nav-item" data-tab="labor-law" onclick="showTab(\'labor-law\')">',
  '                <span class="nav-item-icon">⚖️</span>กฎหมายแรงงาน',
  '            </button>',
  '            <button class="nav-item" data-tab="pkg-rules" onclick="showTab(\'pkg-rules\')">',
  '                <span class="nav-item-icon">📘</span>ระเบียบบริษัท',
  '            </button>',
  '            <button class="nav-item" data-tab="research" onclick="showTab(\'research\')">',
  '                <span class="nav-item-icon">🔬</span>วิจัย',
  '            </button>',
  '            <button class="nav-item" data-tab="executive" onclick="showTab(\'executive\')">',
  '                <span class="nav-item-icon">📌</span>บทสรุปผู้บริหาร',
  '            </button>',
  '        </div>',
  '',
  '        <div class="sidebar-section">',
  '            <div class="sidebar-section-title">⚡ ศูนย์รวมข้อมูลตั้งต้น</div>',
  '            <button class="nav-item" data-tab="business-structure" onclick="showTab(\'business-structure\')">',
  '                <span class="nav-item-icon">🏗️</span>โครงสร้างธุรกิจ',
  '            </button>',
  '        </div>',
  '    </aside>',
  '    <!-- Main Content -->',
  '    <div class="main-content">',
  '',
  '    <!-- Tab: Landing (หน้าหลัก) -->',
  '    <div id="tab-landing">',
  '    <!-- Navigation -->',
  '    <nav class="bg-white shadow-lg sticky top-0 z-50">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
  '            <div class="flex justify-between h-16">',
  '                <div class="flex items-center">',
  '                    <i class="fas fa-building text-purple-600 text-2xl mr-3"></i>',
  '                    <span class="font-bold text-xl text-gray-800">PKG Recruitment</span>',
  '                </div>',
  '                <div class="flex items-center space-x-4">',
  '                    <button onclick="showLogin()" class="text-gray-700 hover:text-purple-600 px-3 py-2 rounded-md text-sm font-medium">',
  '                        <i class="fas fa-sign-in-alt mr-1"></i>เข้าสู่ระบบ',
  '                    </button>',
  '                    <button onclick="showRegister()" class="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 transition">',
  '                        <i class="fas fa-user-plus mr-1"></i>ลงทะเบียน',
  '                    </button>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </nav>',
  '',
  '    <!-- Hero Section -->',
  '    <div class="gradient-bg text-white py-20">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">',
  '            <h1 class="text-5xl font-bold mb-4">ร่วมงานกับ PKG Group</h1>',
  '            <p class="text-xl opacity-90 mb-8">ระบบรับสมัครงานออนไลน์ที่ทันสมัย ง่าย และรวดเร็ว</p>',
  '            <div class="flex justify-center space-x-4">',
  '                <button onclick="document.getElementById(\'recruit-system\').scrollIntoView({behavior:\'smooth\'})" class="bg-white text-purple-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-100 transition">',
  '                    <i class="fas fa-briefcase mr-2"></i>ดูตำแหน่งงาน',
  '                </button>',
  '                <button onclick="showRegister()" class="bg-purple-700 text-white px-8 py-3 rounded-lg font-semibold hover:bg-purple-800 transition">',
  '                    <i class="fas fa-rocket mr-2"></i>เริ่มสมัครงาน',
  '                </button>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Features Section -->',
  '    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">',
  '        <h2 class="text-3xl font-bold text-center text-gray-800 mb-12">ทำไมต้องสมัครกับเรา?</h2>',
  '        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">',
  '            <div class="bg-white p-8 rounded-xl shadow-lg card-hover">',
  '                <div class="text-4xl text-purple-600 mb-4">🎯</div>',
  '                <h3 class="text-xl font-bold text-gray-800 mb-3">AI คัดกรองอัจฉริยะ</h3>',
  '                <p class="text-gray-600">ระบบ AI วิเคราะห์ความเหมาะสมของคุณกับตำแหน่งงานโดยอัตโนมัติ</p>',
  '            </div>',
  '            <div class="bg-white p-8 rounded-xl shadow-lg card-hover">',
  '                <div class="text-4xl text-blue-600 mb-4">⚡</div>',
  '                <h3 class="text-xl font-bold text-gray-800 mb-3">รวดเร็วและง่ายดาย</h3>',
  '                <p class="text-gray-600">สมัครงานออนไลน์ได้ตลอด 24 ชม. ไม่ต้องเดินทางมาสมัครด้วยตนเอง</p>',
  '            </div>',
  '            <div class="bg-white p-8 rounded-xl shadow-lg card-hover">',
  '                <div class="text-4xl text-green-600 mb-4">📊</div>',
  '                <h3 class="text-xl font-bold text-gray-800 mb-3">ติดตามสถานะได้</h3>',
  '                <p class="text-gray-600">ตรวจสอบสถานะใบสมัครและผลการคัดเลือกได้ผ่าน Dashboard</p>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Steps Section -->',
  '    <div class="bg-gray-100 py-16">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
  '            <h2 class="text-3xl font-bold text-center text-gray-800 mb-12">ขั้นตอนการสมัคร</h2>',
  '            <div class="grid grid-cols-1 md:grid-cols-4 gap-8">',
  '                <div class="text-center">',
  '                    <div class="w-16 h-16 bg-purple-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">1</div>',
  '                    <h3 class="font-bold text-gray-800 mb-2">ลงทะเบียน</h3>',
  '                    <p class="text-gray-600 text-sm">สร้างบัญชีผู้สมัคร</p>',
  '                </div>',
  '                <div class="text-center">',
  '                    <div class="w-16 h-16 bg-purple-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">2</div>',
  '                    <h3 class="font-bold text-gray-800 mb-2">เลือกตำแหน่ง</h3>',
  '                    <p class="text-gray-600 text-sm">ดูตำแหน่งที่เปิดรับ</p>',
  '                </div>',
  '                <div class="text-center">',
  '                    <div class="w-16 h-16 bg-purple-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">3</div>',
  '                    <h3 class="font-bold text-gray-800 mb-2">กรอกใบสมัคร</h3>',
  '                    <p class="text-gray-600 text-sm">กรอกข้อมูล 4 ขั้นตอน</p>',
  '                </div>',
  '                <div class="text-center">',
  '                    <div class="w-16 h-16 bg-purple-600 text-white rounded-full flex items-center justify-center text-2xl font-bold mx-auto mb-4">4</div>',
  '                    <h3 class="font-bold text-gray-800 mb-2">รอผลการคัดเลือก</h3>',
  '                    <p class="text-gray-600 text-sm">ติดตามสถานะใน Dashboard</p>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Recruitment System -->',
  '    <div id="recruit-system" class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">',
  '        <h2 class="text-3xl font-bold text-center text-gray-800 mb-8">🎯 ระบบรับสมัครงาน PKG</h2>',
  '        ',
  '        <!-- View Switcher -->',
  '        <div class="bg-white rounded-xl shadow-lg p-4 mb-6">',
  '            <div class="flex space-x-4">',
  '                <button onclick="switchView(\'applicant\')" id="view-applicant" class="flex-1 py-3 rounded-lg font-semibold bg-purple-600 text-white">',
  '                    <i class="fas fa-user mr-2"></i>ผู้สมัคร',
  '                </button>',
  '                <button onclick="switchView(\'hr\')" id="view-hr" class="flex-1 py-3 rounded-lg font-semibold bg-gray-200 text-gray-700">',
  '                    <i class="fas fa-user-tie mr-2"></i>HR',
  '                </button>',
  '            </div>',
  '        </div>',
  '',
  '        <!-- Content Area -->',
  '        <div id="content-area"></div>',
  '    </div>',
  '',
  '    <!-- Flow 10 ขั้นตอน -->',
  '    <div class="bg-gradient-to-r from-indigo-50 to-blue-50 py-16 border-t-4 border-indigo-300">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
  '            <h2 class="text-3xl font-bold text-center text-gray-800 mb-8">🔄 Flow การสรรหา — 10 ขั้นตอน</h2>',
  '            <div class="grid grid-cols-2 md:grid-cols-5 gap-4">',
  '                <a href="docs/p1-dashboard.html#subtab=headcount" class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-indigo-500 hover:shadow-lg transition-shadow cursor-pointer block">',
  '                    <div class="text-2xl mb-2">📝</div>',
  '                    <div class="font-semibold text-indigo-700">1. BU คีย์ขอโครงสร้าง</div>',
  '                    <div class="text-xs text-slate-600 mt-1">ขออัตรากำลังคน</div>',
  '                    <div class="mt-2 text-xs text-indigo-600 font-medium">🔗 เปิดฟอร์ม</div>',
  '                </a>',
  '                <div class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-blue-500">',
  '                    <div class="text-2xl mb-2">🗄️</div>',
  '                    <div class="font-semibold text-blue-700">2. ฐานข้อมูล</div>',
  '                    <div class="text-xs text-slate-600 mt-1">บริษัท/สาขา/ทีม</div>',
  '                </div>',
  '                <a href="docs/p1-dashboard.html#subtab=postings" class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-emerald-500 hover:shadow-lg transition-shadow cursor-pointer block">',
  '                    <div class="text-2xl mb-2">📢</div>',
  '                    <div class="font-semibold text-emerald-700">3. เปิดรับ</div>',
  '                    <div class="text-xs text-slate-600 mt-1">ประกาศตำแหน่ง</div>',
  '                    <div class="mt-2 text-xs text-emerald-600 font-medium">🔗 เปิดฟอร์ม</div>',
  '                </a>',
  '                <a href="docs/recruit/application-assessment.html" class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-amber-500 hover:shadow-lg transition-shadow cursor-pointer block">',
  '                    <div class="text-2xl mb-2">📥</div>',
  '                    <div class="font-semibold text-amber-700">4. ใบสมัคร</div>',
  '                    <div class="text-xs text-slate-600 mt-1">รับใบสมัคร PKG</div>',
  '                    <div class="mt-2 text-xs text-amber-600 font-medium">🔗 เปิดฟอร์ม</div>',
  '                </a>',
  '                <a href="docs/p1-dashboard.html#subtab=screening" class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-purple-500 hover:shadow-lg transition-shadow cursor-pointer block">',
  '                    <div class="text-2xl mb-2">🎯</div>',
  '                    <div class="font-semibold text-purple-700">5. คัดเลือก</div>',
  '                    <div class="text-xs text-slate-600 mt-1">ผ่าน/ไม่ผ่าน</div>',
  '                    <div class="mt-2 text-xs text-purple-600 font-medium">🔗 เปิดฟอร์ม</div>',
  '                </a>',
  '                <a href="docs/p2-forms/p2-dashboard.html" class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-pink-500 hover:shadow-lg transition-shadow cursor-pointer block">',
  '                    <div class="text-2xl mb-2">📅</div>',
  '                    <div class="font-semibold text-pink-700">6. นัดสัมภาษณ์</div>',
  '                    <div class="text-xs text-slate-600 mt-1">ตอบรับ/ปฏิเสธ</div>',
  '                    <div class="mt-2 text-xs text-pink-600 font-medium">🔗 เปิดฟอร์ม</div>',
  '                </a>',
  '                <a href="docs/p2-forms/interview-new-member.html" class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-red-500 hover:shadow-lg transition-shadow cursor-pointer block">',
  '                    <div class="text-2xl mb-2">💬</div>',
  '                    <div class="font-semibold text-red-700">7. สัมภาษณ์</div>',
  '                    <div class="text-xs text-slate-600 mt-1">ผ่าน/ไม่ผ่าน</div>',
  '                    <div class="mt-2 text-xs text-red-600 font-medium">🔗 เปิดฟอร์ม</div>',
  '                </a>',
  '                <div class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-teal-500">',
  '                    <div class="text-2xl mb-2">🔍</div>',
  '                    <div class="font-semibold text-teal-700">8. ตรวจสอบประวัติ</div>',
  '                    <div class="text-xs text-slate-600 mt-1">ผ่าน/รอตรวจ</div>',
  '                </div>',
  '                <div class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-orange-500">',
  '                    <div class="text-2xl mb-2">🤝</div>',
  '                    <div class="font-semibold text-orange-700">9. นัดเริ่มงาน</div>',
  '                    <div class="text-xs text-slate-600 mt-1">ตกลง/ปฏิเสธ</div>',
  '                </div>',
  '                <div class="bg-white p-4 rounded-lg shadow text-center border-t-4 border-green-500">',
  '                    <div class="text-2xl mb-2">✅</div>',
  '                    <div class="font-semibold text-green-700">10. เข้าระบบ</div>',
  '                    <div class="text-xs text-slate-600 mt-1">ส่งต่อ P4 PAO</div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Statistics -->',
  '    <div class="bg-gradient-to-r from-emerald-50 to-teal-50 py-16 border-t-4 border-emerald-300">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
  '            <h2 class="text-3xl font-bold text-center text-gray-800 mb-8">📊 สถิติ Funnel การสรรหา</h2>',
  '            <div class="grid grid-cols-2 md:grid-cols-4 gap-6">',
  '                <div class="bg-white p-6 rounded-xl shadow text-center">',
  '                    <div class="text-4xl font-bold text-emerald-600">12.4%</div>',
  '                    <div class="text-sm text-slate-600 mt-2">Conversion Rate</div>',
  '                    <div class="text-xs text-slate-500">ใบสมัคร → เข้างาน</div>',
  '                </div>',
  '                <div class="bg-white p-6 rounded-xl shadow text-center">',
  '                    <div class="text-4xl font-bold text-blue-600">18</div>',
  '                    <div class="text-sm text-slate-600 mt-2">Avg Time-to-Hire</div>',
  '                    <div class="text-xs text-slate-500">วัน (เฉลี่ย)</div>',
  '                </div>',
  '                <div class="bg-white p-6 rounded-xl shadow text-center">',
  '                    <div class="text-4xl font-bold text-purple-600">82.4%</div>',
  '                    <div class="text-sm text-slate-600 mt-2">Offer Accept Rate</div>',
  '                    <div class="text-xs text-slate-500">ตกลงเข้างาน</div>',
  '                </div>',
  '                <div class="bg-white p-6 rounded-xl shadow text-center">',
  '                    <div class="text-4xl font-bold text-amber-600">94%</div>',
  '                    <div class="text-sm text-slate-600 mt-2">Background Check</div>',
  '                    <div class="text-xs text-slate-500">ตรวจสอบประวัติผ่าน</div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Footer -->',
  '    <footer class="bg-gray-800 text-white py-8">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">',
  '            <p class="text-lg font-semibold mb-2">PKG Group - ระบบบริหารบุคลากร PP7</p>',
  '            <p class="text-sm opacity-75">© 2026 PKG Group. All rights reserved.</p>',
  '        </div>',
  '    </footer>',
  '',
  '    </div><!-- /tab-landing -->',
  '',
  '    <!-- Tab: P1 แสวงหา (Recruitment) -->',
  '    <div id="tab-recruit" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">🔎</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">P1 — แสวงหา</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">ค้นหาและดึงดูดสมาชิกที่มี Core Competency (CC) ตรงกับความต้องการขององค์กร ผ่านระบบรับสมัครงานออนไลน์ที่ทันสมัย</p>',
  '                <div class="mt-6">',
  '                    <a href="form-register.html" class="inline-block bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-bold py-3 px-8 rounded-lg shadow-lg transition transform hover:scale-105">',
  '                        📝 เปิดฟอร์มสมัครงาน (4 ภาษา)',
  '                    </a>',
  '                </div>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-blue-100 text-blue-800 rounded-full font-semibold"><i class="fas fa-check-circle mr-2"></i>ระบบรับสมัครงานพร้อมใช้งาน</span>',
  '                </div>',
  '                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">',
  '                    <div class="bg-blue-50 p-6 rounded-lg text-center cursor-pointer hover:shadow-lg transition-all" onclick="showTab(\'recruit\')"><div class="text-3xl mb-2">📝</div><h3 class="font-bold text-gray-800 mb-1">สมัครงานออนไลน์</h3><p class="text-sm text-gray-600">ระบบ 4 ขั้นตอน AI คัดกรองอัจฉริยะ</p></div>',
  '                    <div class="bg-indigo-50 p-6 rounded-lg text-center cursor-pointer hover:shadow-lg transition-all" onclick="showTab(\'recruit\')"><div class="text-3xl mb-2">🎯</div><h3 class="font-bold text-gray-800 mb-1">AI Match</h3><p class="text-sm text-gray-600">วิเคราะห์ความเหมาะสมอัตโนมัติ</p></div>',
  '                    <div class="bg-purple-50 p-6 rounded-lg text-center cursor-pointer hover:shadow-lg transition-all" onclick="showTab(\'recruit\')"><div class="text-3xl mb-2">📊</div><h3 class="font-bold text-gray-800 mb-1">Dashboard</h3><p class="text-sm text-gray-600">ติดตามสถานะ Funnel แบบ Real-time</p></div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: P2 หยั่งประเมิน -->',
  '    <div id="tab-assess" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">🧭</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">P2 — หยั่งประเมิน</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">ประเมินศักยภาพก่อนรบ — วัด CC 7 ด้าน เพื่อเตรียมคนให้พร้อมก่อนจับคู่กับตำแหน่งงาน</p>',
  '            </div>',
  '            <div id="p2-content"></div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: P3 จับคู่คนกับงาน -->',
  '    <div id="tab-match" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">🤝</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">P3 — จับคู่คนกับงาน</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">จับคู่คนกับตำแหน่งที่เหมาะสมที่สุด ตาม CC ทักษะ และประสบการณ์</p>',
  '            </div>',
  '            <div id="p3-content"></div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: P4 ประเมินผล -->',
  '    <div id="tab-performance" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">📈</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">P4 — ประเมินผล</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">ประเมินหลังรบ + เครดิตประจำปี 360 องศา — วัดผลงานจริง เปรียบเทียบกับเป้าหมาย</p>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full font-semibold"><i class="fas fa-tools mr-2"></i>กำลังพัฒนา</span>',
  '                </div>',
  '                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">',
  '                    <div class="bg-rose-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">🎯</div><h3 class="font-bold text-gray-800 mb-1">KPI Tracking</h3><p class="text-sm text-gray-600">ติดตามผลตามเป้าหมาย</p></div>',
  '                    <div class="bg-pink-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">🔄</div><h3 class="font-bold text-gray-800 mb-1">360° Review</h3><p class="text-sm text-gray-600">ประเมินรอบด้าน</p></div>',
  '                    <div class="bg-red-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">🏆</div><h3 class="font-bold text-gray-800 mb-1">Annual Credit</h3><p class="text-sm text-gray-600">เครดิตประจำปี</p></div>',
  '                </div>'
];
