var PP7_PART_4 = [
  '                        </div>',
  '                    </div>',
  '',
  '                    <div class="flex justify-between">',
  '                        <button onclick="prevQuestion()" ${currentTest === \'attitude\' && currentQuestion === 0 ? \'disabled\' : \'\'} class="bg-gray-300 text-gray-700 px-6 py-3 rounded-lg hover:bg-gray-400 transition disabled:opacity-50"><i class="fas fa-arrow-left mr-2"></i>ก่อนหน้า</button>',
  '                        ${currentTest === \'e3p\' && currentQuestion === test.questions.length - 1 ? `<button onclick="submitTest()" class="bg-green-600 text-white px-8 py-3 rounded-lg hover:bg-green-700 transition font-semibold"><i class="fas fa-check-circle mr-2"></i>ส่งคำตอบ</button>` : `<button onclick="nextQuestion()" class="bg-purple-600 text-white px-6 py-3 rounded-lg hover:bg-purple-700 transition">ถัดไป<i class="fas fa-arrow-right ml-2"></i></button>`}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function switchTest(test) { currentTest = test; currentQuestion = 0; renderTestView(); }',
  '        function selectAnswer(test, questionId, value) { testAnswers[test][questionId] = value; renderTestView(); }',
  '        function nextQuestion() { const test = TESTS[currentTest]; if (currentQuestion < test.questions.length - 1) currentQuestion++; else { const tests = Object.keys(TESTS); const idx = tests.indexOf(currentTest); if (idx < tests.length - 1) { currentTest = tests[idx + 1]; currentQuestion = 0; } } renderTestView(); }',
  '        function prevQuestion() { if (currentQuestion > 0) currentQuestion--; else { const tests = Object.keys(TESTS); const idx = tests.indexOf(currentTest); if (idx > 0) { currentTest = tests[idx - 1]; currentQuestion = TESTS[currentTest].questions.length - 1; } } renderTestView(); }',
  '',
  '        function submitTest() {',
  '            const totalQuestions = Object.values(TESTS).reduce((sum, t) => sum + t.questions.length, 0);',
  '            const answeredQuestions = Object.values(testAnswers).reduce((sum, t) => sum + Object.keys(t).length, 0);',
  '            if (answeredQuestions < totalQuestions) { if (!confirm(`คุณยังไม่ได้ตอบคำถาม ${totalQuestions - answeredQuestions} ข้อ ต้องการส่งคำตอบหรือไม่?`)) return; }',
  '            else { if (!confirm(\'ต้องการส่งคำตอบหรือไม่?\')) return; }',
  '            ',
  '            const scores = calculateTestScores();',
  '            ',
  '            // บันทึกคะแนนลง localStorage',
  '            const applications = JSON.parse(localStorage.getItem(\'pkg_applications\') || \'[]\');',
  '            const app = applications.find(a => a.id === currentApplicantId);',
  '            if (app) {',
  '                app.testScores = scores;',
  '                app.status = \'test_done\';',
  '                app.history.push({ action: \'ทำแบบทดสอบ\', timestamp: new Date().toISOString(), note: `คะแนนรวม: ${scores.overall}` });',
  '                localStorage.setItem(\'pkg_applications\', JSON.stringify(applications));',
  '            }',
  '            ',
  '            currentStep = \'testResult\';',
  '            renderTestResult(scores);',
  '        }',
  '',
  '        function calculateTestScores() {',
  '            const scores = {};',
  '            Object.keys(TESTS).forEach(key => {',
  '                const total = Object.values(testAnswers[key]).reduce((sum, v) => sum + v, 0);',
  '                const max = TESTS[key].questions.length * 5;',
  '                scores[key] = Math.round((total / max) * 100);',
  '            });',
  '            scores.overall = Math.round((scores.attitude + scores.skill + scores.cc + scores.e3p) / 4);',
  '            return scores;',
  '        }',
  '',
  '        function renderTestResult(scores) {',
  '            const content = document.getElementById(\'content-area\');',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <div class="text-center py-12">',
  '                        <div class="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6"><i class="fas fa-check-circle text-green-600 text-4xl"></i></div>',
  '                        <h2 class="text-2xl font-bold text-gray-800 mb-4">ส่งแบบทดสอบสำเร็จ!</h2>',
  '                        <p class="text-gray-600 mb-8">ขอบคุณที่ทำแบบทดสอบครบทั้ง 4 ชุด</p>',
  '                        ',
  '                        <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">',
  '                            <div class="bg-purple-50 p-4 rounded-lg"><i class="fas fa-smile text-2xl text-purple-600 mb-2"></i><p class="text-sm text-gray-600">ทัศนคติ</p><p class="text-2xl font-bold text-purple-600">${scores.attitude}</p></div>',
  '                            <div class="bg-blue-50 p-4 rounded-lg"><i class="fas fa-tools text-2xl text-blue-600 mb-2"></i><p class="text-sm text-gray-600">ทักษะ</p><p class="text-2xl font-bold text-blue-600">${scores.skill}</p></div>',
  '                            <div class="bg-yellow-50 p-4 rounded-lg"><i class="fas fa-star text-2xl text-yellow-600 mb-2"></i><p class="text-sm text-gray-600">CC 7 ด้าน</p><p class="text-2xl font-bold text-yellow-600">${scores.cc}</p></div>',
  '                            <div class="bg-green-50 p-4 rounded-lg"><i class="fas fa-chart-line text-2xl text-green-600 mb-2"></i><p class="text-sm text-gray-600">3E3P</p><p class="text-2xl font-bold text-green-600">${scores.e3p}</p></div>',
  '                        </div>',
  '                        ',
  '                        <div class="bg-gradient-to-r from-purple-600 to-indigo-600 text-white p-6 rounded-lg mb-8">',
  '                            <p class="text-lg font-semibold mb-2">คะแนนรวม</p>',
  '                            <p class="text-5xl font-bold">${scores.overall}</p>',
  '                            <p class="text-sm opacity-90 mt-2">จาก 100 คะแนน</p>',
  '                        </div>',
  '                        ',
  '                        <div class="bg-blue-50 border-l-4 border-blue-400 p-4 text-left mb-8">',
  '                            <div class="flex items-start"><i class="fas fa-info-circle text-blue-600 mr-2 mt-1"></i><div class="text-sm text-blue-700"><p class="font-semibold mb-2">ขั้นตอนถัดไป:</p><ol class="list-decimal list-inside space-y-1"><li>HR จะประเมินผลแบบทดสอบของคุณ</li><li>หากผ่านเกณฑ์ คุณจะได้รับการนัดสัมภาษณ์</li><li>ติดตามสถานะได้ที่หน้า Dashboard</li></ol></div></div>',
  '                        </div>',
  '                        ',
  '                        <button onclick="renderApplicantDashboard()" class="bg-purple-600 text-white px-8 py-3 rounded-lg hover:bg-purple-700 transition font-semibold"><i class="fas fa-tachometer-alt mr-2"></i>ดูสถานะใบสมัคร</button>',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        // ===== APPLICANT DASHBOARD =====',
  '        function renderApplicantDashboard() {',
  '            const content = document.getElementById(\'content-area\');',
  '            const applications = getAllApplicants();',
  '            const myApps = applications.filter(a => a.id === currentApplicantId);',
  '            ',
  '            if (myApps.length === 0) {',
  '                content.innerHTML = `<div class="bg-white rounded-xl shadow-lg p-6 text-center"><p class="text-gray-500">ยังไม่มีใบสมัคร</p><button onclick="renderPositionsList()" class="mt-4 bg-purple-600 text-white px-6 py-2 rounded-lg hover:bg-purple-700">สมัครงาน</button></div>`;',
  '                return;',
  '            }',
  '            ',
  '            const app = myApps[0];',
  '            const statusSteps = [',
  '                { key: \'new\', label: \'ส่งใบสมัคร\', icon: \'📝\' },',
  '                { key: \'test_done\', label: \'ทำแบบทดสอบ\', icon: \'📋\' },',
  '                { key: \'screened\', label: \'HR คัดกรอง\', icon: \'🎯\' },',
  '                { key: \'interview_scheduled\', label: \'นัดสัมภาษณ์\', icon: \'📅\' },',
  '                { key: \'interviewed\', label: \'สัมภาษณ์แล้ว\', icon: \'💬\' },',
  '                { key: \'assessed\', label: \'ประเมิน CC (P2)\', icon: \'🧭\' },',
  '                { key: \'matched\', label: \'จับคู่คนกับงาน (P3)\', icon: \'🤝\' },',
  '                { key: \'hired\', label: \'ผ่านคัดเลือก\', icon: \'✅\' },',
  '                { key: \'onboarded\', label: \'เริ่มงาน\', icon: \'🎉\' }',
  '            ];',
  '            ',
  '            const currentStepIndex = statusSteps.findIndex(s => s.key === app.status);',
  '            ',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <h2 class="text-2xl font-bold text-gray-800 mb-6"><i class="fas fa-tachometer-alt text-purple-600 mr-2"></i>สถานะใบสมัครของฉัน</h2>',
  '                    ',
  '                    <div class="bg-gradient-to-r from-purple-600 to-indigo-600 text-white p-6 rounded-xl mb-6">',
  '                        <div class="flex justify-between items-start">',
  '                            <div>',
  '                                <p class="text-sm opacity-90 mb-1">รหัสใบสมัคร</p>',
  '                                <p class="text-2xl font-bold mb-2">${app.id}</p>',
  '                                <p class="text-lg">${app.position} - ${app.department}</p>',
  '                                <p class="text-sm opacity-90">${app.branch}</p>',
  '                            </div>',
  '                            <div class="text-right">',
  '                                <p class="text-sm opacity-90">สมัครเมื่อ</p>',
  '                                <p class="text-sm">${new Date(app.appliedAt).toLocaleDateString(\'th-TH\')}</p>',
  '                            </div>',
  '                        </div>',
  '                    </div>',
  '                    ',
  '                    <div class="mb-6">',
  '                        <h3 class="text-lg font-semibold text-gray-700 mb-4">สถานะการดำเนินการ</h3>',
  '                        <div class="status-timeline">',
  '                            ${statusSteps.map((step, idx) => {',
  '                                let statusClass = \'pending\';',
  '                                if (idx < currentStepIndex) statusClass = \'completed\';',
  '                                else if (idx === currentStepIndex) statusClass = \'current\';',
  '                                ',
  '                                return `',
  '                                    <div class="status-item ${statusClass}">',
  '                                        <div class="flex items-start">',
  '                                            <div class="flex-1">',
  '                                                <p class="font-semibold text-gray-800">${step.icon} ${step.label}</p>',
  '                                                ${idx <= currentStepIndex ? `<p class="text-sm text-gray-600">${getStepDescription(step.key, app)}</p>` : \'\'}',
  '                                            </div>',
  '                                            ${idx < currentStepIndex ? \'<i class="fas fa-check-circle text-green-600"></i>\' : \'\'}',
  '                                            ${idx === currentStepIndex ? \'<i class="fas fa-spinner fa-spin text-blue-600"></i>\' : \'\'}',
  '                                        </div>',
  '                                    </div>',
  '                                `;',
  '                            }).join(\'\')}',
  '                        </div>',
  '                    </div>',
  '                    ',
  '                    ${app.aiScore ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">คะแนน AI</h3>',
  '                            <div class="bg-gradient-to-r from-purple-500 to-indigo-500 text-white p-4 rounded-lg">',
  '                                <div class="flex justify-between items-center">',
  '                                    <div>',
  '                                        <p class="text-sm opacity-90">คะแนนความเหมาะสม</p>',
  '                                        <p class="text-3xl font-bold">${app.aiScore}/100</p>',
  '                                    </div>',
  '                                    <i class="fas fa-robot text-4xl opacity-50"></i>',
  '                                </div>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    ${app.testScores ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">คะแนนแบบทดสอบ</h3>',
  '                            <div class="grid grid-cols-2 md:grid-cols-4 gap-4">',
  '                                <div class="bg-purple-50 p-4 rounded-lg text-center"><p class="text-sm text-gray-600">ทัศนคติ</p><p class="text-2xl font-bold text-purple-600">${app.testScores.attitude}</p></div>',
  '                                <div class="bg-blue-50 p-4 rounded-lg text-center"><p class="text-sm text-gray-600">ทักษะ</p><p class="text-2xl font-bold text-blue-600">${app.testScores.skill}</p></div>',
  '                                <div class="bg-yellow-50 p-4 rounded-lg text-center"><p class="text-sm text-gray-600">CC 7 ด้าน</p><p class="text-2xl font-bold text-yellow-600">${app.testScores.cc}</p></div>',
  '                                <div class="bg-green-50 p-4 rounded-lg text-center"><p class="text-sm text-gray-600">3E3P</p><p class="text-2xl font-bold text-green-600">${app.testScores.e3p}</p></div>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    ${app.interviewDate ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">นัดสัมภาษณ์</h3>',
  '                            <div class="bg-orange-50 border-l-4 border-orange-400 p-4 rounded-lg">',
  '                                <p class="font-semibold text-orange-800">📅 วันที่: ${app.interviewDate}</p>',
  '                                <p class="text-sm text-orange-700">⏰ เวลา: ${app.interviewTime}</p>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    ${app.startDate ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">วันเริ่มงาน</h3>',
  '                            <div class="bg-green-50 border-l-4 border-green-400 p-4 rounded-lg">',
  '                                <p class="font-semibold text-green-800">🎉 วันเริ่มงาน: ${app.startDate}</p>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    ${app.rejectReason ? `',
  '                        <div class="mb-6">',
  '                            <h3 class="text-lg font-semibold text-gray-700 mb-4">ผลการคัดเลือก</h3>',
  '                            <div class="bg-red-50 border-l-4 border-red-400 p-4 rounded-lg">',
  '                                <p class="font-semibold text-red-800">❌ ไม่ผ่านการคัดเลือก</p>',
  '                                <p class="text-sm text-red-700">เหตุผล: ${app.rejectReason}</p>',
  '                            </div>',
  '                        </div>',
  '                    ` : \'\'}',
  '                    ',
  '                    <div class="flex space-x-4">',
  '                        <button onclick="renderPositionsList()" class="flex-1 bg-gray-300 text-gray-700 py-3 rounded-lg hover:bg-gray-400 transition"><i class="fas fa-briefcase mr-2"></i>สมัครตำแหน่งอื่น</button>',
  '                        <button onclick="switchView(\'hr\')" class="flex-1 bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 transition"><i class="fas fa-user-tie mr-2"></i>ดูมุมมอง HR</button>',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function getStepDescription(stepKey, app) {',
  '            const descriptions = {',
  '                \'new\': `ส่งใบสมัครเมื่อ ${new Date(app.appliedAt).toLocaleDateString(\'th-TH\')}`,',
  '                \'test_done\': `ทำแบบทดสอบเสร็จสิ้น คะแนนรวม: ${app.testScores?.overall || \'-\'}`,',
  '                \'screened\': \'HR คัดกรองผ่าน กำลังรอนัดสัมภาษณ์\',',
  '                \'interview_scheduled\': `นัดสัมภาษณ์วันที่ ${app.interviewDate} เวลา ${app.interviewTime}`,',
  '                \'interviewed\': `สัมภาษณ์เสร็จสิ้น ${app.interviewNotes ? \'- \' + app.interviewNotes : \'\'}`,',
  '                \'assessed\': `ประเมิน CC เสร็จสิ้น คะแนน CC: ${app.ccScore || \'-\'}`,',
  '                \'matched\': `จับคู่กับตำแหน่ง ${app.matchedPosition || \'รอจับคู่\'}`,',
  '                \'hired\': \'ผ่านคัดเลือก ยินดีด้วย!\',',
  '                \'onboarded\': `เริ่มงานวันที่ ${app.startDate}`',
  '            };',
  '            return descriptions[stepKey] || \'\';',
  '        }',
  '',
  '        // ===== RENDER HR VIEW =====',
  '        function renderHRView() {',
  '            const content = document.getElementById(\'content-area\');',
  '            const applications = getAllApplicants(); // ดึงข้อมูลทั้งหมด (ตั้งต้น + ใหม่)',
  '            ',
  '            content.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <h2 class="text-2xl font-bold text-gray-800 mb-6"><i class="fas fa-user-tie text-purple-600 mr-2"></i>มุมมอง HR - Dashboard</h2>',
  '                    ',
  '                    <div class="grid grid-cols-2 md:grid-cols-6 gap-4 mb-6">',
  '                        <div class="bg-blue-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-gray-800">${applications.length}</p><p class="text-xs text-gray-600">ทั้งหมด</p></div>',
  '                        <div class="bg-blue-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-blue-600">${applications.filter(a => a.status === \'new\').length}</p><p class="text-xs text-gray-600">ใหม่</p></div>',
  '                        <div class="bg-purple-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-purple-600">${applications.filter(a => a.status === \'test_done\').length}</p><p class="text-xs text-gray-600">ทำแบบทดสอบแล้ว</p></div>',
  '                        <div class="bg-orange-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-orange-600">${applications.filter(a => a.status === \'screened\').length}</p><p class="text-xs text-gray-600">คัดกรองแล้ว</p></div>',
  '                        <div class="bg-pink-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-pink-600">${applications.filter(a => a.status === \'interview_scheduled\').length}</p><p class="text-xs text-gray-600">นัดสัมภาษณ์</p></div>',
  '                        <div class="bg-green-50 p-4 rounded-lg text-center"><p class="text-2xl font-bold text-green-600">${applications.filter(a => a.status === \'hired\').length}</p><p class="text-xs text-gray-600">จ้างงาน</p></div>',
  '                    </div>',
  '',
  '                    <h3 class="text-lg font-semibold text-gray-700 mb-4">📋 รายการผู้สมัครทั้งหมด (${applications.length} คน)</h3>',
  '                    <div class="space-y-4">',
  '                        ${applications.map(app => `',
  '                            <div class="border border-gray-200 rounded-lg p-4">',
  '                                <div class="flex justify-between items-start mb-3">',
  '                                    <div>',
  '                                        <h4 class="font-bold text-gray-800">${app.firstName} ${app.lastName}</h4>',
  '                                        <p class="text-sm text-gray-600">${app.position} | ${app.department} | ${app.branch}</p>',
  '                                        ${app.phone ? `<p class="text-xs text-gray-500">📞 ${app.phone} | ✉️ ${app.email || \'-\'}</p>` : \'\'}',
  '                                    </div>',
  '                                    <span class="px-3 py-1 ${getStatusBadgeClass(app.status)} rounded-full text-sm font-semibold">${getStatusText(app.status)}</span>',
  '                                </div>',
  '                                ',
  '                                ${app.aiScore ? `',
  '                                    <div class="mb-3 p-3 bg-purple-50 rounded-lg">',
  '                                        <p class="text-sm font-semibold text-purple-800 mb-1">🤖 คะแนน AI: ${app.aiScore}/100</p>',
  '                                        <div class="w-full bg-gray-200 rounded-full h-2">',
  '                                            <div class="bg-purple-600 h-2 rounded-full" style="width: ${app.aiScore}%"></div>',
  '                                        </div>',
  '                                    </div>',
  '                                ` : \'\'}',
  '                                ',
  '                                ${app.testScores ? `',
  '                                    <div class="mb-3 grid grid-cols-4 gap-2 text-center">',
  '                                        <div class="bg-purple-50 p-2 rounded"><p class="text-xs text-gray-600">ทัศนคติ</p><p class="font-bold text-purple-600">${app.testScores.attitude}</p></div>',
  '                                        <div class="bg-blue-50 p-2 rounded"><p class="text-xs text-gray-600">ทักษะ</p><p class="font-bold text-blue-600">${app.testScores.skill}</p></div>',
  '                                        <div class="bg-yellow-50 p-2 rounded"><p class="text-xs text-gray-600">CC</p><p class="font-bold text-yellow-600">${app.testScores.cc}</p></div>',
  '                                        <div class="bg-green-50 p-2 rounded"><p class="text-xs text-gray-600">3E3P</p><p class="font-bold text-green-600">${app.testScores.e3p}</p></div>',
  '                                    </div>',
  '                                ` : \'\'}',
  '                                ',
  '                                ${app.rejectReason ? `',
  '                                    <div class="mb-3 p-3 bg-red-50 rounded-lg">',
  '                                        <p class="text-sm text-red-800">❌ เหตุผลไม่ผ่าน: ${app.rejectReason}</p>',
  '                                    </div>',
  '                                ` : \'\'}',
  '                                ',
  '                                <div class="flex flex-wrap gap-2">',
  '                                    ${app.status === \'new\' || app.status === \'pending\' ? `<button onclick="screenApplicant(\'${app.id}\')" class="px-3 py-1 bg-purple-600 text-white rounded-lg hover:bg-purple-700 text-sm">✅ คัดกรอง</button>` : \'\'}',
  '                                    ${app.status === \'test_done\' ? `<button onclick="screenApplicant(\'${app.id}\')" class="px-3 py-1 bg-purple-600 text-white rounded-lg hover:bg-purple-700 text-sm">✅ คัดกรอง</button>` : \'\'}',
  '                                    ${app.status === \'screened\' ? `<button onclick="scheduleInterview(\'${app.id}\')" class="px-3 py-1 bg-orange-600 text-white rounded-lg hover:bg-orange-700 text-sm">📅 นัดสัมภาษณ์</button>` : \'\'}',
  '                                    ${app.status === \'interview_scheduled\' ? `<button onclick="markInterviewed(\'${app.id}\')" class="px-3 py-1 bg-pink-600 text-white rounded-lg hover:bg-pink-700 text-sm">💬 สัมภาษณ์แล้ว</button>` : \'\'}',
  '                                    ${app.status === \'interviewed\' ? `<button onclick="finalizeResult(\'${app.id}\')" class="px-3 py-1 bg-green-600 text-white rounded-lg hover:bg-green-700 text-sm">🏆 สรุปผล (ผ่าน)</button>` : \'\'}',
  '                                    ${app.status === \'hired\' ? `<button onclick="onboard(\'${app.id}\')" class="px-3 py-1 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 text-sm">🤝 นัดเริ่มงาน</button>` : \'\'}',
  '                                    <button onclick="viewApplicantDetail(\'${app.id}\')" class="px-3 py-1 bg-gray-600 text-white rounded-lg hover:bg-gray-700 text-sm">👁️ ดูรายละเอียด</button>',
  '                                </div>',
  '                            </div>',
  '                        `).join(\'\') || \'<p class="text-gray-500 text-center py-8">ยังไม่มีผู้สมัคร</p>\'}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function getStatusBadgeClass(status) {',
  '            const classes = {',
  '                \'new\': \'bg-blue-100 text-blue-800\',',
  '                \'test_done\': \'bg-purple-100 text-purple-800\',',
  '                \'screened\': \'bg-orange-100 text-orange-800\',',
  '                \'interview_scheduled\': \'bg-pink-100 text-pink-800\',',
  '                \'interviewed\': \'bg-yellow-100 text-yellow-800\',',
  '                \'hired\': \'bg-green-100 text-green-800\',',
  '                \'onboarded\': \'bg-indigo-100 text-indigo-800\'',
  '            };',
  '            return classes[status] || \'bg-gray-100 text-gray-800\';',
  '        }',
  '',
  '        function getStatusText(status) {',
  '            const texts = {',
  '                \'new\': \'ใหม่\',',
  '                \'test_done\': \'ทำแบบทดสอบแล้ว\',',
  '                \'screened\': \'คัดกรองแล้ว\',',
  '                \'interview_scheduled\': \'นัดสัมภาษณ์\',',
  '                \'interviewed\': \'สัมภาษณ์แล้ว\',',
  '                \'hired\': \'ผ่านคัดเลือก\',',
  '                \'onboarded\': \'เริ่มงาน\'',
  '            };',
  '            return texts[status] || status;',
  '        }',
  '',
  '        function screenApplicant(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                app.status = \'screened\';',
  '                app.history.push({ action: \'คัดกรอง\', timestamp: new Date().toISOString(), note: \'HR คัดกรองผ่าน\' });',
  '                saveApplicantData(app);',
  '                alert(\'✅ คัดกรองผู้สมัครแล้ว!\');',
  '                renderHRView();',
  '            }',
  '        }',
  '',
  '        function scheduleInterview(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                const date = prompt(\'วันที่สัมภาษณ์ (เช่น 25/07/2569):\', \'25/07/2569\');',
  '                const time = prompt(\'เวลาสัมภาษณ์ (เช่น 10:00 น.):\', \'10:00 น.\');',
  '                if (date && time) {',
  '                    app.status = \'interview_scheduled\';',
  '                    app.interviewDate = date;',
  '                    app.interviewTime = time;',
  '                    app.history.push({ action: \'นัดสัมภาษณ์\', timestamp: new Date().toISOString(), note: `วันที่ ${date} เวลา ${time}` });',
  '                    saveApplicantData(app);',
  '                    alert(`✅ นัดสัมภาษณ์แล้ว!\\n\\nวันที่: ${date}\\nเวลา: ${time}`);',
  '                    renderHRView();',
  '                }',
  '            }',
  '        }',
  '',
  '        function markInterviewed(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                // แสดงฟอร์มสัมภาษณ์',
  '                const interviewNotes = prompt(\'บันทึกผลการสัมภาษณ์ (เช่น ผ่าน/ไม่ผ่าน/สำรอง):\', \'ผ่าน - มีศักยภาพดี\');',
  '                if (interviewNotes !== null) {',
  '                    app.status = \'interviewed\';',
  '                    app.interviewNotes = interviewNotes;',
  '                    app.history.push({ action: \'สัมภาษณ์\', timestamp: new Date().toISOString(), note: interviewNotes });',
  '                    saveApplicantData(app);',
  '                    alert(\'✅ บันทึกผลการสัมภาษณ์แล้ว!\\n\\n\' + interviewNotes);',
  '                    renderHRView();',
  '                }',
  '            }',
  '        }',
  '',
  '        function finalizeResult(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                app.status = \'hired\';',
  '                app.history.push({ action: \'สรุปผล\', timestamp: new Date().toISOString(), note: \'ผ่านคัดเลือก\' });',
  '                saveApplicantData(app);',
  '                alert(\'✅ สรุปผล: ผ่าน!\');',
  '                renderHRView();',
  '            }',
  '        }',
  '',
  '        function onboard(appId) {',
  '            const applications = getAllApplicants();',
  '            const app = applications.find(a => a.id === appId);',
  '            if (app) {',
  '                const startDate = prompt(\'วันเริ่มงาน (เช่น 01/08/2569):\', \'01/08/2569\');',
  '                if (startDate) {',
  '                    app.status = \'onboarded\';',
  '                    app.startDate = startDate;',
  '                    app.history.push({ action: \'นัดเริ่มงาน\', timestamp: new Date().toISOString(), note: `วันเริ่มงาน: ${startDate}` });',
  '                    saveApplicantData(app);',
  '                    alert(`✅ นัดเริ่มงานแล้ว!\\n\\nวันเริ่มงาน: ${startDate}`);',
  '                    renderHRView();',
  '                }',
  '            }',
  '        }'
];
