var PP7_PART_1 = [
  '<!DOCTYPE html>',
  '<html lang="th">',
  '<head>',
  '    <meta charset="UTF-8">',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '    <title>PKG Recruitment - ระบบรับสมัครงาน</title>',
  '    <style>',
  '.fixed{position:fixed}',
  '.sticky{position:sticky}',
  '.inset-0{top:0;right:0;bottom:0;left:0}',
  '.top-0{top:0}',
  '.top-4{top:1rem}',
  '.right-4{right:1rem}',
  '.z-50{z-index:50}',
  '.mx-auto{margin-left:auto;margin-right:auto}',
  '.mt-1{margin-top:.25rem}',
  '.mt-2{margin-top:.5rem}',
  '.mt-3{margin-top:.75rem}',
  '.mt-4{margin-top:1rem}',
  '.mt-6{margin-top:1.5rem}',
  '.mr-1{margin-right:.25rem}',
  '.mr-2{margin-right:.5rem}',
  '.mr-3{margin-right:.75rem}',
  '.mr-4{margin-right:1rem}',
  '.mb-1{margin-bottom:.25rem}',
  '.mb-2{margin-bottom:.5rem}',
  '.mb-3{margin-bottom:.75rem}',
  '.mb-4{margin-bottom:1rem}',
  '.mb-6{margin-bottom:1.5rem}',
  '.mb-8{margin-bottom:2rem}',
  '.mb-12{margin-bottom:3rem}',
  '.ml-1{margin-left:.25rem}',
  '.ml-2{margin-left:.5rem}',
  '.block{display:block}',
  '.inline-block{display:inline-block}',
  '.flex{display:flex}',
  '.inline-flex{display:inline-flex}',
  '.grid{display:grid}',
  '.hidden{display:none}',
  '.h-2{height:.5rem}',
  '.h-3{height:.75rem}',
  '.h-8{height:2rem}',
  '.h-10{height:2.5rem}',
  '.h-12{height:3rem}',
  '.h-16{height:4rem}',
  '.h-20{height:5rem}',
  '.w-8{width:2rem}',
  '.w-10{width:2.5rem}',
  '.w-12{width:3rem}',
  '.w-16{width:4rem}',
  '.w-20{width:5rem}',
  '.w-full{width:100%}',
  '.max-w-md{max-width:28rem}',
  '.max-w-2xl{max-width:42rem}',
  '.max-w-7xl{max-width:80rem}',
  '.flex-1{flex:1 1 0%}',
  '.transform{--tw-translate-x:0;--tw-translate-y:0;--tw-rotate:0;--tw-skew-x:0;--tw-skew-y:0;--tw-scale-x:1;--tw-scale-y:1;transform:translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))}',
  '.cursor-pointer{cursor:pointer}',
  '.list-inside{list-style-position:inside}',
  '.list-decimal{list-style-type:decimal}',
  '.grid-cols-1{grid-template-columns:repeat(1,minmax(0,1fr))}',
  '.grid-cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}',
  '.grid-cols-4{grid-template-columns:repeat(4,minmax(0,1fr))}',
  '.flex-col{flex-direction:column}',
  '.flex-wrap{flex-wrap:wrap}',
  '.items-start{align-items:flex-start}',
  '.items-center{align-items:center}',
  '.justify-center{justify-content:center}',
  '.justify-between{justify-content:space-between}',
  '.gap-1{gap:.25rem}',
  '.gap-2{gap:.5rem}',
  '.gap-3{gap:.75rem}',
  '.gap-4{gap:1rem}',
  '.gap-6{gap:1.5rem}',
  '.gap-8{gap:2rem}',
  '.overflow-x-auto{overflow-x:auto}',
  '.overflow-y-auto{overflow-y:auto}',
  '.rounded{border-radius:.25rem}',
  '.rounded-md{border-radius:.375rem}',
  '.rounded-lg{border-radius:.5rem}',
  '.rounded-xl{border-radius:.75rem}',
  '.rounded-full{border-radius:9999px}',
  '.border-2{border-width:2px}',
  '.border{border-width:1px}',
  '.border-t-4{border-top-width:4px}',
  '.border-t{border-top-width:1px}',
  '.border-b{border-bottom-width:1px}',
  '.border-l-4{border-left-width:4px}',
  '.border-gray-200{--tw-border-opacity:1;border-color:rgba(229,231,235,var(--tw-border-opacity))}',
  '.border-gray-300{--tw-border-opacity:1;border-color:rgba(209,213,219,var(--tw-border-opacity))}',
  '.border-red-200{--tw-border-opacity:1;border-color:rgba(254,202,202,var(--tw-border-opacity))}',
  '.border-red-300{--tw-border-opacity:1;border-color:rgba(252,165,165,var(--tw-border-opacity))}',
  '.border-red-400{--tw-border-opacity:1;border-color:rgba(248,113,113,var(--tw-border-opacity))}',
  '.border-red-500{--tw-border-opacity:1;border-color:rgba(239,68,68,var(--tw-border-opacity))}',
  '.border-yellow-400{--tw-border-opacity:1;border-color:rgba(251,191,36,var(--tw-border-opacity))}',
  '.border-green-200{--tw-border-opacity:1;border-color:rgba(167,243,208,var(--tw-border-opacity))}',
  '.border-green-300{--tw-border-opacity:1;border-color:rgba(110,231,183,var(--tw-border-opacity))}',
  '.border-green-400{--tw-border-opacity:1;border-color:rgba(52,211,153,var(--tw-border-opacity))}',
  '.border-green-500{--tw-border-opacity:1;border-color:rgba(16,185,129,var(--tw-border-opacity))}',
  '.border-blue-200{--tw-border-opacity:1;border-color:rgba(191,219,254,var(--tw-border-opacity))}',
  '.border-blue-300{--tw-border-opacity:1;border-color:rgba(147,197,253,var(--tw-border-opacity))}',
  '.border-blue-400{--tw-border-opacity:1;border-color:rgba(96,165,250,var(--tw-border-opacity))}',
  '.border-blue-500{--tw-border-opacity:1;border-color:rgba(59,130,246,var(--tw-border-opacity))}',
  '.border-indigo-300{--tw-border-opacity:1;border-color:rgba(165,180,252,var(--tw-border-opacity))}',
  '.border-indigo-500{--tw-border-opacity:1;border-color:rgba(99,102,241,var(--tw-border-opacity))}',
  '.border-purple-200{--tw-border-opacity:1;border-color:rgba(221,214,254,var(--tw-border-opacity))}',
  '.border-purple-500{--tw-border-opacity:1;border-color:rgba(139,92,246,var(--tw-border-opacity))}',
  '.border-purple-600{--tw-border-opacity:1;border-color:rgba(124,58,237,var(--tw-border-opacity))}',
  '.border-pink-400{--tw-border-opacity:1;border-color:rgba(244,114,182,var(--tw-border-opacity))}',
  '.border-pink-500{--tw-border-opacity:1;border-color:rgba(236,72,153,var(--tw-border-opacity))}',
  '.bg-black{--tw-bg-opacity:1;background-color:rgba(0,0,0,var(--tw-bg-opacity))}',
  '.bg-white{--tw-bg-opacity:1;background-color:rgba(255,255,255,var(--tw-bg-opacity))}',
  '.bg-gray-50{--tw-bg-opacity:1;background-color:rgba(249,250,251,var(--tw-bg-opacity))}',
  '.bg-gray-100{--tw-bg-opacity:1;background-color:rgba(243,244,246,var(--tw-bg-opacity))}',
  '.bg-gray-200{--tw-bg-opacity:1;background-color:rgba(229,231,235,var(--tw-bg-opacity))}',
  '.bg-gray-300{--tw-bg-opacity:1;background-color:rgba(209,213,219,var(--tw-bg-opacity))}',
  '.bg-gray-600{--tw-bg-opacity:1;background-color:rgba(75,85,99,var(--tw-bg-opacity))}',
  '.bg-gray-800{--tw-bg-opacity:1;background-color:rgba(31,41,55,var(--tw-bg-opacity))}',
  '.bg-red-50{--tw-bg-opacity:1;background-color:rgba(254,242,242,var(--tw-bg-opacity))}',
  '.bg-red-100{--tw-bg-opacity:1;background-color:rgba(254,226,226,var(--tw-bg-opacity))}',
  '.bg-red-600{--tw-bg-opacity:1;background-color:rgba(220,38,38,var(--tw-bg-opacity))}',
  '.bg-yellow-50{--tw-bg-opacity:1;background-color:rgba(255,251,235,var(--tw-bg-opacity))}',
  '.bg-green-50{--tw-bg-opacity:1;background-color:rgba(236,253,245,var(--tw-bg-opacity))}',
  '.bg-green-100{--tw-bg-opacity:1;background-color:rgba(209,250,229,var(--tw-bg-opacity))}',
  '.bg-green-600{--tw-bg-opacity:1;background-color:rgba(5,150,105,var(--tw-bg-opacity))}',
  '.bg-blue-50{--tw-bg-opacity:1;background-color:rgba(239,246,255,var(--tw-bg-opacity))}',
  '.bg-blue-100{--tw-bg-opacity:1;background-color:rgba(219,234,254,var(--tw-bg-opacity))}',
  '.bg-blue-500{--tw-bg-opacity:1;background-color:rgba(59,130,246,var(--tw-bg-opacity))}',
  '.bg-blue-600{--tw-bg-opacity:1;background-color:rgba(37,99,235,var(--tw-bg-opacity))}',
  '.bg-indigo-50{--tw-bg-opacity:1;background-color:rgba(238,242,255,var(--tw-bg-opacity))}',
  '.bg-indigo-600{--tw-bg-opacity:1;background-color:rgba(79,70,229,var(--tw-bg-opacity))}',
  '.bg-purple-50{--tw-bg-opacity:1;background-color:rgba(245,243,255,var(--tw-bg-opacity))}',
  '.bg-purple-100{--tw-bg-opacity:1;background-color:rgba(237,233,254,var(--tw-bg-opacity))}',
  '.bg-purple-600{--tw-bg-opacity:1;background-color:rgba(124,58,237,var(--tw-bg-opacity))}',
  '.bg-purple-700{--tw-bg-opacity:1;background-color:rgba(109,40,217,var(--tw-bg-opacity))}',
  '.bg-pink-50{--tw-bg-opacity:1;background-color:rgba(253,242,248,var(--tw-bg-opacity))}',
  '.bg-pink-600{--tw-bg-opacity:1;background-color:rgba(219,39,119,var(--tw-bg-opacity))}',
  '.bg-opacity-50{--tw-bg-opacity:0.5}',
  '.bg-gradient-to-r{background-image:linear-gradient(to right,var(--tw-gradient-stops))}',
  '.bg-gradient-to-br{background-image:linear-gradient(to bottom right,var(--tw-gradient-stops))}',
  '.from-green-500{--tw-gradient-from:#10b981;--tw-gradient-stops:var(--tw-gradient-from),var(--tw-gradient-to, rgba(16, 185, 129, 0))}',
  '.from-blue-500{--tw-gradient-from:#3b82f6;--tw-gradient-stops:var(--tw-gradient-from),var(--tw-gradient-to, rgba(59, 130, 246, 0))}',
  '.from-blue-600{--tw-gradient-from:#2563eb;--tw-gradient-stops:var(--tw-gradient-from),var(--tw-gradient-to, rgba(37, 99, 235, 0))}',
  '.from-indigo-50{--tw-gradient-from:#eef2ff;--tw-gradient-stops:var(--tw-gradient-from),var(--tw-gradient-to, rgba(238, 242, 255, 0))}',
  '.from-purple-50{--tw-gradient-from:#f5f3ff;--tw-gradient-stops:var(--tw-gradient-from),var(--tw-gradient-to, rgba(245, 243, 255, 0))}',
  '.from-purple-500{--tw-gradient-from:#8b5cf6;--tw-gradient-stops:var(--tw-gradient-from),var(--tw-gradient-to, rgba(139, 92, 246, 0))}',
  '.from-purple-600{--tw-gradient-from:#7c3aed;--tw-gradient-stops:var(--tw-gradient-from),var(--tw-gradient-to, rgba(124, 58, 237, 0))}',
  '.to-green-600{--tw-gradient-to:#059669}',
  '.to-blue-50{--tw-gradient-to:#eff6ff}',
  '.to-blue-600{--tw-gradient-to:#2563eb}',
  '.to-indigo-50{--tw-gradient-to:#eef2ff}',
  '.to-indigo-500{--tw-gradient-to:#6366f1}',
  '.to-indigo-600{--tw-gradient-to:#4f46e5}',
  '.to-purple-600{--tw-gradient-to:#7c3aed}',
  '.p-2{padding:.5rem}',
  '.p-3{padding:.75rem}',
  '.p-4{padding:1rem}',
  '.p-5{padding:1.25rem}',
  '.p-6{padding:1.5rem}',
  '.p-8{padding:2rem}',
  '.px-2{padding-left:.5rem;padding-right:.5rem}',
  '.px-3{padding-left:.75rem;padding-right:.75rem}',
  '.px-4{padding-left:1rem;padding-right:1rem}',
  '.px-6{padding-left:1.5rem;padding-right:1.5rem}',
  '.px-8{padding-left:2rem;padding-right:2rem}',
  '.py-1{padding-top:.25rem;padding-bottom:.25rem}',
  '.py-2{padding-top:.5rem;padding-bottom:.5rem}',
  '.py-3{padding-top:.75rem;padding-bottom:.75rem}',
  '.py-8{padding-top:2rem;padding-bottom:2rem}',
  '.py-12{padding-top:3rem;padding-bottom:3rem}',
  '.py-16{padding-top:4rem;padding-bottom:4rem}',
  '.py-20{padding-top:5rem;padding-bottom:5rem}',
  '.pt-4{padding-top:1rem}',
  '.text-left{text-align:left}',
  '.text-center{text-align:center}',
  '.text-right{text-align:right}',
  '.font-mono{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace}',
  '.text-xs{font-size:.75rem;line-height:1rem}',
  '.text-sm{font-size:.875rem;line-height:1.25rem}',
  '.text-lg{font-size:1.125rem;line-height:1.75rem}',
  '.text-xl{font-size:1.25rem;line-height:1.75rem}',
  '.text-2xl{font-size:1.5rem;line-height:2rem}',
  '.text-3xl{font-size:1.875rem;line-height:2.25rem}',
  '.text-4xl{font-size:2.25rem;line-height:2.5rem}',
  '.text-5xl{font-size:3rem;line-height:1}',
  '.text-6xl{font-size:3.75rem;line-height:1}',
  '.font-medium{font-weight:500}',
  '.font-semibold{font-weight:600}',
  '.font-bold{font-weight:700}',
  '.text-white{--tw-text-opacity:1;color:rgba(255,255,255,var(--tw-text-opacity))}',
  '.text-gray-400{--tw-text-opacity:1;color:rgba(156,163,175,var(--tw-text-opacity))}',
  '.text-gray-500{--tw-text-opacity:1;color:rgba(107,114,128,var(--tw-text-opacity))}',
  '.text-gray-600{--tw-text-opacity:1;color:rgba(75,85,99,var(--tw-text-opacity))}',
  '.text-gray-700{--tw-text-opacity:1;color:rgba(55,65,81,var(--tw-text-opacity))}',
  '.text-gray-800{--tw-text-opacity:1;color:rgba(31,41,55,var(--tw-text-opacity))}',
  '.text-red-600{--tw-text-opacity:1;color:rgba(220,38,38,var(--tw-text-opacity))}',
  '.text-red-700{--tw-text-opacity:1;color:rgba(185,28,28,var(--tw-text-opacity))}',
  '.text-red-800{--tw-text-opacity:1;color:rgba(153,27,27,var(--tw-text-opacity))}',
  '.text-yellow-600{--tw-text-opacity:1;color:rgba(217,119,6,var(--tw-text-opacity))}',
  '.text-yellow-800{--tw-text-opacity:1;color:rgba(146,64,14,var(--tw-text-opacity))}',
  '.text-green-600{--tw-text-opacity:1;color:rgba(5,150,105,var(--tw-text-opacity))}',
  '.text-green-700{--tw-text-opacity:1;color:rgba(4,120,87,var(--tw-text-opacity))}',
  '.text-green-800{--tw-text-opacity:1;color:rgba(6,95,70,var(--tw-text-opacity))}',
  '.text-blue-600{--tw-text-opacity:1;color:rgba(37,99,235,var(--tw-text-opacity))}',
  '.text-blue-700{--tw-text-opacity:1;color:rgba(29,78,216,var(--tw-text-opacity))}',
  '.text-blue-800{--tw-text-opacity:1;color:rgba(30,64,175,var(--tw-text-opacity))}',
  '.text-indigo-600{--tw-text-opacity:1;color:rgba(79,70,229,var(--tw-text-opacity))}',
  '.text-indigo-700{--tw-text-opacity:1;color:rgba(67,56,202,var(--tw-text-opacity))}',
  '.text-purple-600{--tw-text-opacity:1;color:rgba(124,58,237,var(--tw-text-opacity))}',
  '.text-purple-700{--tw-text-opacity:1;color:rgba(109,40,217,var(--tw-text-opacity))}',
  '.text-purple-800{--tw-text-opacity:1;color:rgba(91,33,182,var(--tw-text-opacity))}',
  '.text-pink-600{--tw-text-opacity:1;color:rgba(219,39,119,var(--tw-text-opacity))}',
  '.text-pink-700{--tw-text-opacity:1;color:rgba(190,24,93,var(--tw-text-opacity))}',
  '.opacity-50{opacity:.5}',
  '.opacity-75{opacity:.75}',
  '.opacity-90{opacity:.9}',
  '.shadow-sm{--tw-shadow:0 1px 2px 0 rgba(0, 0, 0, 0.05);box-shadow:var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow)}',
  '.shadow{--tw-shadow:0 1px 3px 0 rgba(0, 0, 0, 0.1),0 1px 2px 0 rgba(0, 0, 0, 0.06);box-shadow:var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow)}',
  '.shadow-lg{--tw-shadow:0 10px 15px -3px rgba(0, 0, 0, 0.1),0 4px 6px -2px rgba(0, 0, 0, 0.05);box-shadow:var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow)}',
  '.shadow-2xl{--tw-shadow:0 25px 50px -12px rgba(0, 0, 0, 0.25);box-shadow:var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow)}',
  '.transition-all{transition-property:all;transition-timing-function:cubic-bezier(0.4,0,0.2,1);transition-duration:150ms}',
  '.transition{transition-property:background-color,border-color,color,fill,stroke,opacity,box-shadow,transform,filter,-webkit-backdrop-filter;transition-property:background-color,border-color,color,fill,stroke,opacity,box-shadow,transform,filter,backdrop-filter;transition-property:background-color,border-color,color,fill,stroke,opacity,box-shadow,transform,filter,backdrop-filter,-webkit-backdrop-filter;transition-timing-function:cubic-bezier(0.4,0,0.2,1);transition-duration:150ms}',
  '.transition-shadow{transition-property:box-shadow;transition-timing-function:cubic-bezier(0.4,0,0.2,1);transition-duration:150ms}',
  '',
  '</style>',
  '    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">',
  '    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>',
  '    <style>',
  '        @import url(\'https://fonts.googleapis.com/css2?family=Prompt:wght@300;400;500;600;700&display=swap\');',
  '        * { font-family: \'Prompt\', sans-serif; }',
  '        .gradient-bg { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); }',
  '        .card-hover { transition: all 0.3s ease; }',
  '        .card-hover:hover { transform: translateY(-5px); box-shadow: 0 20px 25px -5px rgba(0,0,0,0.1); }',
  '        .option-card { transition: all 0.2s ease; cursor: pointer; }',
  '        .option-card:hover { transform: translateX(5px); background: #f3f4f6; }',
  '        .option-card.selected { background: #667eea; color: white; border-color: #667eea; }',
  '        .status-timeline { position: relative; padding-left: 2rem; }',
  '        .status-timeline::before { content: \'\'; position: absolute; left: 0.75rem; top: 0; bottom: 0; width: 2px; background: #e5e7eb; }',
  '        .status-item { position: relative; padding-bottom: 1.5rem; }',
  '        .status-item::before { content: \'\'; position: absolute; left: -1.5rem; top: 0.25rem; width: 1rem; height: 1rem; border-radius: 50%; background: #e5e7eb; border: 2px solid white; }',
  '        .status-item.completed::before { background: #10b981; }',
  '        .status-item.current::before { background: #3b82f6; animation: pulse 2s infinite; }',
  '        .status-item.pending::before { background: #e5e7eb; }',
  '        @keyframes pulse { 0%, 100% { box-shadow: 0 0 0 0 rgba(59, 130, 246, 0.7); } 50% { box-shadow: 0 0 0 0.5rem rgba(59, 130, 246, 0); } }',
  '        ',
  '        /* Sidebar Styles */',
  '        .sidebar { position: fixed; left: 0; top: 0; bottom: 0; width: 260px; background: linear-gradient(180deg, #0f172a 0%, #1e3a5f 100%); color: #fff; z-index: 50; overflow-y: auto; transition: transform .3s; box-shadow: 4px 0 20px rgba(15,23,42,.1); }',
  '        .sidebar-header { padding: 1.25rem 1rem; border-bottom: 1px solid rgba(255,255,255,.1); }',
  '        .sidebar-header h2 { font-size: 1rem; font-weight: 700; color: #fff; margin: 0; }',
  '        .sidebar-header p { font-size: .7rem; color: #94a3b8; margin-top: .25rem; }',
  '        .sidebar-section { padding: .75rem 0; }',
  '        .sidebar-section-title { padding: .5rem 1rem; font-size: .65rem; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: .05em; }',
  '        .nav-item { display: flex; align-items: center; gap: .75rem; padding: .65rem 1rem; color: #cbd5e1; font-size: .85rem; cursor: pointer; border: none; background: none; width: 100%; text-align: left; transition: all .15s; font-family: \'Prompt\', sans-serif; border-left: 3px solid transparent; }',
  '        .nav-item:hover { background: rgba(255,255,255,.05); color: #fff; }',
  '        .nav-item.active { background: rgba(59,130,246,.15); color: #60a5fa; border-left-color: #3b82f6; }',
  '        .nav-item-icon { font-size: 1.1rem; width: 1.5rem; text-align: center; }',
  '        .main-content { margin-left: 260px; min-height: 100vh; background: #f1f5f9; }',
  '        @media (max-width: 768px) {',
  '            .sidebar { transform: translateX(-100%); }',
  '            .sidebar.open { transform: translateX(0); }',
  '            .main-content { margin-left: 0; }',
  '        }',
  '        .mobile-menu-btn { display: none; position: fixed; top: 1rem; left: 1rem; z-index: 60; background: #3b82f6; color: white; border: none; border-radius: 0.5rem; padding: 0.5rem 0.75rem; cursor: pointer; }',
  '        @media (max-width: 768px) { .mobile-menu-btn { display: block; } }',
  '        ',
  '        /* ═══ PP7 KPI Dashboard — War Room Style ═══ */',
  '        .pp7-dash{background:#fff;border-radius:12px;padding:20px;box-shadow:0 1px 3px rgba(0,0,0,.08);border:1px solid #e2e8f0;margin-bottom:24px}',
  '        .pp7-dash-title{font-size:1.1rem;font-weight:700;color:#1e293b;margin-bottom:14px;display:flex;align-items:center;gap:8px;padding-bottom:10px;border-bottom:2px solid #e2e8f0}',
  '        .pp7-kpi-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin-bottom:18px}',
  '        .pp7-kpi{background:#f8fafc;border-radius:10px;padding:14px 12px;text-align:center;border:1px solid #e2e8f0;transition:all .2s;position:relative;overflow:hidden}',
  '        .pp7-kpi:hover{box-shadow:0 4px 12px rgba(0,0,0,.1);transform:translateY(-2px)}',
  '        .pp7-kpi .lbl{font-size:.72rem;color:#64748b;font-weight:600;margin-bottom:6px;line-height:1.3}',
  '        .pp7-kpi .val{font-size:1.5rem;font-weight:800;color:#1e293b;line-height:1.1}',
  '        .pp7-kpi .tgt{font-size:.68rem;color:#94a3b8;margin-top:3px}',
  '        .pp7-kpi .pct{font-size:.78rem;font-weight:700;margin-top:4px;display:inline-block;padding:2px 8px;border-radius:6px}',
  '        .pp7-kpi .pct.g{background:#d1fae5;color:#065f46}.pp7-kpi .pct.y{background:#fef3c7;color:#92400e}.pp7-kpi .pct.r{background:#fee2e2;color:#991b1b}',
  '        .pp7-kpi.green{border-left:4px solid #10b981}.pp7-kpi.yellow{border-left:4px solid #f59e0b}.pp7-kpi.red{border-left:4px solid #ef4444}',
  '        .pp7-bar-chart{margin-top:14px}',
  '        .pp7-bar-row{display:flex;align-items:center;gap:8px;margin-bottom:8px}',
  '        .pp7-bar-label{font-size:.78rem;color:#475569;font-weight:600;min-width:100px;flex-shrink:0}',
  '        .pp7-bar-track{flex:1;height:22px;background:#e2e8f0;border-radius:6px;overflow:hidden;position:relative}',
  '        .pp7-bar-fill{height:100%;border-radius:6px;transition:width .5s ease;display:flex;align-items:center;justify-content:flex-end;padding-right:6px;font-size:.68rem;font-weight:700;color:#fff}',
  '        .pp7-bar-val{font-size:.78rem;font-weight:700;color:#1e293b;min-width:45px;text-align:right;flex-shrink:0}',
  '        .pp7-gauge{width:100px;height:60px;position:relative;margin:0 auto}',
  '        .pp7-gauge-bg{width:100px;height:50px;border-radius:50px 50px 0 0;background:conic-gradient(from 270deg at 50% 100%,#ef4444 0deg,#f59e0b 90deg,#10b981 180deg);overflow:hidden;clip-path:polygon(0 100%,100% 100%,100% 50%,0 50%)}',
  '        .pp7-summary-bar{display:flex;gap:4px;height:8px;border-radius:4px;overflow:hidden;margin-top:10px}',
  '        .pp7-summary-bar>div{height:100%}',
  '        @media(max-width:768px){.pp7-kpi-row{grid-template-columns:1fr 1fr}.pp7-bar-label{min-width:70px}}',
  '    </style>',
  '</head>',
  '<body class="bg-gray-50">',
  '    <!-- Mobile Menu Button -->',
  '    <button class="mobile-menu-btn" onclick="document.getElementById(\'sidebar\').classList.toggle(\'open\')">☰</button>',
  '',
  '    <!-- Language Selector -->',
  '    <div class="fixed top-4 right-4 z-50 bg-white rounded-lg shadow-lg p-2 flex gap-2">',
  '        <button onclick="setLanguage(\'th\')" id="lang-th" class="px-3 py-1 rounded text-sm font-medium bg-blue-600 text-white">🇹🇭 ไทย</button>',
  '        <button onclick="setLanguage(\'lo\')" id="lang-lo" class="px-3 py-1 rounded text-sm font-medium bg-gray-200 text-gray-700 hover:bg-gray-300">🇱🇦 ລາວ</button>',
  '        <button onclick="setLanguage(\'km\')" id="lang-km" class="px-3 py-1 rounded text-sm font-medium bg-gray-200 text-gray-700 hover:bg-gray-300">🇰🇭 ខ្មែរ</button>',
  '    </div>',
  '',
  '    <!-- Sidebar Navigation -->',
  '    <aside id="sidebar" class="sidebar">',
  '        <div class="sidebar-header">',
  '            <h2>📊 PP7 System</h2>',
  '            <p>ระบบบริหารบุคลากร</p>',
  '        </div>',
  '        ',
  '        <div class="sidebar-section">',
  '            <div class="sidebar-section-title">📋 Core PP7</div>',
  '            <button class="nav-item active" data-tab="landing" onclick="showTab(\'landing\')">',
  '                <span class="nav-item-icon">🏠</span>หน้าหลัก',
  '            </button>',
  '            <button class="nav-item" data-tab="recruit" onclick="showTab(\'recruit\')">',
  '                <span class="nav-item-icon">🔎</span>P1 แสวงหา',
  '            </button>',
  '            <button class="nav-item" data-tab="assess" onclick="showTab(\'assess\')">',
  '                <span class="nav-item-icon">🧭</span>P2 หยั่งประเมิน',
  '            </button>',
  '            <button class="nav-item" data-tab="match" onclick="showTab(\'match\')">',
  '                <span class="nav-item-icon">🤝</span>P3 จับคู่คนกับงาน',
  '            </button>',
  '            <button class="nav-item" data-tab="performance" onclick="showTab(\'performance\')">',
  '                <span class="nav-item-icon">📈</span>P4 ประเมินผล',
  '            </button>',
  '            <button class="nav-item" data-tab="develop" onclick="showTab(\'develop\')">',
  '                <span class="nav-item-icon">🎓</span>P5 พัฒนา',
  '            </button>',
  '            <button class="nav-item" data-tab="welfare" onclick="showTab(\'welfare\')">',
  '                <span class="nav-item-icon">💰</span>P6 ค่าตอบแทน',
  '            </button>',
  '            <button class="nav-item" data-tab="quality" onclick="showTab(\'quality\')">',
  '                <span class="nav-item-icon">🌿</span>P7 คุณภาพชีวิต',
  '            </button>',
  '        </div>',
  '        ',
  '        <div class="sidebar-section">',
  '            <div class="sidebar-section-title">📚 เอกสารอ้างอิง</div>',
  '            <button class="nav-item" data-tab="labor-law" onclick="showTab(\'labor-law\')">',
  '                <span class="nav-item-icon">⚖️</span>กฎหมายแรงงาน',
  '            </button>',
  '            <button class="nav-item" data-tab="pkg-rules" onclick="showTab(\'pkg-rules\')">',
  '                <span class="nav-item-icon">📘</span>ระเบียบบริษัท',
  '            </button>',
  '            <button class="nav-item" data-tab="research" onclick="showTab(\'research\')">',
  '                <span class="nav-item-icon">🔬</span>วิจัย',
  '            </button>',
  '            <button class="nav-item" data-tab="executive" onclick="showTab(\'executive\')">',
  '                <span class="nav-item-icon">📌</span>บทสรุปผู้บริหาร',
  '            </button>',
  '        </div>',
  '',
  '        <div class="sidebar-section">',
  '            <div class="sidebar-section-title">⚡ ศูนย์รวมข้อมูลตั้งต้น</div>',
  '            <button class="nav-item" data-tab="business-structure" onclick="showTab(\'business-structure\')">',
  '                <span class="nav-item-icon">🏗️</span>โครงสร้างธุรกิจ',
  '            </button>',
  '        </div>',
  '    </aside>',
  '    <!-- Main Content -->',
  '    <div class="main-content">',
  '',
  '    <!-- Tab: Landing (หน้าหลัก) -->',
  '    <div id="tab-landing">',
  '    <!-- Navigation -->',
  '    <nav class="bg-white shadow-lg sticky top-0 z-50">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
  '            <div class="flex justify-between h-16">',
  '                <div class="flex items-center">',
  '                    <i class="fas fa-building text-purple-600 text-2xl mr-3"></i>',
  '                    <span class="font-bold text-xl text-gray-800">PKG Recruitment</span>',
  '                </div>',
  '                <div class="flex items-center space-x-4">',
  '                    <button onclick="showLogin()" class="text-gray-700 hover:text-purple-600 px-3 py-2 rounded-md text-sm font-medium">',
  '                        <i class="fas fa-sign-in-alt mr-1"></i>เข้าสู่ระบบ',
  '                    </button>',
  '                    <button onclick="showRegister()" class="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700 transition">',
  '                        <i class="fas fa-user-plus mr-1"></i>ลงทะเบียน',
  '                    </button>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </nav>',
  '',
  '    <!-- Hero Section -->',
  '    <div class="gradient-bg text-white py-20">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">',
  '            <h1 class="text-5xl font-bold mb-4">ร่วมงานกับ PKG Group</h1>',
  '            <p class="text-xl opacity-90 mb-8">ระบบรับสมัครงานออนไลน์ที่ทันสมัย ง่าย และรวดเร็ว</p>',
  '            <div class="flex justify-center space-x-4">',
  '                <button onclick="document.getElementById(\'recruit-system\').scrollIntoView({behavior:\'smooth\'})" class="bg-white text-purple-600 px-8 py-3 rounded-lg font-semibold hover:bg-gray-100 transition">',
  '                    <i class="fas fa-briefcase mr-2"></i>ดูตำแหน่งงาน',
  '                </button>',
  '                <button onclick="showRegister()" class="bg-purple-700 text-white px-8 py-3 rounded-lg font-semibold hover:bg-purple-800 transition">',
  '                    <i class="fas fa-rocket mr-2"></i>เริ่มสมัครงาน',
  '                </button>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Features Section -->',
  '    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">',
  '        <h2 class="text-3xl font-bold text-center text-gray-800 mb-12">ทำไมต้องสมัครกับเรา?</h2>',
  '        <div class="grid grid-cols-1 md:grid-cols-3 gap-8">',
  '            <div class="bg-white p-8 rounded-xl shadow-lg card-hover">',
  '                <div class="text-4xl text-purple-600 mb-4">🎯</div>',
  '                <h3 class="text-xl font-bold text-gray-800 mb-3">AI คัดกรองอัจฉริยะ</h3>',
  '                <p class="text-gray-600">ระบบ AI วิเคราะห์ความเหมาะสมของคุณกับตำแหน่งงานโดยอัตโนมัติ</p>',
  '            </div>',
  '            <div class="bg-white p-8 rounded-xl shadow-lg card-hover">',
  '                <div class="text-4xl text-blue-600 mb-4">⚡</div>',
  '                <h3 class="text-xl font-bold text-gray-800 mb-3">รวดเร็วและง่ายดาย</h3>',
  '                <p class="text-gray-600">สมัครงานออนไลน์ได้ตลอด 24 ชม. ไม่ต้องเดินทางมาสมัครด้วยตนเอง</p>',
  '            </div>',
  '            <div class="bg-white p-8 rounded-xl shadow-lg card-hover">',
  '                <div class="text-4xl text-green-600 mb-4">📊</div>',
  '                <h3 class="text-xl font-bold text-gray-800 mb-3">ติดตามสถานะได้</h3>',
  '                <p class="text-gray-600">ตรวจสอบสถานะใบสมัครและผลการคัดเลือกได้ผ่าน Dashboard</p>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Steps Section -->',
  '    <div class="bg-gray-100 py-16">'
];
