var PP7_PART_6 = [
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">บริษัทเดิม</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50" readonly>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">บริษัทใหม่ *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ทีมใหม่ *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งใหม่</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">เหตุผล</label>',
  '                                    <textarea rows="2" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500"></textarea>',
  '                                </div>',
  '                                <button type="submit" class="w-full bg-orange-600 text-white py-2 rounded-lg hover:bg-orange-700 transition">โอนย้าย</button>',
  '                            </form>',
  '                        </div>',
  '                    `',
  '                },',
  '                \'promotion\': {',
  '                    title: \'📈 เลื่อนตำแหน่ง (Promotion)\',',
  '                    content: `',
  '                        <div class="space-y-4">',
  '                            <div class="bg-red-50 border border-red-200 rounded-lg p-4">',
  '                                <p class="text-sm text-red-800"><strong>ข้อมูลจะเข้า Database 2:</strong> อัพเดทตำแหน่งสมาชิก</p>',
  '                            </div>',
  '                            <form id="promotionForm" class="space-y-3">',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">รหัสสมาชิก *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500" placeholder="เช่น X5102012">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ชื่อสมาชิก</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50" readonly>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งเดิม</label>',
  '                                    <input type="text" class="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-50" readonly>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ตำแหน่งใหม่ *</label>',
  '                                    <input type="text" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">ระดับใหม่</label>',
  '                                    <select class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">',
  '                                        <option value="">-- เลือก --</option>',
  '                                        <option value="staff">Staff</option>',
  '                                        <option value="senior">Senior</option>',
  '                                        <option value="lead">Team Lead</option>',
  '                                        <option value="manager">Manager</option>',
  '                                        <option value="director">Director</option>',
  '                                    </select>',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">วันที่มีผล *</label>',
  '                                    <input type="date" required class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500">',
  '                                </div>',
  '                                <div>',
  '                                    <label class="block text-sm font-medium text-gray-700 mb-1">เหตุผล</label>',
  '                                    <textarea rows="2" class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500"></textarea>',
  '                                </div>',
  '                                <button type="submit" class="w-full bg-red-600 text-white py-2 rounded-lg hover:bg-red-700 transition">เลื่อนตำแหน่ง</button>',
  '                            </form>',
  '                        </div>',
  '                    `',
  '                }',
  '            };',
  '            ',
  '            const action = actions[actionType];',
  '            if (action) {',
  '                title.textContent = action.title;',
  '                content.innerHTML = action.content;',
  '                modal.classList.remove(\'hidden\');',
  '                ',
  '                // Add form submit handlers',
  '                setTimeout(() => {',
  '                    const form = content.querySelector(\'form\');',
  '                    if (form) {',
  '                        form.addEventListener(\'submit\', (e) => {',
  '                            e.preventDefault();',
  '                            alert(\'✅ บันทึกข้อมูลสำเร็จ! (Demo - ยังไม่เชื่อม Backend)\');',
  '                            hideActionModal();',
  '                        });',
  '                    }',
  '                }, 100);',
  '            }',
  '        }',
  '        ',
  '        function hideActionModal() {',
  '            document.getElementById(\'actionModal\').classList.add(\'hidden\');',
  '        }',
  '        ',
  '        function handleLogin(event) {',
  '            event.preventDefault();',
  '            const phone = document.getElementById(\'loginPhone\').value;',
  '            const password = document.getElementById(\'loginPassword\').value;',
  '            const users = JSON.parse(localStorage.getItem(\'pkg_users\') || \'[]\');',
  '            const user = users.find(u => u.phone === phone && u.password === btoa(password));',
  '            if (user) {',
  '                localStorage.setItem(\'pkg_current_user\', JSON.stringify(user));',
  '                alert(\'✅ เข้าสู่ระบบสำเร็จ!\\n\\nชื่อ: \' + user.name + \'\\nบทบาท: \' + (user.role === \'hr\' ? \'HR\' : \'ผู้สมัคร\'));',
  '                hideLogin();',
  '                if (user.role === \'hr\') {',
  '                    switchView(\'hr\');',
  '                } else {',
  '                    renderApplicantDashboard();',
  '                }',
  '                document.getElementById(\'recruit-system\').scrollIntoView({behavior:\'smooth\'});',
  '            } else {',
  '                alert(\'❌ เบอร์โทรหรือรหัสผ่านไม่ถูกต้อง\');',
  '            }',
  '        }',
  '        ',
  '        function handleRegister(event) {',
  '            event.preventDefault();',
  '            const name = document.getElementById(\'regName\').value;',
  '            const phone = document.getElementById(\'regPhone\').value;',
  '            const email = document.getElementById(\'regEmail\').value;',
  '            const password = document.getElementById(\'regPassword\').value;',
  '            const users = JSON.parse(localStorage.getItem(\'pkg_users\') || \'[]\');',
  '            if (users.find(u => u.phone === phone)) {',
  '                alert(\'❌ เบอร์โทรนี้ถูกใช้แล้ว\');',
  '                return;',
  '            }',
  '            const newUser = {',
  '                id: \'APP-\' + Date.now().toString().slice(-6),',
  '                name, phone, email,',
  '                password: btoa(password),',
  '                role: \'applicant\',',
  '                status: \'active\',',
  '                createdAt: new Date().toISOString()',
  '            };',
  '            users.push(newUser);',
  '            localStorage.setItem(\'pkg_users\', JSON.stringify(users));',
  '            alert(\'✅ ลงทะเบียนสำเร็จ! กรุณาเข้าสู่ระบบ\');',
  '            hideRegister();',
  '            showLogin();',
  '        }',
  '',
  '        // ============================================================',
  '        // ===== P2: ระบบหยั่งประเมิน (CC Assessment) =====',
  '        // ============================================================',
  '',
  '        const CC_DIMENSIONS = [',
  '            { key: \'CC1\', name: \'Servant Leadership\', icon: \'🫂\', color: \'#8b5cf6\',',
  '              questions: [',
  '                \'คุณให้ความสำคัญกับความต้องการของทีมมากกว่าความต้องการส่วนตัวหรือไม่?\',',
  '                \'คุณเคยช่วยเหลือสมาชิกในทีมให้พัฒนาทักษะหรือไม่?\',',
  '                \'คุณเปิดรับฟังความคิดเห็นของผู้อื่นก่อนตัดสินใจหรือไม่?\',',
  '                \'คุณยินดีรับผิดชอบแทนทีมเมื่อเกิดข้อผิดพลาดหรือไม่?\'',
  '              ]},',
  '            { key: \'CC2\', name: \'Adaptive Innovation\', icon: \'💡\', color: \'#3b82f6\',',
  '              questions: [',
  '                \'คุณพร้อมปรับตัวเมื่อสถานการณ์เปลี่ยนหรือไม่?\',',
  '                \'คุณเคยเสนอแนวทางใหม่เพื่อปรับปรุงงานหรือไม่?\',',
  '                \'คุณเรียนรู้เทคโนโลยี/เครื่องมือใหม่ได้เร็วแค่ไหน?\',',
  '                \'คุณกล้าทดลองวิธีทำงานแบบใหม่ที่ไม่เคยทำมาก่อนหรือไม่?\',',
  '                \'คุณมองปัญหาเป็นโอกาสในการสร้างนวัตกรรมหรือไม่?\'',
  '              ]},',
  '            { key: \'CC3\', name: \'Trust-Based Value Creation\', icon: \'🤝\', color: \'#10b981\',',
  '              questions: [',
  '                \'คุณสร้างความไว้วางใจกับลูกค้า/เพื่อนร่วมงานอย่างไร?\',',
  '                \'คุณยึดมั่นในจริยธรรมทางธุรกิจแม้ในสถานการณ์ยากลำบากหรือไม่?\',',
  '                \'คุณสร้างมูลค่าเพิ่มให้กับองค์กรเกินกว่าที่ได้รับมอบหมายหรือไม่?\',',
  '                \'คุณรักษาความลับขององค์กรและลูกค้าอย่างเคร่งครัดหรือไม่?\'',
  '              ]},',
  '            { key: \'CC4\', name: \'Consensus-Driven Teamwork\', icon: \'👥\', color: \'#f59e0b\',',
  '              questions: [',
  '                \'คุณทำงานร่วมกับผู้อื่นได้ดีแค่ไหน?\',',
  '                \'คุณหาจุดร่วมในความแตกต่างของทีมได้อย่างไร?\',',
  '                \'คุณยอมประนีประนอมเพื่อประโยชน์ของทีมหรือไม่?\',',
  '                \'คุณสื่อสารอย่างเปิดเผยและตรงไปตรงมาหรือไม่?\',',
  '                \'คุณสนับสนุนการตัดสินใจแบบฉันทามติหรือไม่?\'',
  '              ]},',
  '            { key: \'CC5\', name: \'Disciplined Professionalism\', icon: \'🎯\', color: \'#ef4444\',',
  '              questions: [',
  '                \'คุณตรงต่อเวลาและปฏิบัติตามกฎระเบียบหรือไม่?\',',
  '                \'คุณทำงานให้เสร็จตามกำหนดเวลาอย่างมีคุณภาพหรือไม่?\',',
  '                \'คุณรับผิดชอบต่อผลงานของตัวเองหรือไม่?\',',
  '                \'คุณรักษามาตรฐานวิชาชีพในงานที่ทำหรือไม่?\'',
  '              ]},',
  '            { key: \'CC6\', name: \'Technology Mastery\', icon: \'💻\', color: \'#06b6d4\',',
  '              questions: [',
  '                \'คุณใช้เครื่องมือดิจิทัล/เทคโนโลยีในงานได้คล่องแคล่วแค่ไหน?\',',
  '                \'คุณติดตามเทรนด์เทคโนโลยีในสายงานของคุณหรือไม่?\',',
  '                \'คุณสามารถสอนหรือช่วยเหลือผู้อื่นด้านเทคโนโลยีได้หรือไม่?\',',
  '                \'คุณใช้ข้อมูล/ระบบในการตัดสินใจทำงานหรือไม่?\',',
  '                \'คุณเรียนรู้ระบบใหม่ได้เร็วแค่ไหน?\'',
  '              ]},',
  '            { key: \'CC7\', name: \'Humor & Joy\', icon: \'😊\', color: \'#ec4899\',',
  '              questions: [',
  '                \'คุณสร้างบรรยากาศที่ดีในที่ทำงานได้อย่างไร?\',',
  '                \'คุณใช้เสียงหัวเราะเพื่อคลายเครียดในทีมหรือไม่?\',',
  '                \'คุณมองโลกในแง่ดีแม้ในสถานการณ์ยากลำบากหรือไม่?\',',
  '                \'คุณทำให้เพื่อนร่วมงานรู้สึกมีคุณค่าและได้รับการยอมรับหรือไม่?\'',
  '              ]}',
  '        ];',
  '',
  '        // ===== P2 State =====',
  '        let p2CurrentApplicant = null;',
  '        let p2CurrentCC = 0;',
  '        let p2CurrentQuestion = 0;',
  '        let p2Answers = {};',
  '        let p2RadarChart = null;',
  '',
  '        function initP2SampleData() {',
  '            const initial = JSON.parse(localStorage.getItem(\'pkg_initial_applicants\') || \'[]\');',
  '            const sampleIds = [\'P2-SAMPLE-001\',\'P2-SAMPLE-002\',\'P2-SAMPLE-003\',\'P2-SAMPLE-004\',\'P2-SAMPLE-005\'];',
  '            const samples = [',
  '                { id:\'P2-SAMPLE-001\', firstName:\'สมชาย\', lastName:\'ใจดี\', position:\'ช่างยนต์\', department:\'บริการ\', branch:\'ชลบุรี\', status:\'test_done\', phone:\'0810000001\', email:\'somchai@test.com\', education:\'ปวส.\', major:\'ช่างยนต์\', skills:\'ซ่อมเครื่องยนต์, ระบบไฟฟ้า, การวินิจฉัยปัญหา\', experience:\'3\', aiScore:82, appliedAt:\'2026-07-20T08:00:00Z\', testScores:{attitude:85,skill:80,cc:85,e3p:78,overall:82}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-20T08:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-21T10:00:00Z\',note:\'คะแนนรวม: 82\'}] },',
  '                { id:\'P2-SAMPLE-002\', firstName:\'พิมพ์ใจ\', lastName:\'รักดี\', position:\'ที่ปรึกษางานขาย\', department:\'ขาย\', branch:\'ชลบุรี\', status:\'test_done\', phone:\'0810000002\', email:\'pimjai@test.com\', education:\'ปริญญาตรี\', major:\'บริหารธุรกิจ\', skills:\'การสื่อสาร, การเจรจา, CRM, Microsoft Office\', experience:\'2\', aiScore:90, appliedAt:\'2026-07-19T09:00:00Z\', testScores:{attitude:95,skill:88,cc:92,e3p:90,overall:91}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-19T09:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-20T11:00:00Z\',note:\'คะแนนรวม: 91\'}] },',
  '                { id:\'P2-SAMPLE-003\', firstName:\'ณัฐพล\', lastName:\'เก่งกาจ\', position:\'ช่างเทคนิคคอมพิวเตอร์\', department:\'IT\', branch:\'ชลบุรี\', status:\'screened\', phone:\'0810000003\', email:\'nuttapon@test.com\', education:\'ปวส.\', major:\'คอมพิวเตอร์\', skills:\'ซ่อมคอมพิวเตอร์, Network, ติดตั้งระบบ, Linux\', experience:\'1\', aiScore:75, appliedAt:\'2026-07-18T07:00:00Z\', testScores:{attitude:78,skill:82,cc:78,e3p:74,overall:78}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-18T07:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-19T09:00:00Z\',note:\'คะแนนรวม: 78\'},{action:\'คัดกรอง\',timestamp:\'2026-07-20T14:00:00Z\',note:\'HR คัดกรองผ่าน\'}] },',
  '                { id:\'P2-SAMPLE-004\', firstName:\'กัลยา\', lastName:\'ชาญชัย\', position:\'feel well\', department:\'บริการ\', branch:\'ชลบุรี\', status:\'test_done\', phone:\'0810000004\', email:\'kanlaya@test.com\', education:\'มัธยมศึกษา\', major:\'ไม่จำกัด\', skills:\'การสื่อสาร, การบริการ, ความเป็นมิตร, First Aid\', experience:\'4\', aiScore:86, appliedAt:\'2026-07-17T10:00:00Z\', testScores:{attitude:92,skill:80,cc:88,e3p:85,overall:86}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-17T10:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-18T13:00:00Z\',note:\'คะแนนรวม: 86\'}] },',
  '                { id:\'P2-SAMPLE-005\', firstName:\'วริศ\', lastName:\'มั่นคง\', position:\'ช่างยนต์\', department:\'บริการ\', branch:\'ชลบุรี\', status:\'screened\', phone:\'0810000005\', email:\'warit@test.com\', education:\'ปวส.\', major:\'ช่างยนต์\', skills:\'ซ่อมเครื่องยนต์, ระบบไฟฟ้า, ไฮบริด, EV, การวินิจฉัยปัญหา\', experience:\'5\', aiScore:94, appliedAt:\'2026-07-16T08:00:00Z\', testScores:{attitude:96,skill:95,cc:95,e3p:93,overall:95}, history:[{action:\'สมัครงาน\',timestamp:\'2026-07-16T08:00:00Z\',note:\'ส่งใบสมัคร\'},{action:\'ทำแบบทดสอบ\',timestamp:\'2026-07-17T10:00:00Z\',note:\'คะแนนรวม: 95\'},{action:\'คัดกรอง\',timestamp:\'2026-07-18T15:00:00Z\',note:\'HR คัดกรองผ่าน\'}] }',
  '            ];',
  '            // Add only if not already present',
  '            samples.forEach(s => {',
  '                if (!initial.find(a => a.id === s.id)) initial.push(s);',
  '            });',
  '            localStorage.setItem(\'pkg_initial_applicants\', JSON.stringify(initial));',
  '        }',
  '',
  '        function getP2Candidates() {',
  '            const all = getAllApplicants();',
  '            return all.filter(a => a.status === \'test_done\' || a.status === \'screened\');',
  '        }',
  '',
  '        function renderP2() {',
  '            initP2SampleData();',
  '            const candidates = getP2Candidates();',
  '            const container = document.getElementById(\'p2-content\');',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                    <div class="flex items-center justify-between mb-4">',
  '                        <h2 class="text-xl font-bold text-gray-800"><i class="fas fa-users text-purple-600 mr-2"></i>ผู้สมัครรอประเมิน CC (${candidates.length} คน)</h2>',
  '                        <span class="text-sm text-gray-500">สถานะ: test_done / screened</span>',
  '                    </div>',
  '                    ${candidates.length === 0 ? \'<p class="text-gray-500 text-center py-8">ไม่มีผู้สมัครรอประเมิน</p>\' : `',
  '                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">',
  '                        ${candidates.map(app => `',
  '                            <div class="border-2 border-gray-200 rounded-xl p-4 card-hover cursor-pointer hover:border-purple-500" onclick="startP2Assess(\'${app.id}\')">',
  '                                <div class="flex items-center gap-3 mb-3">',
  '                                    <div class="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center text-xl font-bold text-purple-600">${app.firstName.charAt(0)}</div>',
  '                                    <div>',
  '                                        <h3 class="font-bold text-gray-800">${app.firstName} ${app.lastName}</h3>',
  '                                        <p class="text-xs text-gray-500">${app.position}</p>',
  '                                    </div>',
  '                                </div>',
  '                                <div class="flex justify-between text-xs text-gray-600 mb-2">',
  '                                    <span>🎓 ${app.education || \'-\'}</span>',
  '                                    <span>💼 ${app.experience || 0} ปี</span>',
  '                                </div>',
  '                                <div class="flex justify-between items-center">',
  '                                    <span class="px-2 py-1 ${getStatusBadgeClass(app.status)} rounded-full text-xs font-semibold">${getStatusText(app.status)}</span>',
  '                                    ${app.aiScore ? `<span class="text-sm font-bold text-purple-600">AI: ${app.aiScore}</span>` : \'\'}',
  '                                </div>',
  '                                ${app.ccScores ? `<div class="mt-2 text-xs text-green-600 font-semibold">✅ ประเมินแล้ว (Score: ${calcCCOverall(app.ccScores)})</div>` : \'<div class="mt-2 text-xs text-amber-600 font-semibold">⏳ ยังไม่ประเมิน</div>\'}',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>`}',
  '                </div>',
  '                <div class="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-xl p-6 border border-purple-200">',
  '                    <h3 class="font-bold text-gray-800 mb-3">🧭 CC 7 ด้าน — Core Competency</h3>',
  '                    <div class="grid grid-cols-2 md:grid-cols-4 gap-3">',
  '                        ${CC_DIMENSIONS.map(cc => `',
  '                            <div class="bg-white p-3 rounded-lg text-center shadow-sm">',
  '                                <div class="text-2xl mb-1">${cc.icon}</div>',
  '                                <div class="text-xs font-bold" style="color:${cc.color}">${cc.key}</div>',
  '                                <div class="text-xs text-gray-600">${cc.name}</div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function startP2Assess(appId) {',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (!app) return;',
  '            p2CurrentApplicant = app;',
  '            p2CurrentCC = 0;',
  '            p2CurrentQuestion = 0;',
  '            p2Answers = {};',
  '            // If already assessed, load existing answers',
  '            if (app.ccScores) {',
  '                p2Answers = JSON.parse(JSON.stringify(app.ccScores));',
  '            }',
  '            renderP2Question();',
  '        }',
  '',
  '        function renderP2Question() {',
  '            const container = document.getElementById(\'p2-content\');',
  '            const cc = CC_DIMENSIONS[p2CurrentCC];',
  '            const q = cc.questions[p2CurrentQuestion];',
  '            const totalQ = CC_DIMENSIONS.reduce((s,c) => s + c.questions.length, 0);',
  '            const answered = Object.keys(p2Answers).length;',
  '            const progress = (answered / totalQ) * 100;',
  '            const currentKey = cc.key + \'_q\' + p2CurrentQuestion;',
  '            const currentVal = p2Answers[currentKey] || 0;',
  '',
  '            container.innerHTML = `',
  '                <div class="bg-white rounded-xl shadow-lg p-6">',
  '                    <div class="flex items-center justify-between mb-4">',
  '                        <button onclick="renderP2()" class="text-purple-600 hover:text-purple-800 text-sm"><i class="fas fa-arrow-left mr-1"></i>กลับรายการ</button>',
  '                        <div class="text-sm text-gray-500">${p2CurrentApplicant.firstName} ${p2CurrentApplicant.lastName} — ${p2CurrentApplicant.position}</div>',
  '                    </div>',
  '                    <div class="flex justify-between items-center mb-2">',
  '                        <h3 class="text-lg font-bold" style="color:${cc.color}">${cc.icon} ${cc.key}: ${cc.name}</h3>',
  '                        <span class="text-sm text-gray-500">ข้อ ${p2CurrentQuestion+1}/${cc.questions.length}</span>',
  '                    </div>',
  '                    <div class="w-full bg-gray-200 rounded-full h-2 mb-6"><div class="h-2 rounded-full" style="width:${progress}%;background:${cc.color}"></div></div>',
  '',
  '                    <!-- CC Navigation Tabs -->',
  '                    <div class="flex flex-wrap gap-1 mb-6">',
  '                        ${CC_DIMENSIONS.map((c,i) => {',
  '                            const cAnswered = c.questions.filter((_,qi) => p2Answers[c.key+\'_q\'+qi]).length;',
  '                            const isComplete = cAnswered === c.questions.length;',
  '                            return `<button onclick="p2CurrentCC=${i};p2CurrentQuestion=0;renderP2Question()" class="px-2 py-1 rounded text-xs font-semibold ${i===p2CurrentCC?\'text-white\':\'bg-gray-100 text-gray-600 hover:bg-gray-200\'} ${isComplete && i!==p2CurrentCC?\'ring-2 ring-green-400\':\'\'}" style="${i===p2CurrentCC?\'background:\'+c.color:\'\'}">${c.key} ${isComplete?\'✓\':\'\'}</button>`;',
  '                        }).join(\'\')}',
  '                    </div>',
  '',
  '                    <div class="bg-gray-50 border-l-4 p-4 rounded-lg mb-6" style="border-color:${cc.color}">',
  '                        <p class="text-gray-800 font-medium">${q}</p>',
  '                    </div>',
  '                    <div class="space-y-3 mb-6">',
  '                        ${[1,2,3,4,5].map(score => `',
  '                            <div class="option-card border-2 rounded-lg p-4 ${currentVal===score?\'selected\':\'\'}" onclick="p2Answers[\'${currentKey}\']=${score};renderP2Question()" style="${currentVal===score?\'border-color:\'+cc.color+\';background:\'+cc.color+\';color:white\':\'\'}">',
  '                                <div class="flex items-center">',
  '                                    <div class="w-10 h-10 rounded-full border-2 flex items-center justify-center font-bold mr-4 ${currentVal===score?\'bg-white text-gray-800\':\'border-gray-300 text-gray-600\'}">${score}</div>',
  '                                    <span>${[\'\',\'น้อยมาก\',\'น้อย\',\'ปานกลาง\',\'ดี\',\'ดีมาก\'][score]}</span>',
  '                                </div>',
  '                            </div>',
  '                        `).join(\'\')}',
  '                    </div>',
  '                    <div class="flex justify-between">',
  '                        <button onclick="p2Prev()" class="bg-gray-300 text-gray-700 px-6 py-3 rounded-lg hover:bg-gray-400 disabled:opacity-50" ${p2CurrentCC===0&&p2CurrentQuestion===0?\'disabled\':\'\'}><i class="fas fa-arrow-left mr-2"></i>ก่อนหน้า</button>',
  '                        ${p2CurrentCC===CC_DIMENSIONS.length-1&&p2CurrentQuestion===cc.questions.length-1',
  '                            ? `<button onclick="submitP2Assessment()" class="bg-green-600 text-white px-8 py-3 rounded-lg hover:bg-green-700 font-semibold"><i class="fas fa-check-circle mr-2"></i>ส่งผลการประเมิน</button>`',
  '                            : `<button onclick="p2Next()" class="text-white px-6 py-3 rounded-lg hover:opacity-90" style="background:${cc.color}">ถัดไป<i class="fas fa-arrow-right ml-2"></i></button>`}',
  '                    </div>',
  '                </div>',
  '            `;',
  '        }',
  '',
  '        function p2Next() {',
  '            const cc = CC_DIMENSIONS[p2CurrentCC];',
  '            if (p2CurrentQuestion < cc.questions.length - 1) { p2CurrentQuestion++; }',
  '            else if (p2CurrentCC < CC_DIMENSIONS.length - 1) { p2CurrentCC++; p2CurrentQuestion = 0; }',
  '            renderP2Question();',
  '        }',
  '        function p2Prev() {',
  '            if (p2CurrentQuestion > 0) { p2CurrentQuestion--; }',
  '            else if (p2CurrentCC > 0) { p2CurrentCC--; p2CurrentQuestion = CC_DIMENSIONS[p2CurrentCC].questions.length - 1; }',
  '            renderP2Question();',
  '        }',
  '',
  '        function submitP2Assessment() {',
  '            const totalQ = CC_DIMENSIONS.reduce((s,c) => s + c.questions.length, 0);',
  '            const answered = Object.keys(p2Answers).length;',
  '            if (answered < totalQ) {',
  '                if (!confirm(`ยังไม่ได้ตอบ ${totalQ - answered} ข้อ ต้องการส่งหรือไม่?`)) return;',
  '            } else {',
  '                if (!confirm(\'ต้องการส่งผลการประเมิน CC หรือไม่?\')) return;',
  '            }',
  '            // Calculate CC scores',
  '            const ccScores = {};',
  '            CC_DIMENSIONS.forEach(cc => {',
  '                let total = 0, count = 0;',
  '                cc.questions.forEach((_, qi) => {',
  '                    const val = p2Answers[cc.key + \'_q\' + qi];',
  '                    if (val) { total += val; count++; }',
  '                });',
  '                ccScores[cc.key] = count > 0 ? Math.round((total / (count * 5)) * 100) : 0;',
  '            });',
  '            // Save to applicant',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === p2CurrentApplicant.id);',
  '            if (app) {',
  '                app.ccScores = ccScores;',
  '                app.status = \'assessed\';',
  '                if (!app.history) app.history = [];',
  '                app.history.push({ action:\'ประเมิน CC\', timestamp: new Date().toISOString(), note: `CC Score: ${calcCCOverall(ccScores)}` });',
  '                saveApplicantData(app);',
  '            }',
  '            // Show result with radar chart',
  '            renderP2Result(ccScores);',
  '        }',
  '',
  '        function calcCCOverall(ccScores) {',
  '            const vals = Object.values(ccScores);',
  '            return vals.length ? Math.round(vals.reduce((a,b)=>a+b,0)/vals.length) : 0;'
];
