var PP7_PART_2 = [
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: P5 พัฒนา -->',
  '    <div id="tab-develop" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">🎓</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">P5 — พัฒนา</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">พัฒนาตาม CC — สร้างแผนพัฒนาบุคลากรเฉพาะบุคคล ตามจุดแข็งและจุดที่ต้องปรับปรุง</p>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full font-semibold"><i class="fas fa-tools mr-2"></i>กำลังพัฒนา</span>',
  '                </div>',
  '                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">',
  '                    <div class="bg-violet-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">📚</div><h3 class="font-bold text-gray-800 mb-1">Learning Path</h3><p class="text-sm text-gray-600">เส้นทางการเรียนรู้</p></div>',
  '                    <div class="bg-fuchsia-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">🎯</div><h3 class="font-bold text-gray-800 mb-1">IDP</h3><p class="text-sm text-gray-600">แผนพัฒนารายบุคคล</p></div>',
  '                    <div class="bg-purple-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">📊</div><h3 class="font-bold text-gray-800 mb-1">Growth Track</h3><p class="text-sm text-gray-600">ติดตามการเติบโต</p></div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: P6 ค่าตอบแทน -->',
  '    <div id="tab-welfare" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">💰</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">P6 — ค่าตอบแทน</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">ตอบแทนตาม CC — ระบบค่าตอบแทนที่เป็นธรรม สอดคล้องกับศักยภาพและผลงาน</p>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full font-semibold"><i class="fas fa-tools mr-2"></i>กำลังพัฒนา</span>',
  '                </div>',
  '                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">',
  '                    <div class="bg-emerald-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">💵</div><h3 class="font-bold text-gray-800 mb-1">Salary Structure</h3><p class="text-sm text-gray-600">โครงสร้างเงินเดือนตาม CC</p></div>',
  '                    <div class="bg-green-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">🎁</div><h3 class="font-bold text-gray-800 mb-1">Bonus</h3><p class="text-sm text-gray-600">โบนัสตามผลงาน</p></div>',
  '                    <div class="bg-teal-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">📊</div><h3 class="font-bold text-gray-800 mb-1">Benefits</h3><p class="text-sm text-gray-600">สวัสดิการครบวงจร</p></div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: P7 คุณภาพชีวิต -->',
  '    <div id="tab-quality" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">🌿</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">P7 — คุณภาพชีวิต</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">5 องค์ประกอบ: Health, Wealth, Well-being, Time, Fun — ดูแลคุณภาพชีวิตสมาชิกแบบองค์รวม</p>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full font-semibold"><i class="fas fa-tools mr-2"></i>กำลังพัฒนา</span>',
  '                </div>',
  '                <div class="grid grid-cols-2 md:grid-cols-5 gap-4">',
  '                    <div class="bg-red-50 p-5 rounded-lg text-center border-t-4 border-red-400"><div class="text-3xl mb-2">❤️</div><h3 class="font-bold text-gray-800 text-sm">Health</h3><p class="text-xs text-gray-600 mt-1">สุขภาพกายใจ</p></div>',
  '                    <div class="bg-yellow-50 p-5 rounded-lg text-center border-t-4 border-yellow-400"><div class="text-3xl mb-2">💎</div><h3 class="font-bold text-gray-800 text-sm">Wealth</h3><p class="text-xs text-gray-600 mt-1">ความมั่งคั่ง</p></div>',
  '                    <div class="bg-green-50 p-5 rounded-lg text-center border-t-4 border-green-400"><div class="text-3xl mb-2">🧘</div><h3 class="font-bold text-gray-800 text-sm">Well-being</h3><p class="text-xs text-gray-600 mt-1">ความสุข</p></div>',
  '                    <div class="bg-blue-50 p-5 rounded-lg text-center border-t-4 border-blue-400"><div class="text-3xl mb-2">⏰</div><h3 class="font-bold text-gray-800 text-sm">Time</h3><p class="text-xs text-gray-600 mt-1">เวลาคุณภาพ</p></div>',
  '                    <div class="bg-pink-50 p-5 rounded-lg text-center border-t-4 border-pink-400"><div class="text-3xl mb-2">🎉</div><h3 class="font-bold text-gray-800 text-sm">Fun</h3><p class="text-xs text-gray-600 mt-1">ความสนุก</p></div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: กฎหมายแรงงาน -->',
  '    <div id="tab-labor-law" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">⚖️</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">กฎหมายแรงงาน</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">ข้อมูลอ้างอิงกฎหมายแรงงาน — พ.ร.บ. คุ้มครองแรงงาน, ประกันสังคม, สวัสดิการตามกฎหมาย</p>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full font-semibold"><i class="fas fa-tools mr-2"></i>กำลังพัฒนา</span>',
  '                </div>',
  '                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">',
  '                    <div class="bg-slate-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">📜</div><h3 class="font-bold text-gray-800 mb-1">พ.ร.บ. คุ้มครองแรงงาน</h3><p class="text-sm text-gray-600">สิทธิลูกจ้าง นายจ้าง</p></div>',
  '                    <div class="bg-slate-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">🏥</div><h3 class="font-bold text-gray-800 mb-1">ประกันสังคม</h3><p class="text-sm text-gray-600">สิทธิประโยชน์ประกันสังคม</p></div>',
  '                    <div class="bg-slate-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">📋</div><h3 class="font-bold text-gray-800 mb-1">ข้อกฎหมายที่เกี่ยวข้อง</h3><p class="text-sm text-gray-600">ภาษี, สวัสดิการ, ความปลอดภัย</p></div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: ระเบียบบริษัท -->',
  '    <div id="tab-pkg-rules" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">📘</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">ระเบียบบริษัท PKG</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">ข้อมูลอ้างอิงระเบียบภายในองค์กร — ข้อบังคับการทำงาน วินัย โทษทางวินัย และสวัสดิการบริษัท</p>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full font-semibold"><i class="fas fa-tools mr-2"></i>กำลังพัฒนา</span>',
  '                </div>',
  '                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">',
  '                    <div class="bg-blue-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">📖</div><h3 class="font-bold text-gray-800 mb-1">ข้อบังคับทำงาน</h3><p class="text-sm text-gray-600">เวลาทำงาน ลา หยุด</p></div>',
  '                    <div class="bg-indigo-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">⚠️</div><h3 class="font-bold text-gray-800 mb-1">วินัยและโทษ</h3><p class="text-sm text-gray-600">มาตรการทางวินัย</p></div>',
  '                    <div class="bg-violet-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">🎁</div><h3 class="font-bold text-gray-800 mb-1">สวัสดิการ PKG</h3><p class="text-sm text-gray-600">สิทธิประโยชน์เพิ่มเติม</p></div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: วิจัย -->',
  '    <div id="tab-research" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">🔬</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">วิจัย PP7</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">งานวิจัยและองค์ความรู้เกี่ยวกับระบบ PP7 — การศึกษา ทดลอง และพัฒนาโมเดลบริหารบุคลากร</p>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full font-semibold"><i class="fas fa-tools mr-2"></i>กำลังพัฒนา</span>',
  '                </div>',
  '                <div class="grid grid-cols-1 md:grid-cols-3 gap-6">',
  '                    <div class="bg-cyan-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">📄</div><h3 class="font-bold text-gray-800 mb-1">งานวิจัย</h3><p class="text-sm text-gray-600">เอกสารวิจัย PP7</p></div>',
  '                    <div class="bg-sky-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">📊</div><h3 class="font-bold text-gray-800 mb-1">ข้อมูลสถิติ</h3><p class="text-sm text-gray-600">ผลการวิเคราะห์ข้อมูล</p></div>',
  '                    <div class="bg-blue-50 p-6 rounded-lg text-center"><div class="text-3xl mb-2">💡</div><h3 class="font-bold text-gray-800 mb-1">Best Practices</h3><p class="text-sm text-gray-600">แนวทางปฏิบัติที่ดี</p></div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: บทสรุปผู้บริหาร -->',
  '    <div id="tab-executive" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">📌</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">บทสรุปผู้บริหาร</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">Dashboard ผู้บริหาร — ภาพรวมระบบ PP7 ทั้งหมด แบบ Real-time</p>',
  '            </div>',
  '            <div class="bg-white rounded-xl shadow-lg p-8">',
  '                <div class="flex items-center justify-center gap-3 mb-6">',
  '                    <span class="inline-flex items-center px-4 py-2 bg-amber-100 text-amber-800 rounded-full font-semibold"><i class="fas fa-tools mr-2"></i>กำลังพัฒนา</span>',
  '                </div>',
  '                <div class="grid grid-cols-2 md:grid-cols-4 gap-4">',
  '                    <div class="bg-gradient-to-br from-blue-500 to-blue-600 text-white p-5 rounded-lg text-center"><div class="text-3xl font-bold">P1</div><p class="text-sm opacity-90 mt-1">แสวงหา</p></div>',
  '                    <div class="bg-gradient-to-br from-purple-500 to-purple-600 text-white p-5 rounded-lg text-center"><div class="text-3xl font-bold">P2</div><p class="text-sm opacity-90 mt-1">หยั่งประเมิน</p></div>',
  '                    <div class="bg-gradient-to-br from-emerald-500 to-emerald-600 text-white p-5 rounded-lg text-center"><div class="text-3xl font-bold">P3</div><p class="text-sm opacity-90 mt-1">จับคู่</p></div>',
  '                    <div class="bg-gradient-to-br from-rose-500 to-rose-600 text-white p-5 rounded-lg text-center"><div class="text-3xl font-bold">P4</div><p class="text-sm opacity-90 mt-1">ประเมินผล</p></div>',
  '                    <div class="bg-gradient-to-br from-violet-500 to-violet-600 text-white p-5 rounded-lg text-center"><div class="text-3xl font-bold">P5</div><p class="text-sm opacity-90 mt-1">พัฒนา</p></div>',
  '                    <div class="bg-gradient-to-br from-amber-500 to-amber-600 text-white p-5 rounded-lg text-center"><div class="text-3xl font-bold">P6</div><p class="text-sm opacity-90 mt-1">ค่าตอบแทน</p></div>',
  '                    <div class="bg-gradient-to-br from-green-500 to-green-600 text-white p-5 rounded-lg text-center"><div class="text-3xl font-bold">P7</div><p class="text-sm opacity-90 mt-1">คุณภาพชีวิต</p></div>',
  '                    <div class="bg-gradient-to-br from-slate-700 to-slate-800 text-white p-5 rounded-lg text-center"><div class="text-3xl font-bold">📊</div><p class="text-sm opacity-90 mt-1">ภาพรวม</p></div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Tab: โครงสร้างธุรกิจ (Master Data สำหรับ P1) -->',
  '    <div id="tab-business-structure" class="hidden">',
  '        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">',
  '            <div class="text-center mb-8">',
  '                <div class="text-6xl mb-4">🏗️</div>',
  '                <h1 class="text-4xl font-bold text-gray-800 mb-3">โครงสร้างธุรกิจ</h1>',
  '                <p class="text-lg text-gray-600 max-w-2xl mx-auto">ศูนย์รวมจัดการข้อมูลตั้งต้น — ผู้สมัครงานใหม่, ขออัตรากำลังคน, โอนย้าย, เลื่อนตำแหน่ง</p>',
  '                <p class="text-sm text-gray-500 mt-2">อัพเดทล่าสุด: <span id="last-updated">-</span></p>',
  '            </div>',
  '',
  '            <!-- Action Panel: จัดการข้อมูลตั้งต้น -->',
  '            <div class="bg-gradient-to-r from-purple-50 to-blue-50 rounded-xl shadow-lg p-6 mb-6 border-2 border-purple-200">',
  '                <div class="flex items-center gap-3 mb-4">',
  '                    <div class="w-10 h-10 bg-purple-600 rounded-lg flex items-center justify-center text-white text-xl">⚡</div>',
  '                    <h2 class="text-2xl font-bold text-gray-800">จัดการข้อมูลตั้งต้น (Action Panel)</h2>',
  '                </div>',
  '                <p class="text-sm text-gray-600 mb-4">เลือกการดำเนินการที่ต้องการ:</p>',
  '                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">',
  '                    <button onclick="showActionModal(\'new-applicant\')" class="bg-white hover:bg-blue-50 border-2 border-blue-300 rounded-lg p-4 text-left transition shadow-sm hover:shadow-md">',
  '                        <div class="text-3xl mb-2">📥</div>',
  '                        <h3 class="font-bold text-blue-800 mb-1">ผู้สมัครงานใหม่</h3>',
  '                        <p class="text-xs text-gray-600">เพิ่มผู้สมัครเข้า DB1 (Stock ผู้สมัคร)</p>',
  '                    </button>',
  '                    <button onclick="showActionModal(\'new-position\')" class="bg-white hover:bg-green-50 border-2 border-green-300 rounded-lg p-4 text-left transition shadow-sm hover:shadow-md">',
  '                        <div class="text-3xl mb-2">🏗️</div>',
  '                        <h3 class="font-bold text-green-800 mb-1">ขออัตรากำลังคน</h3>',
  '                        <p class="text-xs text-gray-600">สร้างโครงสร้างใหม่ / เพิ่มตำแหน่ง (DB2)</p>',
  '                    </button>',
  '                    <button onclick="showActionModal(\'transfer\')" class="bg-white hover:bg-orange-50 border-2 border-orange-300 rounded-lg p-4 text-left transition shadow-sm hover:shadow-md">',
  '                        <div class="text-3xl mb-2">🔄</div>',
  '                        <h3 class="font-bold text-orange-800 mb-1">โอนย้ายสมาชิก</h3>',
  '                        <p class="text-xs text-gray-600">ย้ายบริษัท / ทีม / function (DB2)</p>',
  '                    </button>',
  '                    <button onclick="showActionModal(\'promotion\')" class="bg-white hover:bg-red-50 border-2 border-red-300 rounded-lg p-4 text-left transition shadow-sm hover:shadow-md">',
  '                        <div class="text-3xl mb-2">📈</div>',
  '                        <h3 class="font-bold text-red-800 mb-1">เลื่อนตำแหน่ง</h3>',
  '                        <p class="text-xs text-gray-600">Promotion สมาชิก (DB2)</p>',
  '                    </button>',
  '                </div>',
  '            </div>',
  '',
  '            <!-- Database Architecture -->',
  '            <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                <div class="flex items-center gap-3 mb-4">',
  '                    <div class="w-10 h-10 bg-indigo-600 rounded-lg flex items-center justify-center text-white text-xl">🗄️</div>',
  '                    <h2 class="text-2xl font-bold text-gray-800">Database Architecture (3 ฐานข้อมูล)</h2>',
  '                </div>',
  '                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">',
  '                    <div class="bg-blue-50 p-4 rounded-lg border-2 border-blue-200">',
  '                        <h3 class="font-bold text-blue-800 mb-2">📥 Database 1: ข้อมูลผู้สมัครงาน</h3>',
  '                        <p class="text-xs text-gray-600 mb-2"><strong>Trigger:</strong> ผู้สมัครสมัครงานเข้ามา</p>',
  '                        <ul class="text-xs text-gray-700 space-y-1">',
  '                            <li>• Stock ข้อมูลผู้สมัคร (สมัครเข้ามาโดยไม่จำเป็นต้องเลือกว่าตำแหน่งงานไหนว่าง)</li>',
  '                            <li>• ข้อมูลผู้สมัครเข้ามากองในฐาน และเราสามารถเลือกใช้ได้โดย AI พิจารณาคุณสมบัติตามพื้นที่</li>',
  '                            <li>• เอกสารการสมัครงาน</li>',
  '                        </ul>',
  '                    </div>',
  '                    <div class="bg-green-50 p-4 rounded-lg border-2 border-green-200">',
  '                        <h3 class="font-bold text-green-800 mb-2">🏗️ Database 2: ข้อมูลโครงสร้าง</h3>',
  '                        <p class="text-xs text-gray-600 mb-2"><strong>Trigger:</strong> คีย์ขออัตรากำลังคน / สร้างโครงสร้างใหม่ / โอนย้าย / เลื่อนตำแหน่ง</p>',
  '                        <div class="space-y-2">',
  '                            <div class="bg-white p-2 rounded">',
  '                                <p class="text-xs font-semibold text-gray-800">โครงสร้างภายนอก:</p>',
  '                                <ul class="text-xs text-gray-700 space-y-1">',
  '                                    <li>• เงินเดือน เบี้ยเลี้ยง ค่าตอบแทนตามต้นสังกัด</li>',
  '                                    <li>• ประกันสังคม สิทธิสวัสดิการรัฐ</li>',
  '                                    <li>• อยู่ใน PKG Member</li>',
  '                                </ul>',
  '                            </div>',
  '                            <div class="bg-white p-2 rounded">',
  '                                <p class="text-xs font-semibold text-gray-800">โครงสร้างภายใน:</p>',
  '                                <ul class="text-xs text-gray-700 space-y-1">',
  '                                    <li>• โครงสร้างเครือข่าย ข้าม function ได้</li>',
  '                                    <li>• กลุ่มธุรกิจ PMSG, AAMG, CPDG</li>',
  '                                    <li>• ประเมินเครดิต ค่าตอบแทน ข้ามสายงานได้</li>',
  '                                </ul>',
  '                            </div>',
  '                        </div>',
  '                    </div>',
  '                    <div class="bg-red-50 p-4 rounded-lg border-2 border-red-200">',
  '                        <h3 class="font-bold text-red-800 mb-2">📤 Database 3: ข้อมูลสมาชิกลาออก</h3>',
  '                        <p class="text-xs text-gray-600 mb-2"><strong>Trigger:</strong> สมาชิกมีผลลาออก</p>',
  '                        <ul class="text-xs text-gray-700 space-y-1">',
  '                            <li>• ข้อมูลทั้งหมดจะถูกดึงออกไปอยู่ฐานนี้ ตั้งแต่วันที่มีผลลาออก</li>',
  '                            <li>• สามารถดึงกลับเข้าไปใหม่ได้กรณีที่เปลี่ยนใจกลับมาทำงาน</li>',
  '                            <li>• ต้องทำการ update ให้เป็นปัจจุบัน</li>',
  '                            <li>• <strong>เก็บไว้ 10 ปี</strong></li>',
  '                        </ul>',
  '                    </div>',
  '                </div>',
  '            </div>',
  '',
  '            <!-- ข้อมูลโครงสร้างบริษัท ภาษี -->',
  '            <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                <div class="flex items-center gap-3 mb-4">',
  '                    <div class="w-10 h-10 bg-blue-500 rounded-lg flex items-center justify-center text-white text-xl">📋</div>',
  '                    <h2 class="text-2xl font-bold text-gray-800">ข้อมูลโครงสร้างบริษัท ภาษี</h2>',
  '                </div>',
  '                <div class="overflow-x-auto">',
  '                    <table class="w-full text-sm" id="tax-table">',
  '                        <thead>',
  '                            <tr class="bg-blue-100">',
  '                                <th class="px-3 py-2 text-left font-semibold">รหัสสมาชิก</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ชื่อสมาชิก</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ประเทศ</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">บริษัท</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">สาขา</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ตำแหน่งงาน</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">คุณสมบัติ</th>',
  '                            </tr>',
  '                        </thead>',
  '                        <tbody id="tax-tbody"></tbody>',
  '                    </table>',
  '                </div>',
  '            </div>',
  '',
  '            <!-- ข้อมูลโครงสร้างบริษัท บริหาร -->',
  '            <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                <div class="flex items-center gap-3 mb-4">',
  '                    <div class="w-10 h-10 bg-green-600 rounded-lg flex items-center justify-center text-white text-xl">🏢</div>',
  '                    <h2 class="text-2xl font-bold text-gray-800">ข้อมูลโครงสร้างบริษัท บริหาร</h2>',
  '                </div>',
  '                <div class="overflow-x-auto">',
  '                    <table class="w-full text-sm">',
  '                        <thead>',
  '                            <tr class="bg-green-100">',
  '                                <th class="px-3 py-2 text-left font-semibold">ประเทศ</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">บริษัท</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ทีม</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">กรุ๊ป</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">บทบาท</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">จุดมุ่งหมายทีม</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">Objective</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">Key Result</th>',
  '                            </tr>',
  '                        </thead>',
  '                        <tbody id="admin-tbody"></tbody>',
  '                    </table>',
  '                </div>',
  '            </div>',
  '',
  '            <!-- DATAโครงสร้างบริษัทภายนอก -->',
  '            <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                <div class="flex items-center gap-3 mb-4">',
  '                    <div class="w-10 h-10 bg-purple-600 rounded-lg flex items-center justify-center text-white text-xl">🏭</div>',
  '                    <h2 class="text-2xl font-bold text-gray-800">DATAโครงสร้างบริษัทภายนอก</h2>',
  '                </div>',
  '                <div class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4" id="external-companies-grid"></div>',
  '                <div class="overflow-x-auto">',
  '                    <table class="w-full text-sm">',
  '                        <thead>',
  '                            <tr class="bg-purple-100">',
  '                                <th class="px-3 py-2 text-left font-semibold">บริษัท</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">สาขา</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ฝ่าย</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">แผนก</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ตำแหน่งงาน</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ชื่อภาษาอังกฤษ</th>',
  '                            </tr>',
  '                        </thead>',
  '                        <tbody id="external-tbody"></tbody>',
  '                    </table>',
  '                </div>',
  '            </div>',
  '',
  '            <!-- Center BCT Flowchart ภาษี -->',
  '            <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                <div class="flex items-center gap-3 mb-4">',
  '                    <div class="w-10 h-10 bg-orange-500 rounded-lg flex items-center justify-center text-white text-xl">📊</div>',
  '                    <h2 class="text-2xl font-bold text-gray-800">Center BCT โครงสร้าง Flowchart ภาษี</h2>',
  '                </div>',
  '                <div class="overflow-x-auto">',
  '                    <table class="w-full text-sm">',
  '                        <thead>',
  '                            <tr class="bg-orange-100">',
  '                                <th class="px-3 py-2 text-left font-semibold">รหัส</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">บริษัท</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">Flow S</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">Flow XL</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">Flow S_M</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">Flow M_M</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">Flow XL_M</th>',
  '                            </tr>',
  '                        </thead>',
  '                        <tbody id="flowchart-tbody"></tbody>',
  '                    </table>',
  '                </div>',
  '            </div>',
  '',
  '            <!-- DATAโครงสร้างบริษัทภายใน -->',
  '            <div class="bg-white rounded-xl shadow-lg p-6 mb-6">',
  '                <div class="flex items-center gap-3 mb-4">',
  '                    <div class="w-10 h-10 bg-red-600 rounded-lg flex items-center justify-center text-white text-xl">🏠</div>',
  '                    <h2 class="text-2xl font-bold text-gray-800">DATAโครงสร้างบริษัทภายใน</h2>',
  '                </div>',
  '                <div class="overflow-x-auto">',
  '                    <table class="w-full text-sm">',
  '                        <thead>',
  '                            <tr class="bg-red-100">',
  '                                <th class="px-3 py-2 text-left font-semibold">วันที่ส่ง</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">รหัสสมาชิก</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ชื่อสมาชิก</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ประเทศ</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">บริษัท</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">ทีม</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">บทบาท</th>',
  '                                <th class="px-3 py-2 text-left font-semibold">จุดมุ่งหมาย</th>',
  '                            </tr>',
  '                        </thead>',
  '                        <tbody id="internal-tbody"></tbody>',
  '                    </table>',
  '                </div>',
  '            </div>',
  '',
  '            <!-- หมายเหตุ -->',
  '            <div class="bg-amber-50 border border-amber-200 rounded-lg p-4">',
  '                <h3 class="font-semibold text-amber-800 mb-2">📌 หมายเหตุ</h3>',
  '                <ul class="text-sm text-amber-700 space-y-1">',
  '                    <li>• Tab นี้เป็น <strong>ศูนย์รวมจัดการข้อมูลตั้งต้น</strong> สำหรับ 4 กรณี: ผู้สมัครงานใหม่, ขออัตรากำลังคน, โอนย้าย, เลื่อนตำแหน่ง</li>',
  '                    <li>• ข้อมูลเข้า <strong>DB1</strong> (ผู้สมัคร) หรือ <strong>DB2</strong> (โครงสร้าง) ตามกรณี</li>',
  '                    <li>• ข้อมูลเต็มอยู่ใน Google Sheet: <a href="https://docs.google.com/spreadsheets/d/1yP_l-WmsnlkMDCkZB7ulhe6oS_AAex8iE3LYdPdg-uc/edit" target="_blank" class="text-blue-600 hover:underline">โครงสร้าง ระบบ PP7</a></li>',
  '                    <li>• Flow S/XL/S_M/M_M/XL_M = ลิงค์ flowchart ภาษีแต่ละประเภท</li>',
  '                    <li>• ข้อมูลบริษัทภายนอกและภายในสามารถ import เพิ่มจาก source ได้</li>',
  '                </ul>',
  '            </div>',
  '        </div>',
  '    </div>',
  '',
  '    </div><!-- /main-content -->',
  '',
  '    <!-- Action Modal -->',
  '    <div id="actionModal" class="hidden fixed inset-0 bg-black bg-opacity-50 z-[9999] flex items-center justify-center p-4">',
  '        <div class="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">',
  '            <div class="flex justify-between items-center mb-6 p-6 border-b">',
  '                <h2 id="actionModalTitle" class="text-2xl font-bold text-gray-800"></h2>',
  '                <button onclick="hideActionModal()" class="text-gray-400 hover:text-gray-600 text-2xl">&times;</button>',
  '            </div>',
  '            <div id="actionModalContent" class="p-6"></div>',
  '        </div>',
  '    </div>',
  '',
  '    <!-- Login Modal -->'
];
