var PP7_PART_7 = [
  '                                        <div>',
  '                                            <h4 class="font-bold text-gray-800 text-lg">${job.title}</h4>',
  '                                            <p class="text-sm text-gray-600">${job.department} | ${job.level} | ${job.salary} ฿</p>',
  '                                        </div>',
  '                                    </div>',
  '                                    <div class="text-center">',
  '                                        <div class="text-3xl font-bold ${idx===0?\'text-amber-600\':\'text-gray-700\'}">${job.matchScore}</div>',
  '                                        <div class="text-xs text-gray-500">Match Score</div>',
  '                                    </div>',
  '                                </div>',
  '                                <div class="w-full bg-gray-200 rounded-full h-3 mb-3">',
  '                                    <div class="h-3 rounded-full bg-gradient-to-r ${colors[idx]}" style="width:${job.matchScore}%"></div>',
  '                                </div>',
  '                                <div class="grid grid-cols-2 gap-2 text-xs">',
  '                                    <div class="bg-white p-2 rounded">',
  '                                        <span class="text-gray-500">ทักษะที่ต้องการ:</span>',
  '                                        <span class="text-gray-700 ml-1">${job.requiredSkills.join(\', \')}</span>',
  '                                    </div>',
  '                                    <div class="bg-white p-2 rounded">',
  '                                        <span class="text-gray-500">วุฒิ:</span>',
  '                                        <span class="text-gray-700 ml-1">${job.education}</span>',
  '                                    </div>',
  '                                </div>',
  '                            </div>`;',
  '                        }).join(\'\')}',
  '                    </div>',
  '',
  '                    <div class="flex flex-col sm:flex-row gap-4">',
  '                        <button onclick="hireApplicant(\'${app.id}\',\'${topMatches[0].title}\')" class="flex-1 bg-green-600 text-white py-3 rounded-lg hover:bg-green-700 font-semibold text-lg"><i class="fas fa-user-check mr-2"></i>รับเข้าทำงาน</button>',
  '                        <button onclick="createMember(\'${app.id}\')" class="flex-1 bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 font-semibold text-lg"><i class="fas fa-id-card mr-2"></i>สร้างสมาชิก</button>',
  '                    </div>',
  '                </div>',
  '            `;',
  '            // Draw radar',
  '            setTimeout(() => {',
  '                const ctx = document.getElementById(\'p3RadarChart\');',
  '                if (!ctx) return;',
  '                new Chart(ctx, {',
  '                    type: \'radar\',',
  '                    data: {',
  '                        labels: CC_DIMENSIONS.map(c => c.key),',
  '                        datasets: [{',
  '                            label: \'CC Score\',',
  '                            data: CC_DIMENSIONS.map(c => app.ccScores[c.key]),',
  '                            backgroundColor: \'rgba(16, 185, 129, 0.2)\',',
  '                            borderColor: \'rgba(16, 185, 129, 1)\',',
  '                            borderWidth: 2,',
  '                            pointBackgroundColor: CC_DIMENSIONS.map(c => c.color),',
  '                            pointRadius: 4',
  '                        }]',
  '                    },',
  '                    options: {',
  '                        responsive: true,',
  '                        scales: { r: { beginAtZero: true, max: 100, ticks: { stepSize: 20, font:{size:9} }, pointLabels: { font:{size:11, family:\'Prompt\'} } } },',
  '                        plugins: { legend: { display: false } }',
  '                    }',
  '                });',
  '            }, 100);',
  '        }',
  '',
  '        function hireApplicant(appId, position) {',
  '            if (!confirm(`ยืนยันรับ ${position} เข้าทำงาน?`)) return;',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (app) {',
  '                app.status = \'hired\';',
  '                app.hiredPosition = position;',
  '                app.hiredDate = new Date().toISOString().split(\'T\')[0];',
  '                if (!app.history) app.history = [];',
  '                app.history.push({ action:\'รับเข้าทำงาน\', timestamp: new Date().toISOString(), note: `ตำแหน่ง: ${position}` });',
  '                saveApplicantData(app);',
  '                alert(`✅ รับเข้าทำงานสำเร็จ!\\n\\nชื่อ: ${app.firstName} ${app.lastName}\\nตำแหน่ง: ${position}\\nวันที่: ${app.hiredDate}`);',
  '                renderP3();',
  '            }',
  '        }',
  '',
  '        function createMember(appId) {',
  '            if (!confirm(\'สร้างสมาชิกใหม่ในระบบ?\')) return;',
  '            const all = getAllApplicants();',
  '            const app = all.find(a => a.id === appId);',
  '            if (app) {',
  '                // Save to members list',
  '                const members = JSON.parse(localStorage.getItem(\'pkg_members\') || \'[]\');',
  '                const memberId = \'MEM-\' + Date.now().toString().slice(-6);',
  '                const newMember = {',
  '                    id: memberId,',
  '                    applicantId: app.id,',
  '                    firstName: app.firstName,',
  '                    lastName: app.lastName,',
  '                    phone: app.phone || \'\',',
  '                    email: app.email || \'\',',
  '                    position: app.position || \'\',',
  '                    department: app.department || \'\',',
  '                    branch: app.branch || \'\',',
  '                    ccScores: app.ccScores || {},',
  '                    ccOverall: calcCCOverall(app.ccScores || {}),',
  '                    education: app.education || \'\',',
  '                    experience: app.experience || \'0\',',
  '                    skills: app.skills || \'\',',
  '                    joinedAt: new Date().toISOString(),',
  '                    status: \'active\'',
  '                };',
  '                members.push(newMember);',
  '                localStorage.setItem(\'pkg_members\', JSON.stringify(members));',
  '                // Update applicant status',
  '                app.status = \'member\';',
  '                if (!app.history) app.history = [];',
  '                app.history.push({ action:\'สร้างสมาชิก\', timestamp: new Date().toISOString(), note: `รหัสสมาชิก: ${memberId}` });',
  '                saveApplicantData(app);',
  '                alert(`✅ สร้างสมาชิกสำเร็จ!\\n\\nรหัสสมาชิก: ${memberId}\\nชื่อ: ${app.firstName} ${app.lastName}\\nCC Score: ${newMember.ccOverall}`);',
  '                renderP3();',
  '            }',
  '        }',
  '',
  '        // Hook P2/P3 render on tab show',
  '        const _origShowTab = showTab;',
  '        showTab = function(tabName) {',
  '            _origShowTab(tabName);',
  '            if (tabName === \'assess\') renderP2();',
  '            if (tabName === \'match\') renderP3();',
  '        };',
  '    </script>',
  '    <script>',
  '        // Load business structure data',
  '        async function loadBusinessStructureData() {',
  '            try {',
  '                const response = await fetch(\'business-structure-data.json\');',
  '                const data = await response.json();',
  '                ',
  '                // Update last updated',
  '                document.getElementById(\'last-updated\').textContent = data.meta.lastUpdated;',
  '                ',
  '                // Render tax structure',
  '                const taxTbody = document.getElementById(\'tax-tbody\');',
  '                if (taxTbody && data.taxStructure.sampleData) {',
  '                    taxTbody.innerHTML = data.taxStructure.sampleData.map(item => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2">${item[\'รหัสสมาชิก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ชื่อสมาชิก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ประเทศ\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บริษัท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'สาขา\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ตำแหน่งงาน\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'คุณสมบัติ\'] || \'-\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render admin structure',
  '                const adminTbody = document.getElementById(\'admin-tbody\');',
  '                if (adminTbody && data.adminStructure.sampleData) {',
  '                    adminTbody.innerHTML = data.adminStructure.sampleData.map(item => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2">${item[\'ประเทศ\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บริษัท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ทีม\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'กรุ๊ป\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บทบาท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'จุดมุ่งหมายทีม\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'เป้าหมายทีม\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'ตัววัดผลทีม\'] || \'-\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render external companies grid',
  '                const externalGrid = document.getElementById(\'external-companies-grid\');',
  '                if (externalGrid && data.externalCompanies.companies) {',
  '                    const allCompanies = [...data.externalCompanies.companies, ...(data.externalCompanies.otherCompanies || [])];',
  '                    externalGrid.innerHTML = allCompanies.map(company => `',
  '                        <div class="bg-purple-50 p-3 rounded-lg text-center">',
  '                            <div class="text-2xl font-bold text-purple-600">${company.code}</div>',
  '                            <p class="text-xs text-gray-600">${company.name}</p>',
  '                        </div>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render external positions table',
  '                const externalTbody = document.getElementById(\'external-tbody\');',
  '                if (externalTbody && data.externalCompanies.companies) {',
  '                    let allPositions = [];',
  '                    data.externalCompanies.companies.forEach(company => {',
  '                        if (company.positions) {',
  '                            company.positions.forEach(pos => {',
  '                                allPositions.push({',
  '                                    company: company.name,',
  '                                    ...pos',
  '                                });',
  '                            });',
  '                        }',
  '                    });',
  '                    externalTbody.innerHTML = allPositions.slice(0, 20).map(pos => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2">${pos.company}</td>',
  '                            <td class="px-3 py-2">${pos[\'สาขา\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${pos[\'ฝ่าย\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${pos[\'แผนก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${pos[\'ตำแหน่ง\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${pos[\'ตำแหน่งEn\'] || \'-\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render flowchart tax',
  '                const flowchartTbody = document.getElementById(\'flowchart-tbody\');',
  '                if (flowchartTbody && data.flowchartTax.companies) {',
  '                    flowchartTbody.innerHTML = data.flowchartTax.companies.map(company => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2 font-mono">${company.code}</td>',
  '                            <td class="px-3 py-2 font-semibold">${company.name}</td>',
  '                            <td class="px-3 py-2">${company.flows.S ? `<a href="${company.flows.S}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                            <td class="px-3 py-2">${company.flows.XL ? `<a href="${company.flows.XL}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                            <td class="px-3 py-2">${company.flows.S_M ? `<a href="${company.flows.S_M}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                            <td class="px-3 py-2">${company.flows.M_M ? `<a href="${company.flows.M_M}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                            <td class="px-3 py-2">${company.flows.XL_M ? `<a href="${company.flows.XL_M}" target="_blank" class="text-blue-600 hover:underline">🔗</a>` : \'<span class="text-gray-400">-</span>\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '                // Render internal companies',
  '                const internalTbody = document.getElementById(\'internal-tbody\');',
  '                if (internalTbody && data.internalCompanies.teams) {',
  '                    internalTbody.innerHTML = data.internalCompanies.teams.map(item => `',
  '                        <tr class="border-b hover:bg-gray-50">',
  '                            <td class="px-3 py-2">${item[\'วันที่ส่ง\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'รหัสสมาชิก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ชื่อสมาชิก\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ประเทศ\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บริษัท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'ทีม\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2">${item[\'บทบาท\'] || \'-\'}</td>',
  '                            <td class="px-3 py-2 text-xs">${item[\'จุดมุ่งหมาย\'] || \'-\'}</td>',
  '                        </tr>',
  '                    `).join(\'\');',
  '                }',
  '                ',
  '            } catch (error) {',
  '                console.error(\'Error loading business structure data:\', error);',
  '            }',
  '        }',
  '        ',
  '        // Load data when page loads',
  '        if (document.readyState === \'loading\') {',
  '            document.addEventListener(\'DOMContentLoaded\', loadBusinessStructureData);',
  '        } else {',
  '            loadBusinessStructureData();',
  '        }',
  '    </script>',
  '</body>',
  '</html>',
  ''
];
